import {test,expect,type Page} from '@playwright/test';
async function fixture(page:Page,mode:'fallback'|'evacuation'|'infrastructure'|'traces'){
 await page.goto('/');await page.evaluate(async mode=>{
 const e=await import('/src/simulation/engine.ts' as string),p=await import('/src/persistence/checkpoints.ts' as string);
 const profiles={fallback:'wolf_pack',evacuation:'istari_ember',infrastructure:'troll_hold',traces:'vaire'};let s=e.createMatch([profiles[mode],'human_rohan'],63);s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};s.infrastructureSites={};s.players.p2.ai=false;s.players.p1.stock={P:500,M:500,K:500,E:500};const f=s.facilities['p1:core'],u=s.units['p1:company:0'],owner=s.players.p1;Object.assign(f,{x:4,y:4});Object.assign(u,{x:4,y:4});owner.hero.status='living';owner.hero.readiness=6;s.units[owner.hero.id]={...structuredClone(u),id:owner.hero.id,kind:'hero'};
 if(mode==='evacuation'){f.kind='research';f.job={id:'paid-research',recipe:'technique',remaining:2,started:s.turn,cost:{P:0,M:20,K:30,E:10},supply:0,great:0,binding:0};s.facilities.refuge={...structuredClone(f),id:'refuge',kind:'refuge',x:6,workers:1,job:undefined};}
 if(mode==='infrastructure'){f.kind='workshop';f.x=3;const worker=(Object.values(s.units) as Array<{owner:string;kind:string;x:number;y:number}>).find(v=>v.owner==='p1'&&v.kind==='worker')!;Object.assign(worker,{x:4,y:4});s.infrastructureSites.site={id:'site',owner:'p1',kind:'haulway',x:4,y:4,blocked:true,originalCapacity:1,material:'stone',yield:{P:0,M:0,K:0,E:0},consumed:false};}
 if(mode==='traces'){Object.assign(s.units['p2:company:0'],{x:4,y:4,name:'Unestablished secret identity'});const order={id:'fixture-travel',seat:'p2',seq:s.nextSeq.p2,turn:s.turn,revision:s.revision,action:{kind:'move',unit:'p2:company:0',x:5,y:4}};const result=e.submit(s,order);if(!result.ok)throw new Error(result.reason);s=e.resolveWeek(result.state);}
 await p.saveCheckpoint(s);
 },mode);await page.getByRole('button',{name:'Continue saved match'}).click();
}
async function open(page:Page,title:string){const detail=page.getByText(title,{exact:true}).locator('..');if(await detail.getAttribute('open')===null)await page.getByText(title,{exact:true}).click();}
async function confirm(page:Page,title:string){await page.getByRole('button',{name:title,exact:true}).click();await page.getByRole('button',{name:'Confirm order'}).click();}
async function resolve(page:Page){const before=await page.locator('.topbar').innerText();await page.getByRole('button',{name:'Resolve week'}).click();await expect(page.locator('.topbar')).not.toHaveText(before);}
async function saved(page:Page){return page.evaluate(async()=>{const p=await import('/src/persistence/checkpoints.ts' as string);return(await p.loadCheckpoint()).state;});}
test('wolf ordinary fallback declares an operation and moves only after response',async({page})=>{await fixture(page,'fallback');await page.locator('#entity').selectOption('p1:company:0');await page.locator('#dest-x').fill('4');await page.locator('#dest-y').fill('5');await open(page,'Declared withdrawal and pursuit');await confirm(page,'Review declared fallback');await resolve(page);await expect(page.locator('#controls')).toContainText('(4, 4)');await resolve(page);await expect(page.locator('#controls')).toContainText('(4, 5)');});
test('Ember prepared evacuation transfers existing staff and pauses paid production',async({page})=>{await fixture(page,'evacuation');await page.getByRole('button',{name:'Economy',exact:true}).click();await open(page,'Prepared worksite evacuation');await page.locator('#worksite-source').selectOption('p1:core');await page.locator('#worksite-refuge').selectOption('refuge');await confirm(page,'Review evacuation preparation');await open(page,'Prepared worksite evacuation');await confirm(page,'Review prepared withdrawal');await resolve(page);const s=await saved(page);expect(s.facilities['p1:core'].workers).toBe(0);expect(s.facilities.refuge.workers).toBe(4);expect(s.facilities['p1:core'].job.remaining).toBe(2);});
test('paid restoration clears an existing haulway through a real crew queue',async({page})=>{await fixture(page,'infrastructure');await page.getByRole('button',{name:'Economy',exact:true}).click();await open(page,'Existing routes and finite salvage');await page.locator('#infra-site').selectOption('site');await page.locator('#infra-facility').selectOption('p1:core');await confirm(page,'Review funded restoration or salvage');await resolve(page);expect((await saved(page)).infrastructureSites.site.blocked).toBe(true);await resolve(page);const s=await saved(page);expect(s.infrastructureSites.site.blocked).toBe(false);expect(s.infrastructureSites.site.yield).toEqual({P:0,M:0,K:0,E:0});});
test('Vaire inspects actual prior movement as dated uncertain evidence without identity',async({page})=>{await fixture(page,'traces');await page.getByRole('button',{name:'Hero',exact:true}).click();await open(page,'Dated trails and surveyed routes');await confirm(page,'Review local trace inspection');await resolve(page);await open(page,'Dated trails and surveyed routes');const panel=page.getByText('Dated trails and surveyed routes',{exact:true}).locator('..');await expect(panel).toContainText('(4,4) → (5,4)');await expect(panel).toContainText('No identity');await expect(panel).not.toContainText('Unestablished secret identity');});
