import {test,expect} from '@playwright/test';
import type {Action,Match} from '../../src/simulation/types';
test('Vairë preserves an ordinarily unlocked plan through review, keyboard cancellation and checkpoint reload',async({page})=>{await page.goto('/');await page.evaluate(async()=>{const {createMatch,submit,resolveWeek}=await import('/src/simulation/engine.ts' as string);const {saveCheckpoint}=await import('/src/persistence/checkpoints.ts' as string);const {recipe}=await import('/src/content/catalog.ts' as string);let s:Match=createMatch(['vaire','human_gondor'],127);s.players.p2.ai=false;for(const k of ['P','M','K','E']as const)s.players.p1.stock[k]=2000;const run=(action:Action)=>{const r=submit(s,{id:`p1-${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});if(!r.ok)throw Error(r.reason);s=resolveWeek(r.state);};run({kind:'produce',facility:'p1:core',recipe:'component'});run({kind:'produce',facility:'p1:core',recipe:'hero'});for(let i=1;i<recipe('vaire','hero').turns;i++)s=resolveWeek(s);run({kind:'build',building:'archive',x:4,y:5});const archive=Object.values(s.facilities).find(f=>f.owner==='p1'&&f.kind==='archive')!;run({kind:'produce',facility:archive.id,recipe:'plan-equipment'});await saveCheckpoint(s);});await page.getByRole('button',{name:'Continue saved match'}).click();await page.getByRole('button',{name:'Economy',exact:true}).click();await page.getByText('The Remembered Workshop',{exact:true}).click();await page.getByRole('button',{name:'Review preserve plan',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Review preserve plan',exact:true})).toBeFocused();await page.getByRole('button',{name:'Review preserve plan',exact:true}).click();await page.getByRole('button',{name:'Confirm order',exact:true}).click();await page.getByRole('button',{name:'Resolve week →',exact:true}).click();await expect(page.locator('#status')).toContainText('committed and saved');await page.reload();await page.getByRole('button',{name:'Continue saved match'}).click();await page.getByRole('button',{name:'Economy',exact:true}).click();await page.getByText('The Remembered Workshop',{exact:true}).click();await expect(page.locator('#plan-id')).toContainText('carried');await page.locator('#plan-id').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/production-support-desktop.png'});await page.setViewportSize({width:700,height:1000});await page.locator('#plan-id').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/production-support-compact.png'});});
test('Avari relocation reviews and cancels safely, then preserves its paid queue across transit and reload',async({page})=>{
 await page.goto('/');
 const fixture=await page.evaluate(async()=>{
 const {createMatch,submit,resolveWeek}=await import('/src/simulation/engine.ts' as string);const {saveCheckpoint}=await import('/src/persistence/checkpoints.ts' as string);const {recipe}=await import('/src/content/catalog.ts' as string);
 let s:Match=createMatch(['elf_avari','human_gondor'],127);s.players.p2.ai=false;
 for(let y=3;y<=4;y++)for(let x=3;x<=7;x++){s.map.terrain[y*s.map.width+x]='meadow';delete s.shallowWater[`${x},${y}`];}
 const p=s.players.p1,w=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;Object.assign(w,{x:4,y:4,move:5});Object.assign(s.facilities['p1:core'],{x:4,y:3});p.stock={P:2000,M:2000,K:2000,E:2000};p.sources.push(...recipe(p.profile,'equipment').access.filter((a:string)=>!p.sources.includes(a)));p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(w),id:p.hero.id,kind:'hero',name:'Frontier Mediator'};
 const order=(action:Action)=>{const r=submit(s,{id:`p1-${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});if(!r.ok)throw Error(r.reason);s=r.state;};order({kind:'build',building:'portable-workshop',x:4,y:4});order({kind:'build',building:'depot',x:7,y:4});s=resolveWeek(s);
 const workshop=Object.values(s.facilities).find(f=>f.kind==='portable-workshop')!.id,destination=Object.values(s.facilities).find(f=>f.kind==='depot'&&f.x===7)!.id;
 order({kind:'produce',facility:workshop,recipe:'equipment'});s=resolveWeek(s);const job=s.facilities[workshop].job!;if(!job)throw Error('Expected partially completed queue');await saveCheckpoint(s);return{workshop,destination,carrier:w.id,job};});
 await page.getByRole('button',{name:'Continue saved match'}).click();await page.getByRole('button',{name:'Economy',exact:true}).click();await page.getByText('Traveling Compact',{exact:true}).click();
 for(const site of ['p1:core',fixture.destination]){if(!await page.locator('#portable-settlement').isVisible())await page.getByText('Traveling Compact',{exact:true}).click();await page.locator('#portable-settlement').selectOption(site);await page.getByRole('button',{name:'Review allow relocation',exact:true}).click();await page.getByRole('button',{name:'Confirm order',exact:true}).click();}
 if(!await page.locator('#portable-workshop').isVisible())await page.getByText('Traveling Compact',{exact:true}).click();
 await page.locator('#portable-workshop').selectOption(fixture.workshop);await page.locator('#portable-origin').selectOption('p1:core');await page.locator('#portable-destination').selectOption(fixture.destination);await page.locator('#portable-carrier').selectOption(fixture.carrier);
 await page.getByRole('button',{name:'Review Traveling Compact',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('3 readiness');await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Review Traveling Compact',exact:true})).toBeFocused();
 await page.getByRole('button',{name:'Review Traveling Compact',exact:true}).click();await page.getByRole('button',{name:'Confirm order',exact:true}).click();await page.getByRole('button',{name:'Resolve week →',exact:true}).click();await expect(page.locator('#status')).toContainText('committed and saved');
 await page.reload();await page.getByRole('button',{name:'Continue saved match'}).click();await page.getByRole('button',{name:'Economy',exact:true}).click();await page.getByText('Traveling Compact',{exact:true}).click();
 const saved=await page.evaluate(async()=>{const{loadCheckpoint}=await import('/src/persistence/checkpoints.ts' as string);return(await loadCheckpoint()).state;});expect(saved.facilities[fixture.workshop].job).toEqual(fixture.job);expect(saved.facilities[fixture.workshop].x).toBe(6);expect(Object.values(saved.portableWorkshops)[0]).toMatchObject({phase:'arrived',workshopId:fixture.workshop});
 await page.locator('#portable-workshop').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/avari-support-desktop.png'});await page.setViewportSize({width:700,height:1000});await page.locator('#portable-workshop').scrollIntoViewIfNeeded();await page.screenshot({path:'test-results/avari-support-compact.png'});
});
