import type {Match,Pos,Stock} from './types';
import {stocks} from './types';
export interface CropCycle {id:string;owner:string;plot:string;irrigation:string;stage:number;harvest:number;remainingCare:number;advanced:boolean;status:'growing'|'harvested'|'failed';started:number;lastProgress:number;seed:Stock}
export type CropState=Match & {crops:Record<string,CropCycle>};
const distance=(a:Pos,b:Pos)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
export function plantingReason(s:CropState,seat:string,plot:string,irrigation:string){const p=s.players[seat],f=s.facilities[plot],i=s.facilities[irrigation];if(!p||!f||f.owner!==seat||f.kind!=='crop-plot'||f.hp<=0||f.workers<1)return 'Existing owned staffed cultivated plot required';if(!i||i.owner!==seat||i.kind!=='irrigation'||i.hp<=0||i.workers<1||distance(f,i)>2)return 'Existing nearby staffed irrigation required';if(f.job||f.repair||f.rest||Object.values(s.crops).some(c=>c.plot===plot&&c.status==='growing'))return 'Plot has an existing crop or occupied work';if(p.stock.P<10||p.stock.M<5)return 'Planting requires 10P seed and 5M tending inputs';return '';}
/** Provisional ordinary crop: seed10P/5M, three growth stages, fixed30P harvest,
 * three paid2P tending advances. Vana never changes yield or remaining upkeep: any unpaid tending supplies
 * are settled before the earlier harvest, not waived. */
export function plantCrop(s:CropState,seat:string,plot:string,irrigation:string){const reason=plantingReason(s,seat,plot,irrigation);if(reason)throw new Error(reason);const p=s.players[seat];p.stock.P-=10;p.stock.M-=5;const id=`crop:${s.nextId++}`;s.crops[id]={id,owner:seat,plot,irrigation,stage:0,harvest:30,remainingCare:3,advanced:false,status:'growing',started:s.turn,lastProgress:s.turn-1,seed:stocks(10,5)};}
export function cropPowerReason(s:CropState,seat:string,id:string,connected?:(a:Pos,b:Pos)=>boolean){const p=s.players[seat],c=s.crops[id],f=c&&s.facilities[c.plot],i=c&&s.facilities[c.irrigation],h=p&&s.units[p.hero.id];if(!p||p.profile!=='vana'||p.hero.status!=='living'||p.hero.readiness<3||p.commitment<1)return 'Living Vana, readiness and personal commitment required';if(!c||c.owner!==seat||c.status!=='growing'||c.advanced||c.stage>=3)return 'Existing growing crop without its once-cycle advance required';if(!f||!i||f.owner!==seat||i.owner!==seat||f.hp<=0||i.hp<=0||f.workers<1||i.workers<1)return 'Intact irrigation and tending labor required';if(!h?.alive||!h.active||!connected||!connected(h,f))return 'Hero and planted plot must occupy one connected region';return '';}
export function advanceCrop(s:CropState,seat:string,id:string,connected?:(a:Pos,b:Pos)=>boolean){const reason=cropPowerReason(s,seat,id,connected);if(reason)throw new Error(reason);s.players[seat].hero.readiness-=3;const c=s.crops[id];c.stage++;c.advanced=true;}
export function progressCrops(s:CropState){for(const c of Object.values(s.crops)){if(c.status!=='growing'||c.lastProgress>=s.turn)continue;const f=s.facilities[c.plot],i=s.facilities[c.irrigation],p=s.players[c.owner];if(!f||!i||f.hp<=0||i.hp<=0||f.owner!==c.owner||i.owner!==c.owner){c.status='failed';continue;}if(f.workers<1||i.workers<1||p.stock.P<2)continue;c.lastProgress=s.turn;p.stock.P-=2;c.remainingCare--;c.stage=Math.min(3,c.stage+1);if(c.stage===3&&p.stock.P>=c.remainingCare*2){p.stock.P-=c.remainingCare*2;c.remainingCare=0;p.stock.P+=c.harvest;c.status='harvested';}}}
export function validateCrop(s:CropState,c:CropCycle){if(!['growing','harvested','failed'].includes(c.status)||![c.stage,c.harvest,c.remainingCare,c.started,c.lastProgress].every(Number.isSafeInteger)||c.started<1||c.lastProgress<0||s.crops[c.id]!==c||!s.players[c.owner]||!s.facilities[c.plot]||!s.facilities[c.irrigation]||c.harvest!==30||c.stage<0||c.stage>3||c.remainingCare<0||c.remainingCare>3||c.started>s.turn||c.lastProgress>s.turn||JSON.stringify(c.seed)!==JSON.stringify(stocks(10,5))||(c.status==='harvested'&&(c.stage!==3||c.remainingCare!==0)))throw new Error('Invalid finite crop checkpoint');}
