import type {Match,Pos,Item} from './types';
export type OrdinaryHazard='arrows'|'impact';
export interface ProtectionKit{unit:string;owner:string;hazard:OrdinaryHazard;materials:number}
export interface ArmorFitting{unit:string;owner:string;item:string;hazard:OrdinaryHazard;percent:20|25;until:number|null;burden:number}
export interface EquipmentService{id:string;owner:string;unit:string;item:string;facility:string;hazard:OrdinaryHazard;started:number;lastProgress:number;status:'working'|'lost'}
export type EquipmentServiceState=Match&{protectionKits:Record<string,ProtectionKit>;armorFittings:Record<string,ArmorFitting>;equipmentServices:Record<string,EquipmentService>};
export type ServiceRoute=(from:Pos,to:Pos)=>boolean;
const d=(a:Pos,b:Pos)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
function armor(s:EquipmentServiceState,seat:string,unit:string):Item|undefined{const u=s.units[unit];if(!u?.alive||!u.active||!u.supplied||u.owner!==seat||u.kind!=='company')return;return u.inventory.map(id=>s.items[id]).find(i=>i?.owner===seat&&i.bearer===unit&&i.bonus>0&&i.durability>0);}
function hero(s:EquipmentServiceState,seat:string,cost:number){const p=s.players[seat],h=p&&s.units[p.hero.id];return p?.profile==='dwarf_belegost'&&p.hero.status==='living'&&h?.alive&&h.active&&p.hero.readiness>=cost?h:undefined;}
export function equipmentServiceBusy(s:EquipmentServiceState,unit:string){return Object.values(s.equipmentServices).some(q=>q.unit===unit&&q.status==='working');}
export function protectionKitReason(s:EquipmentServiceState,seat:string,unit:string,facility:string,hazard:OrdinaryHazard){const u=s.units[unit],f=s.facilities[facility],p=s.players[seat];if(!['arrows','impact'].includes(hazard)||!armor(s,seat,unit)||equipmentServiceBusy(s,unit))return 'Available own armored infantry company required';if(!f||f.owner!==seat||f.kind!=='workshop'||f.hp<=0||f.workers<1||d(u,f)>1)return 'Adjacent staffed workshop required';if(s.protectionKits[unit])return 'Company already carries a protection kit';if(!p.sources.includes('metal')||p.stock.M<5)return 'Metal access and five Materials required';return '';}
/** Provisional ordinary kit recipe:5M, carried by one company; caller charges ordinary operation. */
export function makeProtectionKit(s:EquipmentServiceState,seat:string,unit:string,facility:string,hazard:OrdinaryHazard){const reason=protectionKitReason(s,seat,unit,facility,hazard);if(reason)throw new Error(reason);s.players[seat].stock.M-=5;s.protectionKits[unit]={unit,owner:seat,hazard,materials:5};}
export function fitGuardReason(s:EquipmentServiceState,seat:string,unit:string,hazard:OrdinaryHazard){const h=hero(s,seat,2),u=s.units[unit],kit=s.protectionKits[unit];if(!h||!armor(s,seat,unit)||d(h,u)>1||equipmentServiceBusy(s,unit))return 'Adjacent Armor Master and available armored infantry required';if(!kit||kit.owner!==seat||kit.hazard!==hazard||kit.materials!==5)return 'Existing carried protection kit for declared hazard required';if(s.players[seat].operations<1)return 'Company equipment action required';return '';}
export function fitGuard(s:EquipmentServiceState,seat:string,unit:string,hazard:OrdinaryHazard){const reason=fitGuardReason(s,seat,unit,hazard);if(reason)throw new Error(reason);const p=s.players[seat];p.hero.readiness-=2;p.operations--;delete s.protectionKits[unit];s.armorFittings[unit]={unit,owner:seat,item:armor(s,seat,unit)!.id,hazard,percent:25,until:s.revision+2,burden:0};}
export function temperReason(s:EquipmentServiceState,seat:string,unit:string,facility:string,hazard:OrdinaryHazard,route:ServiceRoute){const h=hero(s,seat,3),u=s.units[unit],f=s.facilities[facility],p=s.players[seat];if(!h||!armor(s,seat,unit)||equipmentServiceBusy(s,unit)||!['arrows','impact'].includes(hazard))return 'Available Armor Master and armored company required';if(!f||f.owner!==seat||f.hp<=0||f.kind!=='workshop'||f.workers<1||f.job||f.repair||f.rest||Object.values(s.equipmentServices).some(q=>q.facility===facility&&q.status==='working'))return 'Free staffed workshop queue required';if(d(u,f)>1||d(h,f)>6||!route(h,f)||!route(u,f))return 'Hero, company and workshop connected by safe local routes required';if(!p.sources.includes('metal')||p.stock.M<10||p.stock.K<5)return 'Metal access, ten Materials and five Lore supplies required';return '';}
/** Caller charges weekly commitment. One staffed week, no durability restoration.
 * Provisional burden: one movement point (caller clamps minimum1); region radius6. */
export function startTemper(s:EquipmentServiceState,seat:string,unit:string,facility:string,hazard:OrdinaryHazard,route:ServiceRoute){const reason=temperReason(s,seat,unit,facility,hazard,route);if(reason)throw new Error(reason);const p=s.players[seat];p.hero.readiness-=3;p.stock.M-=10;p.stock.K-=5;const id=`temper:${s.nextId++}`;s.equipmentServices[id]={id,owner:seat,unit,item:armor(s,seat,unit)!.id,facility,hazard,started:s.turn,lastProgress:s.turn-1,status:'working'};return id;}
export function progressEquipmentServices(s:EquipmentServiceState,route:ServiceRoute){for(const q of Object.values(s.equipmentServices)){if(q.status!=='working'||q.lastProgress>=s.turn)continue;const u=s.units[q.unit],f=s.facilities[q.facility],i=s.items[q.item],p=s.players[q.owner],h=s.units[p.hero.id];if(!u?.alive||u.owner!==q.owner||!f||f.hp<=0||f.owner!==q.owner||!i||i.owner!==q.owner){q.status='lost';continue;}if(!u.active||!u.supplied||f.workers<1||d(u,f)>1||!h?.alive||!h.active||d(h,f)>6||!route(h,f)||!route(u,f)||!p.sources.includes('metal')||i.bearer!==u.id||i.durability<=0)continue;q.lastProgress=s.turn;s.armorFittings[u.id]={unit:u.id,owner:q.owner,item:i.id,hazard:q.hazard,percent:20,until:null,burden:1};delete s.equipmentServices[q.id];}for(const[id,k]of Object.entries(s.protectionKits))if(!s.units[id]?.alive||s.units[id].owner!==k.owner)delete s.protectionKits[id];}
function activeFitting(s:EquipmentServiceState,unit:string){const q=s.armorFittings[unit],u=s.units[unit],i=q&&s.items[q.item];return q&&u?.alive&&u.owner===q.owner&&i?.owner===q.owner&&i.bearer===unit&&i.durability>0&&(q.until===null||q.until>s.revision)?q:undefined;}
/** Caller distinguishes ordinary arrows/impact; spells/fire/other hazards bypass. Flanking is explicit. */
export function fittingReduction(s:EquipmentServiceState,unit:string,hazard:OrdinaryHazard,flanked:boolean){const q=activeFitting(s,unit);return q?.hazard===hazard&&!flanked?q.percent:0;}
export function fittingMovementPenalty(s:EquipmentServiceState,unit:string){return activeFitting(s,unit)?.burden??0;}
export function validateEquipmentServices(s:EquipmentServiceState,guestSeat?:string){for(const[id,k]of Object.entries(s.protectionKits))if(id!==k.unit||!s.players[k.owner]||!s.units[id]||k.materials!==5||(guestSeat&&k.owner!==guestSeat))throw new Error('Invalid finite protection kit');for(const[id,q]of Object.entries(s.armorFittings))if(id!==q.unit||!s.players[q.owner]||(!guestSeat&&(!s.units[id]||!s.items[q.item]))||(guestSeat&&q.owner!==guestSeat)||(q.percent===25&&(q.until===null||q.burden!==0||q.until>s.revision+2))||(q.percent===20&&(q.until!==null||q.burden!==1)))throw new Error('Invalid armor fitting');for(const[id,q]of Object.entries(s.equipmentServices))if(id!==q.id||s.players[q.owner]?.profile!=='dwarf_belegost'||(guestSeat&&q.owner!==guestSeat)||(!guestSeat&&(!s.units[q.unit]||!s.items[q.item]||!s.facilities[q.facility]))||q.started>s.turn||q.lastProgress>s.turn)throw new Error('Invalid paid armor service');}
