import {activeEffects} from "./effects";
import {stocks,type Match,type Pos,type Stock,type Unit} from './types';
import {buildings,limits} from '../content/catalog';
import {factionProduction} from '../content/production';
import {effectiveRelation} from './diplomacy';
export type FieldworkKind='cover'|'barricade'|'gate'|'siege-brace';
export type StructuralMaterial='timber'|'stone'|'metal';
export interface FieldworkRequest extends Pos{worker:string;facility:string;kind:FieldworkKind;material:StructuralMaterial}
export interface FieldworkJob extends FieldworkRequest{id:string;owner:string;remaining:number;started:number;lastProgress:number;cost:Stock;status:'working'|'lost';lifting?:{unit?:string;method?:'worker'|'hero';turn?:number}}
export interface Fieldwork{ id:string;owner:string;kind:FieldworkKind;material:StructuralMaterial }
export interface FieldRepairKit{unit:string;owner:string;material:StructuralMaterial;stock:Stock}
export interface FaultMark{id:string;owner:string;target:string;until:number}
export type FieldworkState=Match&{fieldworkJobs:Record<string,FieldworkJob>;fieldworks:Record<string,Fieldwork>;repairKits:Record<string,FieldRepairKit>;faultMarks:Record<string,FaultMark>};
export type FieldworkRoute=(from:Pos,to:Pos,worker:Unit)=>boolean;
const distance=(a:Pos,b:Pos)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
export const fieldworkKinds:FieldworkKind[]=['cover','barricade','gate','siege-brace'];
/** Ordinary construction: existing authored costs retained; gate10P30M and one
 * staffed weekly advance are provisional. Durability40/60/100/50 is provisional. */
export const fieldworkCost=(kind:FieldworkKind):Stock=>({...buildings[kind]?.cost??stocks(10,30)});
export const fieldworkDurability=(kind:FieldworkKind)=>({cover:40,barricade:60,gate:100,'siege-brace':50})[kind];
export const isFieldEngineer=(u:Unit)=>u.kind==='company'&&Boolean(u.engineer);
export const fieldworkWorkerBusy=(s:FieldworkState,id:string)=>Object.values(s.fieldworkJobs).some(q=>q.worker===id&&q.status==='working');
export const fieldworkPlotReservations=(s:FieldworkState,seat:string)=>Object.values(s.fieldworkJobs).filter(q=>q.owner===seat&&q.status==='working').length;
export function fieldworkReason(s:FieldworkState,seat:string,a:FieldworkRequest,route:FieldworkRoute){const p=s.players[seat],u=s.units[a.worker],f=s.facilities[a.facility];if(!p||!fieldworkKinds.includes(a.kind)||!['timber','stone','metal'].includes(a.material)||!Number.isSafeInteger(a.x)||!Number.isSafeInteger(a.y)||a.x<0||a.y<0||a.x>=s.map.width||a.y>=s.map.height||['water','cliff'].includes(s.map.terrain[a.y*s.map.width+a.x]))return 'Existing dry accessible fieldwork site required';if(!u?.alive||!u.active||!u.supplied||u.owner!==seat||u.kind!=='worker'||distance(u,a)>1||fieldworkWorkerBusy(s,u.id))return 'Free supplied worker adjacent to construction required';if(!f||f.owner!==seat||f.hp<=0||f.workers<1||distance(f,a)>3||f.job||f.repair||f.rest||Object.values(s.fieldworkJobs).some(q=>q.facility===f.id&&q.status==='working'))return 'Nearby staffed unoccupied supply worksite required';if(!route(u,a,u)||!route(f,a,u))return 'Open worker and material route required';if(Object.values(s.facilities).some(f=>f.hp>0&&distance(f,a)===0)||Object.values(s.fieldworkJobs).some(q=>q.status==='working'&&distance(q,a)===0))return 'Construction site already occupied';if(!p.sources.includes(a.material))return 'Matching structural material source access required';const cost=fieldworkCost(a.kind);if((Object.keys(cost)as(keyof Stock)[]).some(k=>p.stock[k]<cost[k]))return 'Full fieldwork recipe stocks required';if(Object.values(s.facilities).filter(f=>f.owner===seat&&f.hp>0&&!['core','hold'].includes(f.kind)).length+fieldworkPlotReservations(s,seat)>=limits(p.profile).plots)return 'Faction support plot limit reached';return '';}
export function startFieldwork(s:FieldworkState,seat:string,a:FieldworkRequest,route:FieldworkRoute){const reason=fieldworkReason(s,seat,a,route);if(reason)throw new Error(reason);const cost=fieldworkCost(a.kind);for(const k of Object.keys(cost)as(keyof Stock)[])s.players[seat].stock[k]-=cost[k];const id=`fieldwork:${s.nextId++}`;s.fieldworkJobs[id]={...structuredClone(a),id,owner:seat,remaining:1,started:s.turn,lastProgress:s.turn-1,cost,status:'working',...(a.material==='stone'&&['gate','siege-brace'].includes(a.kind)?{lifting:{}}:{})};return id;}
export function progressFieldworks(s:FieldworkState,route:FieldworkRoute){for(const q of Object.values(s.fieldworkJobs)){if(q.lifting?.method==='hero'&&q.lifting.turn!==s.turn)q.lifting={};if(q.status!=='working'||q.lastProgress>=s.turn)continue;const u=s.units[q.worker],f=s.facilities[q.facility];if(!u?.alive||u.owner!==q.owner||!f||f.owner!==q.owner||f.hp<=0){q.status='lost';continue;}if(Object.values(s.facilities).some(f=>f.hp>0&&distance(f,q)===0)||['water','cliff'].includes(s.map.terrain[q.y*s.map.width+q.x]))continue;if(!u.active||!u.supplied||distance(u,q)>1||f.workers<1||!route(u,q,u)||!route(f,q,u)||!s.players[q.owner].sources.includes(q.material))continue;if(q.lifting){const lift=s.units[q.lifting.unit??''];if(!lift?.alive||!lift.active||!lift.supplied||activeEffects(s,lift).some(e=>['stunned','incapacitated','rout'].includes(e.kind))||lift.owner!==q.owner||distance(lift,q)>1||lift.id===q.worker||(q.lifting.method==='hero'?(s.players[q.owner].profile!=='tulkas'||lift.id!==s.players[q.owner].hero.id||q.lifting.turn!==s.turn):lift.kind!=='worker'))continue;}q.lastProgress=s.turn;if(--q.remaining>0)continue;const hp=fieldworkDurability(q.kind);s.facilities[q.id]={id:q.id,owner:q.owner,name:`${q.material} ${q.kind}`,kind:q.kind,tier:1,x:q.x,y:q.y,hp,maxHp:hp,workers:0};s.fieldworks[q.id]={id:q.id,owner:q.owner,kind:q.kind,material:q.material};delete s.fieldworkJobs[q.id];}for(const[id,k]of Object.entries(s.repairKits))if(!s.units[id]?.alive||s.units[id].owner!==k.owner)delete s.repairKits[id];}
export function repairKitReason(s:FieldworkState,seat:string,unit:string,facility:string,material:StructuralMaterial){const p=s.players[seat],u=s.units[unit],f=s.facilities[facility];if(!p||!u?.alive||!u.active||!u.supplied||u.owner!==seat||!isFieldEngineer(u))return 'Own supplied engineer company required';if(!f||f.owner!==seat||f.hp<=0||f.workers<1||f.kind!=='workshop'||distance(f,u)>1)return 'Staffed workshop beside engineers required';if(s.repairKits[unit])return 'Engineer already carries a finite repair kit';if(!['timber','stone','metal'].includes(material)||!p.sources.includes(material)||p.stock.M<5)return 'Five Materials and compatible material source required';return '';}
/** Carried kit stock is drawn from M, not a fifth stock or a durability proxy. */
export function loadRepairKit(s:FieldworkState,seat:string,unit:string,facility:string,material:StructuralMaterial){const reason=repairKitReason(s,seat,unit,facility,material);if(reason)throw new Error(reason);s.players[seat].stock.M-=5;s.repairKits[unit]={unit,owner:seat,material,stock:stocks(0,5)};}
function heroReady(s:FieldworkState,seat:string,profile:string){const p=s.players[seat],h=p&&s.units[p.hero.id];return Boolean(p?.profile===profile&&p.hero.status==='living'&&h?.alive&&h.active&&p.hero.readiness>=2);}
export function braceBreachReason(s:FieldworkState,seat:string,unit:string,target:string){const p=s.players[seat],u=s.units[unit],f=s.facilities[target],meta=s.fieldworks[target],kit=s.repairKits[unit];if(!heroReady(s,seat,'human_gondor'))return 'Living Gondor hero and two readiness required';if(!f||!meta||f.owner!==seat||!['gate','barricade'].includes(f.kind)||f.hp<=0||f.hp>=f.maxHp)return 'Existing damaged owned gate or barricade required';if(!u?.alive||!u.active||!u.supplied||u.owner!==seat||!isFieldEngineer(u)||distance(u,f)>1||distance(s.units[p.hero.id],f)>1||p.operations<1)return 'Adjacent hero and engineer company with ordinary action required';if(!kit||kit.owner!==seat||kit.material!==meta.material||kit.stock.M!==5)return 'Carried compatible five Materials repair kit required';return '';}
/** Parent charges the tactical hero action; this consumes the engineers' normal operation. */
export function braceBreach(s:FieldworkState,seat:string,unit:string,target:string){const reason=braceBreachReason(s,seat,unit,target);if(reason)throw new Error(reason);s.players[seat].hero.readiness-=2;s.players[seat].operations--;delete s.repairKits[unit];const f=s.facilities[target];f.hp=Math.min(f.maxHp,f.hp+Math.floor(f.maxHp*.15));}
export function faultReason(s:FieldworkState,seat:string,target:string,observed:(p:Pos)=>boolean){const p=s.players[seat],f=s.facilities[target],meta=s.fieldworks[target];if(!heroReady(s,seat,'dwarf_khazad_dum'))return 'Living Deep Surveyor and two readiness required';if(!f||!meta||meta.material!=='stone'||f.hp<=0||f.hp>=f.maxHp||distance(s.units[p.hero.id],f)>3||!observed(f))return 'Observed damaged stone obstacle within short survey range required';return '';}
/** Damaged stone denotes an unstable surface; three-tile survey range is provisional. */
export function markFault(s:FieldworkState,seat:string,target:string,observed:(p:Pos)=>boolean){const reason=faultReason(s,seat,target,observed);if(reason)throw new Error(reason);s.players[seat].hero.readiness-=2;const id=`fault:${s.nextId++}`;s.faultMarks[id]={id,owner:seat,target,until:s.revision+1};}
const fieldTool=(s:FieldworkState,u:Unit)=>u.inventory.map(id=>s.items[id]).find(i=>i?.name==='Field breach tools'&&i.owner===u.owner&&i.bearer===u.id&&i.durability>0);
export function fieldworkBreachBonus(s:FieldworkState,u:Unit,target:string){if(!isFieldEngineer(u)||!(fieldTool(s,u)||u.inventory.some(id=>s.items[id]?.name===factionProduction('dwarf_nogrod').equipment.name&&s.items[id].bearer===u.id&&s.items[id].durability>0)))return 0;return Object.values(s.faultMarks).some(m=>m.target===target&&m.until>s.revision&&effectiveRelation(s,u.owner,m.owner)==='alliance')?25:0;}
/** Generic field tool wear is provisional four durability; existing Nogrod tools
 * remain handled by equipment.ts so their adopted passive is not charged twice. */
export function wearFieldTools(s:FieldworkState,u:Unit){const item=fieldTool(s,u);if(item)item.durability=Math.max(0,item.durability-4);}
export function validateFieldworkState(s:FieldworkState,guestSeat?:string){
 const occupied=new Set<string>();for(const q of Object.values(s.fieldworkJobs))if(q.status==='working')for(const id of [q.worker,q.lifting?.unit].filter((v):v is string=>Boolean(v))){if(occupied.has(id))throw new Error('Duplicate construction role');occupied.add(id);}
 const bounded=(p:Pos)=>p.x>=0&&p.y>=0&&p.x<s.map.width&&p.y<s.map.height;
 for(const[id,q]of Object.entries(s.fieldworkJobs)){const cost=fieldworkCost(q.kind);const tagged=q.material==='stone'&&['gate','siege-brace'].includes(q.kind);if(Boolean(q.lifting)!==tagged)throw new Error('Invalid construction lifting tag');if(q.lifting?.unit){const u=s.units[q.lifting.unit];if(!u||u.owner!==q.owner||u.id===q.worker||(q.lifting.method==='hero'?(s.players[q.owner]?.profile!=='tulkas'||u.id!==s.players[q.owner].hero.id||q.lifting.turn===undefined||q.lifting.turn>s.turn):q.lifting.method!=='worker'||u.kind!=='worker'))throw new Error('Invalid assigned lifting role');}else if(q.lifting?.method||q.lifting?.turn!==undefined)throw new Error('Missing lifting actor');if(id!==q.id||!s.players[q.owner]||(guestSeat&&q.owner!==guestSeat)||(!guestSeat&&(!s.units[q.worker]||!s.facilities[q.facility]))||!bounded(q)||q.started>s.turn||q.lastProgress>s.turn||(Object.keys(cost)as(keyof Stock)[]).some(k=>q.cost[k]!==cost[k]))throw new Error('Invalid paid fieldwork queue');}
 for(const[id,q]of Object.entries(s.fieldworks)){const f=s.facilities[id];if(id!==q.id||!s.players[q.owner]||!f||f.kind!==q.kind||f.maxHp!==fieldworkDurability(q.kind))throw new Error('Invalid finite fieldwork');}
 for(const[id,k]of Object.entries(s.repairKits)){const u=s.units[id];if(id!==k.unit||!s.players[k.owner]||(guestSeat&&k.owner!==guestSeat)||!u||!isFieldEngineer(u)||k.stock.M!==5||k.stock.P||k.stock.K||k.stock.E)throw new Error('Invalid carried repair Materials');}
 for(const[id,m]of Object.entries(s.faultMarks))if(id!==m.id||s.players[m.owner]?.profile!=='dwarf_khazad_dum'||m.until>s.revision+1||(guestSeat&&m.owner!==guestSeat)||(!guestSeat&&!s.fieldworks[m.target]))throw new Error('Invalid surveyed fault');
 for(const u of Object.values(s.units))if(u.engineer&&u.kind!=='company')throw new Error('Only engineer companies retain specialist role');
}
/** Provisional geometry: barricades block passage; gates admit their own and
 * mutually allied formations. Flying units bypass ground structures. */
export function fieldworkBlocks(s:FieldworkState,pos:Pos,u?:Unit){return Object.values(s.fieldworks).some(q=>{const f=s.facilities[q.id];return f?.hp>0&&distance(f,pos)===0&&(q.kind==='barricade'||q.kind==='gate'&&(!u||effectiveRelation(s,u.owner,f.owner)!=='alliance'));});}
/** Provisional cover: 25% against a ranged approach passing its one-tile frontage;
 * flanking and adjacent melee bypass it. No extra attack or invulnerability. */
export function fieldworkCoverReduction(s:FieldworkState,attacker:Unit,target:Pos&{owner:string}){if(distance(attacker,target)<=1)return 0;const dx=attacker.x-target.x,dy=attacker.y-target.y;return Object.values(s.fieldworks).some(q=>{const f=s.facilities[q.id];if(!f||f.hp<=0||q.kind!=='cover'||distance(f,target)>1||effectiveRelation(s,target.owner,f.owner)!=='alliance')return false;const fx=f.x-target.x,fy=f.y-target.y;return fx*dx+fy*dy>0&&Math.abs(fx*dy-fy*dx)<=Math.max(Math.abs(dx),Math.abs(dy));})?25:0;}
