import type {Match,Pos,Unit} from './types';
import {activeEffects,sightline} from './effects';
export interface NightRegion extends Pos{id:string;owner:string;radius:number;period:'night'|'dawn'|'day'}
export interface DarkShift{id:string;owner:string;job:string;site:string;week:number;light:'dark'|'lamps'|'dawn';mirror?:string;worked:boolean}
export interface DawnWatch{id:string;owner:string;post:string;approach:Pos[];week:number}
export interface DawnReport extends Pos{id:string;owner:string;post:string;turn:number;revision:number;direction:'north'|'south'|'east'|'west'}
export type NightWorkState=Match&{nightRegions:Record<string,NightRegion>;darkShifts:Record<string,DarkShift>;dawnWatches:Record<string,DawnWatch>;dawnReports:Record<string,DawnReport>};
const dist=(a:Pos,b:Pos)=>Math.hypot(a.x-b.x,a.y-b.y);
export function conscious(s:Match,u:Unit|undefined):u is Unit{return !!u&&u.alive&&u.active&&u.hp>0&&!activeEffects(s,u).some(e=>['stunned','incapacitated','silenced','rout'].includes(e.kind));}
export const lightAt=(s:NightWorkState,p:Pos)=>Object.values(s.nightRegions).filter(r=>dist(r,p)<=r.radius).sort((a,b)=>a.id.localeCompare(b.id))[0]?.period??'day';
/** Authored local lighting, never wall time. Radius6 and night/dawn/day cycle are provisional. */
export function initializeNight(s:NightWorkState){for(const p of Object.values(s.players)){const f=s.facilities[`${p.seat}:core`];if(f)s.nightRegions[`night:${p.seat}`]={id:`night:${p.seat}`,owner:p.seat,x:f.x,y:f.y,radius:6,period:'night'};}}
export function advanceNightRegions(s:NightWorkState){for(const r of Object.values(s.nightRegions))r.period=r.period==='night'?'dawn':r.period==='dawn'?'day':'night';}
export function darkShiftReason(s:NightWorkState,seat:string,job:string){const j=s.infrastructureWork[job],site=j&&s.infrastructureSites[j.site];if(!j||j.owner!==seat||j.phase!=='work'||!site||j.remaining<1)return 'Existing funded infrastructure work stage required';if(lightAt(s,site)!=='night')return 'Explicit authored night worksite required';if(Object.values(s.darkShifts).some(q=>q.job===job&&q.week===s.turn))return 'One assignment per worksite shift';return '';}
export function assignDarkShift(s:NightWorkState,seat:string,job:string){const reason=darkShiftReason(s,seat,job);if(reason)throw new Error(reason);const id=`dark-shift:${s.nextId++}`;s.darkShifts[id]={id,owner:seat,job,site:s.infrastructureWork[job].site,week:s.turn,light:'dark',worked:false};return id;}
export function illuminationReason(s:NightWorkState,seat:string,id:string,method:'lamps'|'dawn',mirror:string|undefined,connected:(a:Pos,b:Pos)=>boolean){const p=s.players[seat],q=s.darkShifts[id],j=q&&s.infrastructureWork[q.job],site=q&&s.infrastructureSites[q.site],crew=j&&s.units[j.worker],f=j&&s.facilities[j.facility];if(!p||!q||q.owner!==seat||q.week!==s.turn||q.worked||q.light!=='dark'||!j||j.phase!=='work'||!site||!conscious(s,crew)||!crew.supplied||crew.owner!==seat||!f||f.owner!==seat||f.hp<=0||f.workers<1)return 'Existing dark staffed funded shift required';if(method==='lamps')return p.stock.M<5?'Ordinary maintained lamps require5M':'';const h=s.units[p.hero.id],m=mirror&&s.facilities[mirror];if(p.profile!=='arien'||p.hero.status!=='living'||!conscious(s,h)||p.hero.readiness<3||p.commitment<1)return 'Living Arien,3readiness and weekly commitment required';if(!m||m.kind!=='mirror-station'||m.owner!==seat||m.hp<=0||m.workers<1||!sightline(s,m,site)||dist(m,site)>6||!connected(h,f))return 'Maintained staffed mirror station with clear worksite sightline in connected region required';return p.stock.M<10||p.stock.K<5?'Dawn Worksite requires10M5K':'';}
export function illuminateShift(s:NightWorkState,seat:string,id:string,method:'lamps'|'dawn',mirror:string|undefined,connected:(a:Pos,b:Pos)=>boolean){const reason=illuminationReason(s,seat,id,method,mirror,connected);if(reason)throw new Error(reason);const p=s.players[seat],q=s.darkShifts[id];p.stock.M-=method==='lamps'?5:10;if(method==='dawn'){p.stock.K-=5;p.hero.readiness-=3;q.mirror=mirror;}q.light=method;}
/** Called by normal queue progression; no shift record means ordinary behavior unchanged. */
export function shiftCanWork(s:NightWorkState,job:string){const q=Object.values(s.darkShifts).find(q=>q.job===job&&q.week===s.turn);if(!q)return true;if(q.worked||q.light==='dark')return false;if(q.light==='lamps')return true;const m=q.mirror&&s.facilities[q.mirror],site=s.infrastructureSites[q.site],p=s.players[q.owner],h=p&&s.units[p.hero.id];return !!m&&m.owner===q.owner&&m.hp>0&&m.workers>0&&!!site&&sightline(s,m,site)&&p.hero.status==='living'&&conscious(s,h);}
export function markShiftWorked(s:NightWorkState,job:string){const q=Object.values(s.darkShifts).find(q=>q.job===job&&q.week===s.turn);if(q)q.worked=true;}
export function dawnWatchReason(s:NightWorkState,seat:string,post:string,approach:Pos[]){const p=s.players[seat],f=s.facilities[post],h=p&&s.units[p.hero.id];if(!p||p.profile!=='arien'||p.hero.status!=='living'||!conscious(s,h)||!f||f.owner!==seat||f.kind!=='dawn-watch'||f.hp<=0||f.workers<1||lightAt(s,f)!=='dawn')return 'Occupied dawn watchpost and living Arien required';if(approach.length<2||approach.length>4||approach.some((at,i)=>at.x<0||at.y<0||at.x>=s.map.width||at.y>=s.map.height||dist(at,f)>3||!sightline(s,f,at)||(i>0&&Math.abs(at.x-approach[i-1].x)+Math.abs(at.y-approach[i-1].y)!==1)))return 'Short physically visible lit approach required';return '';}
export function selectDawnWatch(s:NightWorkState,seat:string,post:string,approach:Pos[]){const reason=dawnWatchReason(s,seat,post,approach);if(reason)throw new Error(reason);for(const[id,w]of Object.entries(s.dawnWatches))if(w.owner===seat)delete s.dawnWatches[id];const id=`dawn-watch:${s.nextId++}`;s.dawnWatches[id]={id,owner:seat,post,approach:structuredClone(approach),week:s.turn};return id;}
export function recordDawnMovement(s:NightWorkState,u:Unit,route:Pos[]){if(!u.alive||route.length<2||activeEffects(s,u).some(e=>['concealed','roofed','tunnel'].includes(e.kind)))return;for(const w of Object.values(s.dawnWatches)){if(w.week!==s.turn||dawnWatchReason(s,w.owner,w.post,w.approach))continue;const f=s.facilities[w.post];for(let i=1;i<route.length;i++){const at=route[i],from=route[i-1];if(!w.approach.some(p=>dist(p,at)===0)||!sightline(s,f,at)||['woodland','cliff'].includes(s.map.terrain[at.y*s.map.width+at.x]))continue;const direction=at.x>from.x?'east':at.x<from.x?'west':at.y>from.y?'south':'north';const id=`dawn-report:${s.nextId++}`;s.dawnReports[id]={id,owner:w.owner,post:w.post,x:at.x,y:at.y,turn:s.turn,revision:s.revision,direction};break;}}}
export function validateNightWork(s:NightWorkState,guestSeat?:string){for(const [id,r]of Object.entries(s.nightRegions))if(id!==r.id||!s.players[r.owner]||r.radius!==6||!['night','dawn','day'].includes(r.period))throw new Error('Invalid authored lighting');for(const[id,q]of Object.entries(s.darkShifts))if(id!==q.id||!s.players[q.owner]||q.week>s.turn||(s.infrastructureWork[q.job]&&(s.infrastructureWork[q.job].owner!==q.owner||s.infrastructureWork[q.job].site!==q.site))||(guestSeat&&q.owner!==guestSeat)||(!guestSeat&&!s.infrastructureSites[q.site])||(q.light==='dawn'&&s.players[q.owner].profile!=='arien'))throw new Error('Invalid funded dark shift');for(const records of [s.dawnWatches,s.dawnReports])for(const[id,q]of Object.entries(records))if(id!==q.id||s.players[q.owner]?.profile!=='arien'||(guestSeat&&q.owner!==guestSeat)||('week'in q?q.week>s.turn:q.turn>s.turn||q.revision>s.revision))throw new Error('Invalid dawn observation');}
