import {terrainObserved} from "./visibility";
import { recipe } from '../content/catalog';
import { activeEffects } from './effects';
import type { Facility, Match, Pos, Unit } from './types';
export interface ProductionPlan extends Pos { id:string; owner:string; recipe:'equipment'; archive:string; carrier:string|null; created:number; workshop?:string; committedTurn?:number }
export type PlanAction = {kind:'preserve-plan';archive:string;recipe:string}|{kind:'remember-workshop';plan:string;facility:string}|{kind:'recover-plan';plan:string;unit:string}|{kind:'destroy-plan';plan:string;unit:string};
type Connected=(a:Pos,b:Pos)=>boolean;
const distance=(a:Pos,b:Pos)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const able=(s:Match,u:Unit|undefined)=>!!u?.alive&&u.active&&u.supplied&&!activeEffects(s,u).some(e=>['stunned','incapacitated','rout'].includes(e.kind));
function hero(s:Match,seat:string){const p=s.players[seat],h=p&&s.units[p.hero.id];return p?.profile==='vaire'&&p.hero.status==='living'&&able(s,h)?h:undefined;}
export function preserveReason(s:Match,seat:string,archive:string,key:string){const p=s.players[seat],h=hero(s,seat),f=s.facilities[archive];if(!h)return 'Living active Vairë required';if(key!=='equipment'||!p.research.includes('plan-equipment'))return 'Previously unlocked own ordinary equipment plan required; hero and foreign recipes excluded';if(Object.values(s.productionPlans).some(q=>q.owner===seat))return 'Only one recoverable production plan may exist';if(!f||f.owner!==seat||f.kind!=='archive'||f.hp<=0||f.workers<1||distance(h,f)>1)return 'Personally accessible staffed owned specialist archive required';return '';}
export function preservePlan(s:Match,seat:string,archive:string,key:string){const reason=preserveReason(s,seat,archive,key);if(reason)throw new Error(reason);const h=hero(s,seat)!,id=`plan:${s.nextId++}`;const q:ProductionPlan={id,owner:seat,recipe:'equipment',archive,carrier:h.id,x:h.x,y:h.y,created:s.turn};s.productionPlans[id]=q;return q;}
export function rememberReason(s:Match,seat:string,id:string,site:string,connected:Connected){const p=s.players[seat],h=hero(s,seat),q=s.productionPlans[id],f=s.facilities[site];if(!h||p.hero.readiness<3)return 'Living active Vairë and three readiness required';if(!q||q.owner!==seat||q.carrier!==h.id)return 'Own preserved plan carried by Vairë required';const archive=s.facilities[q.archive];if(!archive||archive.owner!==seat||archive.kind!=='archive'||archive.hp>0)return 'Actual lost owned specialist archive required';if(q.committedTurn===s.turn)return 'This plan already has its weekly commitment';if(!f||f.owner!==seat||f.kind!=='workshop'||f.hp<=0||f.workers<1||f.repair||f.rest||!connected(h,f))return 'Connected staffed basic workshop required';if(f.job&&f.job.recipe!==q.recipe)return 'Only the preserved ordinary item may use this workshop';const r=recipe(p.profile,q.recipe)!;if(r.access.some(k=>!p.sources.includes(k)))return 'All normal item recipe source inputs required';return '';}
export function rememberWorkshop(s:Match,seat:string,id:string,site:string,connected:Connected){const reason=rememberReason(s,seat,id,site,connected);if(reason)throw new Error(reason);const q=s.productionPlans[id];s.players[seat].hero.readiness-=3;q.workshop=site;q.committedTurn=s.turn;}
/** Native production remains ordinary: full price, queue, staff and duration. The
 * preserved plan only restores access for the current paid hero commitment. */
export function planAllowsProduction(s:Match,f:Facility,connected:Connected):boolean {const p=s.players[f.owner];if(p.profile!=='vaire')return true;if(!p.research.includes('plan-equipment'))return false;const r=recipe(p.profile,'equipment')!;if(r.access.some(k=>!p.sources.includes(k)))return false;if(Object.values(s.facilities).some(a=>a.owner===f.owner&&a.kind==='archive'&&a.hp>0&&a.workers>0))return true;const h=hero(s,f.owner);return !!h&&Object.values(s.productionPlans).some(q=>q.owner===f.owner&&q.recipe==='equipment'&&q.carrier===h.id&&q.workshop===f.id&&q.committedTurn===s.turn&&s.facilities[q.archive]?.hp===0&&connected(h,f));}
export function dropPlans(s:Match,carrier:string){const u=s.units[carrier];if(!u)return;for(const q of Object.values(s.productionPlans))if(q.carrier===carrier){q.carrier=null;q.x=u.x;q.y=u.y;delete q.workshop;delete q.committedTurn;}}
export function planRecoveryReason(s:Match,seat:string,id:string,unit:string,destroy=false){const q=s.productionPlans[id],u=s.units[unit];if(!q||q.carrier!==null||!able(s,u)||u.owner!==seat||distance(u,q)>1)return 'Accessible dropped plan and supplied own party required';if(!destroy&&(q.owner!==seat||unit!==s.players[seat].hero.id||!hero(s,seat)))return 'Only the owning Vairë may recover her plan';return '';}
export function recoverPlan(s:Match,seat:string,id:string,unit:string){const reason=planRecoveryReason(s,seat,id,unit);if(reason)throw new Error(reason);s.productionPlans[id].carrier=unit;}
export function refreshPlans(s:Match){for(const q of Object.values(s.productionPlans)){if(!q.carrier)continue;const u=s.units[q.carrier];if(!u?.alive||u.owner!==q.owner||s.players[q.owner].hero.status!=='living'){dropPlans(s,q.carrier);continue;}q.x=u.x;q.y=u.y;}}
export function validatePlans(s:Match,guestSeat?:string){const owners=new Set<string>();for(const[id,q]of Object.entries(s.productionPlans)){const p=s.players[q.owner],a=s.facilities[q.archive];if(guestSeat&&q.owner!==guestSeat){if(id!==q.id||p?.profile!=='vaire'||owners.has(q.owner)||q.carrier!==null||q.archive!=='undisclosed'||q.workshop!==undefined||q.committedTurn!==undefined||q.recipe!=='equipment'||q.created<1||q.created>s.turn||!terrainObserved(s,guestSeat,q))throw new Error('Invalid observed dropped production plan');owners.add(q.owner);continue;}if(id!==q.id||p?.profile!=='vaire'||(guestSeat&&q.owner!==guestSeat)||owners.has(q.owner)||q.recipe!=='equipment'||!p.research.includes('plan-equipment')||q.created<1||q.created>s.turn||q.x>=s.map.width||q.y>=s.map.height||!a||a.kind!=='archive'||(q.carrier&&(q.carrier!==p.hero.id||!s.units[q.carrier]?.alive||s.units[q.carrier].owner!==q.owner))||((q.workshop===undefined)!==(q.committedTurn===undefined))||(q.committedTurn!==undefined&&(q.committedTurn<q.created||q.committedTurn>s.turn||q.committedTurn===s.turn&&p.commitment!==0))||(q.workshop&&(!s.facilities[q.workshop]||s.facilities[q.workshop].kind!=='workshop')))throw new Error('Invalid singular owned production plan');owners.add(q.owner);}}
