import type {Match,Pos,Unit,Stock} from './types';import {stocks} from './types';import {activeEffects} from './effects';
export interface MountLot{species?:'wolf'|'horse';id:string;owner:string;count:number;fatigue:number;stable:string|null;unit:string|null}
export interface MountJob{id:string;owner:string;kind:'breed'|'recover'|'exchange';facility:string;phase:'working'|'outbound'|'returning'|'lost';remaining:number;started:number;lastProgress:number;cost:Stock;lot?:string;crew?:string;rider?:string;tired?:string;route:Pos[];index:number}
export type MountState=Match&{mountLots:Record<string,MountLot>;mountJobs:Record<string,MountJob>};
export interface MountChecks{open:(s:Match,u:Unit,route:Pos[])=>boolean;budget:(s:Match,u:Unit)=>number;connected?:(a:Pos,b:Pos,u:Unit)=>boolean;cost?:(s:Match,u:Unit,route:Pos[])=>number;moved?:(s:Match,u:Unit,route:Pos[])=>void}
const d=(a:Pos,b:Pos)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);const able=(s:Match,u:Unit|undefined)=>!!u?.alive&&u.active&&u.supplied&&!activeEffects(s,u).some(e=>['stunned','incapacitated','rout','root'].includes(e.kind));
const stable=(s:MountState,seat:string,id:string)=>{const f=s.facilities[id];return f?.owner===seat&&f.hp>0&&f.workers>0&&(f.kind==='stable'||f.kind==='training'&&s.players[seat].profile==='human_rohan')?f:undefined;};
export const mountUnitBusy=(s:MountState,id:string)=>Object.values(s.mountJobs).some(j=>j.phase!=='lost'&&(j.crew===id||j.rider===id));
export const mountFacilityBusy=(s:MountState,id:string)=>Object.values(s.mountJobs).some(j=>j.phase!=='lost'&&j.facility===id);
/** Scenario/company recipe represents twelve existing mounts per rider company;
 * invoke only on initial or paid company creation, never each week. */
export function createCompanyMounts(s:MountState,u:Unit){if(s.players[u.owner]?.profile!=='human_rohan'||u.kind!=='company'||u.engineer||Object.values(s.mountLots).some(q=>q.unit===u.id))return;const id=`mounts:${s.nextId++}`;s.mountLots[id]={id,owner:u.owner,count:12,fatigue:0,stable:null,unit:u.id};}
export function initializeMounts(s:MountState){for(const u of Object.values(s.units))createCompanyMounts(s,u);}
export function travelMounts(s:MountState,u:Unit,from:Pos,to:Pos){if(d(from,to)===0)return;const q=Object.values(s.mountLots).find(q=>q.unit===u.id&&q.owner===u.owner);if(q)q.fatigue=Math.min(6,q.fatigue+1);}
export function mountPenalty(s:MountState,u:Unit){const q=Object.values(s.mountLots).find(q=>q.unit===u.id&&q.owner===u.owner);return q?Math.floor(q.fatigue/3):0;}
export function attachedMountFatigue(s:MountState,u:Unit):number{return Object.values(s.mountLots).find(q=>q.unit===u.id&&q.owner===u.owner)?.fatigue??0;}
/** Provisional ordinary fodder/rest recovery accompanies the existing paid
 * staffed refuge week. It preserves the attached animals, species and count;
 * it grants neither Rohan's immediate remount exchange nor new mounts. */
export function restAttachedMounts(s:MountState,u:Unit):void{if(!u.alive||!u.active||!u.supplied||u.kind!=='company')return;const q=Object.values(s.mountLots).find(q=>q.unit===u.id&&q.owner===u.owner);if(q)q.fatigue=Math.max(0,q.fatigue-2);}
export function queueMountsReason(s:MountState,seat:string,facility:string){const f=stable(s,seat,facility),p=s.players[seat];if(!f||p.profile!=='human_rohan'||f.job||f.repair||f.rest||mountFacilityBusy(s,facility))return 'Free staffed Rohan stable queue required';return p.stock.P<30||p.stock.M<10?'Thirty Provisions and ten Materials required':'';}
/** Provisional breeding/training batch:12 mounts,30P10M,three staffed weeks. */
export function queueMounts(s:MountState,seat:string,facility:string){const reason=queueMountsReason(s,seat,facility);if(reason)throw new Error(reason);s.players[seat].stock.P-=30;s.players[seat].stock.M-=10;const id=`mount-job:${s.nextId++}`;s.mountJobs[id]={id,owner:seat,kind:'breed',facility,phase:'working',remaining:3,started:s.turn,lastProgress:s.turn-1,cost:stocks(30,10),route:[],index:0};return id;}
export function remountReason(s:MountState,seat:string,rider:string,lot:string,crew:string,route:Pos[],c:MountChecks){const p=s.players[seat],h=p&&s.units[p.hero.id],u=s.units[rider],worker=s.units[crew],rested=s.mountLots[lot],tired=Object.values(s.mountLots).find(q=>q.unit===rider&&q.owner===seat),f=rested?.stable&&stable(s,seat,rested.stable);if(!p||p.profile!=='human_rohan'||p.hero.status!=='living'||!able(s,h)||p.hero.readiness<3)return 'Active Rohan hero and three readiness required';if(!able(s,u)||u.owner!==seat||!tired||tired.fatigue===0||!rested||rested.owner!==seat||rested.unit||rested.fatigue!==0||rested.count!==tired.count||!f||mountFacilityBusy(s,f.id))return 'Equal existing rested stable mounts and tired own rider mounts required';if(!able(s,worker)||worker.owner!==seat||worker.kind!=='worker'||mountUnitBusy(s,crew)||mountUnitBusy(s,rider)||d(worker,f)!==0||d(h,f)>6||(c.connected&&!c.connected(h,f,h)))return 'Free supplied handler at connected stable beside hero required';if(route.length<2||route.length>32||d(route[0],f)!==0||d(route.at(-1)!,u)!==0||route.some((p,i)=>p.x<0||p.y<0||p.x>=s.map.width||p.y>=s.map.height||(i>0&&d(p,route[i-1])!==1))||!c.open(s,worker,route)||(c.cost?.(s,worker,route)??route.length-1)>c.budget(s,worker))return 'Actual open transfer route within normal weekly handler movement required';return p.stock.P<5?'Five Provisions for handlers and fodder required':'';}
export function startRemount(s:MountState,seat:string,rider:string,lot:string,crew:string,route:Pos[],c:MountChecks){const reason=remountReason(s,seat,rider,lot,crew,route,c);if(reason)throw new Error(reason);const q=s.mountLots[lot],tired=Object.values(s.mountLots).find(q=>q.unit===rider)!,id=`remount:${s.nextId++}`;s.players[seat].stock.P-=5;s.players[seat].hero.readiness-=3;s.mountJobs[id]={id,owner:seat,kind:'exchange',facility:q.stable!,phase:'outbound',remaining:1,started:s.turn,lastProgress:s.turn-1,cost:stocks(5),lot,rider,crew,tired:tired.id,route:structuredClone(route),index:0};q.stable=null;return id;}
export function recoverMountsReason(s:MountState,seat:string,lot:string){const q=s.mountLots[lot],f=q?.stable&&stable(s,seat,q.stable);if(!q||q.owner!==seat||q.unit||q.fatigue<1||!f||mountFacilityBusy(s,f.id)||f.job||f.repair||f.rest)return 'Tired existing mounts at free staffed stable required';return s.players[seat].stock.P<5?'Five Provisions normal fodder required':'';}
/** Paid ordinary recovery changes mount fatigue only, never rider wounds/fatigue. */
export function recoverMounts(s:MountState,seat:string,lot:string){const reason=recoverMountsReason(s,seat,lot);if(reason)throw new Error(reason);s.players[seat].stock.P-=5;const id=`mount-rest:${s.nextId++}`;s.mountJobs[id]={id,owner:seat,kind:'recover',facility:s.mountLots[lot].stable!,phase:'working',remaining:1,started:s.turn,lastProgress:s.turn-1,cost:stocks(5),lot,route:[],index:0};return id;}
export function progressMounts(s:MountState,c:MountChecks){for(const j of Object.values(s.mountJobs)){if(j.phase==='lost'||j.lastProgress>=s.turn)continue;const f=stable(s,j.owner,j.facility);if(!f){if(!s.facilities[j.facility]||s.facilities[j.facility].owner!==j.owner||s.facilities[j.facility].hp<=0)j.phase='lost';continue;}if(j.kind==='exchange'){const u=s.units[j.crew!],rider=s.units[j.rider!],rested=s.mountLots[j.lot!],tired=s.mountLots[j.tired!];if(!u?.alive||u.owner!==j.owner||!rider?.alive||rider.owner!==j.owner||!rested||!tired){j.phase='lost';continue;}const remaining=j.route.slice(j.index);if(!able(s,u)||d(u,remaining[0])!==0||!c.open(s,u,remaining))continue;let steps=Math.min(Math.floor(c.budget(s,u)),remaining.length-1);while(steps>0&&(c.cost?.(s,u,remaining.slice(0,steps+1))??steps)>c.budget(s,u))steps--;if(steps<1&&remaining.length>1)continue;const route=remaining.slice(0,steps+1);j.index+=steps;Object.assign(u,j.route[j.index]);if(steps>0)c.moved?.(s,u,route);j.lastProgress=s.turn;if(j.index!==j.route.length-1)continue;if(j.phase==='outbound'){if(d(u,rider)!==0||tired.unit!==rider.id)continue;tired.unit=null;rested.unit=rider.id;j.phase='returning';j.route=[...j.route].reverse();j.index=0;}else{tired.stable=f.id;delete s.mountJobs[j.id];}continue;}j.lastProgress=s.turn;if(--j.remaining>0)continue;if(j.kind==='breed'){const id=`mounts:${s.nextId++}`;s.mountLots[id]={id,owner:j.owner,count:12,fatigue:0,stable:f.id,unit:null};}else if(j.lot&&s.mountLots[j.lot])s.mountLots[j.lot].fatigue=Math.max(0,s.mountLots[j.lot].fatigue-2);delete s.mountJobs[j.id];}}
export function validateMounts(s:MountState,guestSeat?:string){const riders=new Set<string>();for(const[id,q]of Object.entries(s.mountLots)){if(id!==q.id||!s.players[q.owner]||(guestSeat&&q.owner!==guestSeat)||q.count!==12||!Number.isSafeInteger(q.fatigue)||q.fatigue<0||q.fatigue>6||(q.unit&&q.stable))throw new Error('Invalid finite mount lot');if(q.unit){if((!guestSeat&&!s.units[q.unit])||riders.has(q.unit))throw new Error('Duplicated rider mounts');riders.add(q.unit);}if(q.stable&&!guestSeat&&!s.facilities[q.stable])throw new Error('Missing mount stable');}const crews=new Set<string>(),lots=new Set<string>();for(const[id,j]of Object.entries(s.mountJobs)){const cost=j.kind==='breed'?stocks(30,10):stocks(5);if(id!==j.id||s.players[j.owner]?.profile!=='human_rohan'||(guestSeat&&j.owner!==guestSeat)||(!guestSeat&&!s.facilities[j.facility])||j.started>s.turn||j.lastProgress>s.turn||(['P','M','K','E']as const).some(k=>j.cost[k]!==cost[k]))throw new Error('Invalid funded mount job');if(j.kind!=='exchange')continue;if(!j.crew||!j.rider||!j.lot||!j.tired||j.lot===j.tired||!s.mountLots[j.lot]||!s.mountLots[j.tired]||s.mountLots[j.lot].count!==s.mountLots[j.tired].count||j.route.length<2||j.route.length>32||j.index>=j.route.length||j.route.some((p,i)=>p.x<0||p.y<0||p.x>=s.map.width||p.y>=s.map.height||(i>0&&d(p,j.route[i-1])!==1)))throw new Error('Invalid physical remount exchange');if(j.phase==='lost')continue;if((!guestSeat&&!s.units[j.crew])||(s.units[j.crew]&&d(s.units[j.crew],j.route[j.index])!==0)||crews.has(j.crew)||lots.has(j.lot)||lots.has(j.tired))throw new Error('Duplicate remount handler or horses');crews.add(j.crew);lots.add(j.lot);lots.add(j.tired);}}
export type MountAction={kind:'mounts';mode:'breed';facility:string}|{kind:'mounts';mode:'recover';lot:string}|{kind:'mounts';mode:'exchange';rider:string;lot:string;crew:string;route:Pos[]};
