import {diplomacyUpkeepCost,consumeDiplomacyUpkeep} from "../content/final-production";
import type {Match,Unit} from './types';
import {activeEffects} from './effects';
export function reserveReason(s:Match,seat:string,unit:string,facility:string,amount:number){const p=s.players[seat],u=s.units[unit],f=s.facilities[facility],h=p&&s.units[p.hero.id];if(!p||p.profile!=='sauron'||p.hero.status!=='living'||!h?.alive||!h.active)return 'Living Sauron required';if(!u?.alive||!u.active||!u.supplied||u.owner!==seat||u.kind!=='company'||activeEffects(s,u).some(e=>['stunned','incapacitated','rout'].includes(e.kind)))return 'Own active supplied ordinary company required';if(!f||f.owner!==seat||f.kind!=='depot'||f.hp<=0||f.workers<1||Math.abs(f.x-u.x)+Math.abs(f.y-u.y)>1)return 'Company beside an owned staffed depot required';if(!Number.isSafeInteger(amount)||amount<1||amount+(u.reserveProvisions??0)>5)return 'One through five paid reserve Provisions maximum';if(Object.values(s.units).some(v=>v.owner===seat&&v.id!==unit&&(v.reserveProvisions??0)>0))return 'Only one selected company may hold reserve Provisions';return p.stock.P<amount?'Existing depot Provisions required':'';}
export function packRations(s:Match,seat:string,unit:string,facility:string,amount:number){const reason=reserveReason(s,seat,unit,facility,amount);if(reason)throw new Error(reason);s.players[seat].stock.P-=amount;s.units[unit].reserveProvisions=(s.units[unit].reserveProvisions??0)+amount;}
/** Pay all upkeep atomically: reserved P can replace only the same company's P.
 * Other stocks, supply capacity, creatures and movement never receive a bonus. */
export function payReservedUpkeep(s:Match,u:Unit):boolean {const p=s.players[u.owner],provisions=diplomacyUpkeepCost(s,u,u.upkeep.P),paid=Math.min(u.reserveProvisions??0,provisions),cost={...u.upkeep,P:provisions-paid};if((['P','M','K','E']as const).some(k=>p.stock[k]<cost[k]))return false;consumeDiplomacyUpkeep(s,u,u.upkeep.P);for(const k of ['P','M','K','E']as const)p.stock[k]-=cost[k];if(u.reserveProvisions!==undefined){u.reserveProvisions-=paid;if(u.reserveProvisions===0)delete u.reserveProvisions;}return true;}
export function validateRations(s:Match){const owners=new Set<string>();for(const u of Object.values(s.units)){if(u.reserveProvisions===undefined)continue;if(!u.alive||u.kind!=='company'||s.players[u.owner]?.profile!=='sauron'||!Number.isSafeInteger(u.reserveProvisions)||u.reserveProvisions<1||u.reserveProvisions>5||owners.has(u.owner))throw new Error('Invalid single company paid reserve');owners.add(u.owner);}}
