import type {Match,Pos,Unit} from './types';
import {factionProduction} from '../content/production';
import {effectiveRelation} from './diplomacy';
import {activeEffects} from './effects';
export interface ShorePreparation{id:string;owner:string;kind:'surge'|'landing';hero:string;unit:string;tile:Pos;until:number;ship?:string;committed?:boolean}
export interface CurrentCrossing{id:string;owner:string;hero:string;convoy:string;carrier:string;tiles:Pos[];turn:number;consumed?:boolean}
export type ShoreState=Match&{shorePreparations:Record<string,ShorePreparation>;currentCrossings:Record<string,CurrentCrossing>;shallowWater:Record<string,true>};
const d=(a:Pos,b:Pos)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const water=(s:Match,p:Pos)=>s.map.terrain[p.y*s.map.width+p.x]==='water';
function ready(s:ShoreState,seat:string,profile:string,cost:number){const p=s.players[seat],h=p&&s.units[p.hero.id];return p?.profile===profile&&p.hero.status==='living'&&h?.alive&&h.active&&p.hero.readiness>=cost?h:undefined;}
export function surgeReason(s:ShoreState,seat:string,unit:string,tile:Pos,observed:(p:Pos)=>boolean){const h=ready(s,seat,'ulmo',2),u=s.units[unit];if(!h||!u?.alive||u.kind==='hero'||!u.active||effectiveRelation(s,seat,u.owner)!=='war')return 'Ulmo and observed hostile ordinary formation required';if(!s.shallowWater[`${tile.x},${tile.y}`]||!water(s,tile)||d(h,tile)>4||d(u,tile)!==0||!observed(tile))return 'Formation must occupy an authored visible shallow ford within local range';if(activeEffects(s,u).some(e=>['brace','braced'].includes(e.kind)))return 'Braced formation resists disrupted footing';return '';}
/** Provisional footing consequence:one movement point while on marked shallow tile;
 * minimum movement remains1. No HP, free movement or invented water is created. */
export function surgePassage(s:ShoreState,seat:string,unit:string,tile:Pos,observed:(p:Pos)=>boolean){const reason=surgeReason(s,seat,unit,tile,observed);if(reason)throw new Error(reason);const id=`surge:${s.nextId++}`;s.players[seat].hero.readiness-=2;s.shorePreparations[id]={id,owner:seat,hero:s.players[seat].hero.id,kind:'surge',unit,tile:{...tile},until:s.revision+2};}
export function surgeFootingPenalty(s:ShoreState,u:Unit){if(activeEffects(s,u).some(e=>e.kind==='shore-footing'&&e.source===`shallow:${u.x},${u.y}`))return 1;if(activeEffects(s,u).some(e=>['brace','braced'].includes(e.kind)))return 0;return Object.values(s.shorePreparations).some(q=>q.kind==='surge'&&q.unit===u.id&&q.until>s.revision&&d(u,q.tile)===0&&s.units[q.hero]?.alive&&s.units[q.hero].active)?1:0;}
export function currentReason(s:ShoreState,seat:string,convoy:string,tiles:Pos[],surveyed:(p:Pos)=>boolean,contested:(p:Pos)=>boolean){const h=ready(s,seat,'ulmo',3),c=s.convoys[convoy],u=c&&s.units[c.carrier];if(!h||!c||c.owner!==seat||c.phase!=='travel'||!u?.alive||!u.active||!u.supplied||c.supplies.P<1||(Object.values(c.cargo).reduce((a,b)=>a+b,0)<=0||Object.values(c.cargo).reduce((a,b)=>a+b,0)>c.capacity))return 'Ulmo and existing normally loaded supplied traveling convoy required';if(Object.values(s.currentCrossings).some(q=>q.convoy===convoy&&q.turn===s.turn))return 'Convoy already has one current passage this week';if(tiles.length<3||tiles.length>6||tiles.length-1>u.move||water(s,tiles[0])||water(s,tiles.at(-1)!)||d(c,tiles[0])!==0||d(h,tiles[0])>6)return 'Local convoy must physically occupy surveyed near bank of one narrow water span';if(tiles.some((p,i)=>p.x<0||p.y<0||p.x>=s.map.width||p.y>=s.map.height||!surveyed(p)||contested(p)||(i>0&&d(p,tiles[i-1])!==1)||(i>0&&i<tiles.length-1&&!water(s,p))))return 'Surveyed open banks and connected water obstacle required';if(d(tiles[0],tiles.at(-1)!)!==tiles.length-1||(tiles[0].x!==tiles.at(-1)!.x&&tiles[0].y!==tiles.at(-1)!.y))return 'One straight bank-to-bank crossing required';return '';}
/** Authorization only. Transport advances the carrier with normal movement,
 * capacity, crew supplies and route checks. Provisional span3..6tiles/radius6. */
export function authorizeCurrentCrossing(s:ShoreState,seat:string,convoy:string,tiles:Pos[],surveyed:(p:Pos)=>boolean,contested:(p:Pos)=>boolean){const reason=currentReason(s,seat,convoy,tiles,surveyed,contested);if(reason)throw new Error(reason);const id=`current:${s.nextId++}`;s.players[seat].hero.readiness-=3;s.currentCrossings[id]={id,owner:seat,hero:s.players[seat].hero.id,convoy,carrier:s.convoys[convoy].carrier,tiles:structuredClone(tiles),turn:s.turn};}
export function currentAllows(s:ShoreState,u:Unit,tile:Pos){return Object.values(s.currentCrossings).some(q=>!q.consumed&&q.carrier===u.id&&q.owner===u.owner&&q.turn===s.turn&&s.convoys[q.convoy]?.phase==='travel'&&s.units[q.hero]?.alive&&s.units[q.hero].active&&q.tiles.some(p=>d(p,tile)===0));}
export function landingReason(s:ShoreState,seat:string,ship:string,unit:string,tile:Pos,contested:(p:Pos)=>boolean){const h=ready(s,seat,'human_numenor',2),v=s.vessels[ship],u=s.units[unit];if(!h||!v||v.owner!==seat||v.hp<=0||v.passenger!==unit||!u?.alive||u.owner!==seat||u.kind!=='company'||!factionProduction(s.players[seat].profile).unit.traits.includes('marine'))return 'Númenor hero and existing own marine passenger aboard a living transport required';if(d(h,v)>1&&d(h,tile)>1)return 'Hero must accompany transport or landing force';if(tile.x<0||tile.y<0||tile.x>=s.map.width||tile.y>=s.map.height||water(s,tile)||s.map.terrain[tile.y*s.map.width+tile.x]==='cliff'||d(v,tile)!==1||contested(tile))return 'Adjacent viable uncontested landing required';return '';}
export function prepareLanding(s:ShoreState,seat:string,ship:string,unit:string,tile:Pos,contested:(p:Pos)=>boolean){const reason=landingReason(s,seat,ship,unit,tile,contested);if(reason)throw new Error(reason);const id=`landing:${s.nextId++}`;s.players[seat].hero.readiness-=2;s.shorePreparations[id]={id,owner:seat,hero:s.players[seat].hero.id,ship,unit,tile:{...tile},kind:'landing',until:s.revision+1};}
/** Call at actual disembark completion only; normal operation/time unchanged.
 * Provisional ordinary unloading cohesion loss1 uses existing morale cleanup. */
export function completeLanding(s:ShoreState,ship:string,u:Unit,tile:Pos){const q=Object.values(s.shorePreparations).find(q=>q.kind==='landing'&&q.ship===ship&&q.unit===u.id&&d(q.tile,tile)===0&&q.committed&&s.units[q.hero]?.alive&&s.units[q.hero].active);if(q){delete s.shorePreparations[q.id];return;}if(u.kind!=='company')return;const e=activeEffects(s,u).find(e=>e.kind==='cohesion-loss');if(e)e.value++;else u.effects.push({kind:'cohesion-loss',value:1,until:1000000,source:`morale:${s.turn}`});}

/** Bind valid one-phase preparation to the actual accepted normal unloading job. */
export function bindLanding(s:ShoreState,ship:string,unit:string,tile:Pos){const q=Object.values(s.shorePreparations).find(q=>q.kind==='landing'&&q.ship===ship&&q.unit===unit&&q.until>s.revision&&d(q.tile,tile)===0);if(q)q.committed=true;}
export function consumeCurrentAtBank(s:ShoreState,u:Unit,travelled:Pos[]=[u]){for(const q of Object.values(s.currentCrossings))if(q.carrier===u.id&&travelled.some(p=>d(p,q.tiles.at(-1)!)===0))q.consumed=true;}
export function interruptShorePower(s:ShoreState,hero:string){for(const[id,q]of Object.entries(s.shorePreparations))if(q.hero===hero)delete s.shorePreparations[id];}
export function validateShoreState(s:ShoreState,guestSeat?:string){const bounded=(p:Pos)=>Number.isSafeInteger(p.x)&&Number.isSafeInteger(p.y)&&p.x>=0&&p.y>=0&&p.x<s.map.width&&p.y<s.map.height;for(const key of Object.keys(s.shallowWater)){const[x,y]=key.split(',').map(Number);if(key!==`${x},${y}`||!bounded({x,y})||!water(s,{x,y}))throw new Error('Invalid authored shallow-water metadata');}for(const[id,q]of Object.entries(s.shorePreparations)){if(id!==q.id||!s.players[q.owner]||!bounded(q.tile)||q.until>s.revision+2||(!guestSeat&&(!s.units[q.unit]||!s.units[q.hero]))||(guestSeat&&q.owner!==guestSeat))throw new Error('Invalid shore preparation');}for(const[id,q]of Object.entries(s.currentCrossings)){if(id!==q.id||s.players[q.owner]?.profile!=='ulmo'||q.turn>s.turn||q.tiles.length<3||q.tiles.length>6||q.tiles.some((p,i)=>!bounded(p)||(i>0&&d(p,q.tiles[i-1])!==1)||(i>0&&i<q.tiles.length-1&&!water(s,p)))||(!guestSeat&&(!s.units[q.carrier]||!s.units[q.hero]))||(guestSeat&&q.owner!==guestSeat))throw new Error('Invalid current passage');}}
