import {limits} from "../content/catalog";
import type {Match,Pos,Unit,Stock} from './types';import {stocks} from './types';import {activeEffects} from './effects';
export interface WatchGear{id:string;owner:string;facility:string;active:boolean}
export interface WatchJob{id:string;owner:string;facility:string;kind:'make'|'move';phase:'working'|'lost';remaining:number;started:number;lastProgress:number;cost:Stock;worker?:string;gear?:string;staff:number;route:Pos[];index:number}
export interface BorderSurvey{id:string;owner:string;turn:number;revision:number;points:Pos[]}
export interface BorderReport{id:string;owner:string;turn:number;revision:number;points:Pos[];text:string}
export type WatchState=Match&{watchGear:Record<string,WatchGear>;watchJobs:Record<string,WatchJob>;borderReports:Record<string,BorderReport>;borderSurveys:Record<string,BorderSurvey>};
export interface WatchChecks{open:(s:Match,u:Unit,route:Pos[])=>boolean;surveyed:(p:Pos)=>boolean;budget:(s:Match,u:Unit)=>number;connected?:(a:Pos,b:Pos,u:Unit)=>boolean;cost?:(s:Match,u:Unit,route:Pos[])=>number;moved?:(s:Match,u:Unit,route:Pos[])=>void}
const d=(a:Pos,b:Pos)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);const wood=(s:Match,p:Pos)=>s.map.terrain[p.y*s.map.width+p.x]==='woodland';const able=(s:Match,u:Unit|undefined)=>!!u?.alive&&u.active&&u.supplied&&!activeEffects(s,u).some(e=>['stunned','incapacitated','rout','root'].includes(e.kind));
export const watchUnitBusy=(s:WatchState,id:string)=>Object.values(s.watchJobs).some(j=>j.worker===id&&j.phase==='working');
export const watchFacilityBusy=(s:WatchState,id:string)=>Object.values(s.watchJobs).some(j=>j.facility===id&&j.phase==='working');
export function watchActive(s:WatchState,facility:string){const f=s.facilities[facility];return !!f&&f.kind==='watch-post'&&f.hp>0&&f.workers>0&&wood(s,f)&&Object.values(s.watchGear).some(q=>q.facility===facility&&q.owner===f.owner&&q.active);}
export function watchConcealed(s:WatchState,pos:Pos){return Object.values(s.watchGear).some(q=>watchActive(s,q.facility)&&d(s.facilities[q.facility],pos)===0);}
export function watchGearReason(s:WatchState,seat:string,facility:string){const p=s.players[seat],f=s.facilities[facility];if(!p||!f||f.owner!==seat||f.kind!=='watch-post'||f.hp<=0||f.workers<1||!wood(s,f)||f.job||f.repair||f.rest||watchFacilityBusy(s,facility)||Object.values(s.watchGear).some(q=>q.facility===facility))return 'Unfitted staffed woodland watch-post and free queue required';return p.stock.M<10||p.stock.K<5?'Ten Materials and five Lore supplies required':'';}
/** Provisional ordinary gear recipe10M5K and one staffed week. One post gear
 * enables existing observation radius8 and woodland concealment, no extra agent. */
export function queueWatchGear(s:WatchState,seat:string,facility:string){const reason=watchGearReason(s,seat,facility);if(reason)throw new Error(reason);s.players[seat].stock.M-=10;s.players[seat].stock.K-=5;const id=`watch-gear-job:${s.nextId++}`;s.watchJobs[id]={id,owner:seat,facility,kind:'make',phase:'working',remaining:1,started:s.turn,lastProgress:s.turn-1,cost:stocks(0,10,5),staff:0,route:[],index:0};return id;}
export function reweaveReason(s:WatchState,seat:string,facility:string,worker:string,route:Pos[],c:WatchChecks){const p=s.players[seat],h=p&&s.units[p.hero.id],f=s.facilities[facility],u=s.units[worker];if(!p||p.profile!=='elf_sindar'||p.hero.status!=='living'||!able(s,h)||p.hero.readiness<3)return 'Active March Warden and three readiness required';if(!f||f.owner!==seat||!watchActive(s,facility)||watchFacilityBusy(s,facility)||f.job||f.repair||f.rest)return 'Existing active unoccupied woodland watch equipment required';if(!able(s,u)||u.owner!==seat||u.kind!=='worker'||d(u,f)!==0||d(h,f)>6||(c.connected&&!c.connected(h,f,h))||watchUnitBusy(s,worker))return 'Free worker at post and physically nearby hero required';if(route.length<2||route.length>7||d(route[0],f)!==0||(c.cost?.(s,u,route)??route.length-1)>c.budget(s,u)||route.some((p,i)=>p.x<0||p.y<0||p.x>=s.map.width||p.y>=s.map.height||!wood(s,p)||!c.surveyed(p)||(i>0&&d(p,route[i-1])!==1))||!c.open(s,u,route))return 'Surveyed open woodland route within one normal weekly worker journey required';const end=route.at(-1)!;if(Object.values(s.facilities).filter(v=>v.owner===seat&&v.hp>0&&!['core','hold'].includes(v.kind)).length+Object.values(s.watchJobs).filter(q=>q.owner===seat&&q.kind==='move'&&q.phase==='working').length+Object.values(s.fieldworkJobs).filter(q=>q.owner===seat&&q.status==='working').length>=limits(p.profile).plots)return 'New light watch site exceeds faction support capacity';if(Object.values(s.facilities).some(v=>v.hp>0&&d(v,end)===0)||Object.values(s.fieldworkJobs).some(q=>q.status==='working'&&d(q,end)===0))return 'Destination is occupied';return p.stock.M<5||p.stock.P<2?'Five Materials and two Provisions normal worker rations required':'';}
/** All existing staff and the same gear move; original post is inactive in
 * transit. Old foundation remains a stripped shell; a new light30HP post receives existing gear and staff only on delivery. */
export function startReweave(s:WatchState,seat:string,facility:string,worker:string,route:Pos[],c:WatchChecks){const reason=reweaveReason(s,seat,facility,worker,route,c);if(reason)throw new Error(reason);const f=s.facilities[facility],gear=Object.values(s.watchGear).find(q=>q.facility===facility)!,id=`reweave:${s.nextId++}`;s.players[seat].hero.readiness-=3;s.players[seat].stock.M-=5;s.players[seat].stock.P-=2;s.watchJobs[id]={id,owner:seat,facility,kind:'move',phase:'working',remaining:1,started:s.turn,lastProgress:s.turn-1,cost:stocks(2,5),worker,gear:gear.id,staff:f.workers,route:structuredClone(route),index:0};f.workers=0;gear.active=false;return id;}
export function progressWatchGear(s:WatchState,c:WatchChecks){for(const j of Object.values(s.watchJobs)){if(j.phase!=='working'||j.lastProgress>=s.turn)continue;const f=s.facilities[j.facility];if(!f||f.hp<=0||f.owner!==j.owner){j.phase='lost';continue;}if(j.kind==='make'){if(f.workers<1||!wood(s,f))continue;j.lastProgress=s.turn;const id=`watch-gear:${s.nextId++}`;s.watchGear[id]={id,owner:j.owner,facility:f.id,active:true};delete s.watchJobs[j.id];continue;}const u=s.units[j.worker!],gear=s.watchGear[j.gear!];if(!u?.alive||u.owner!==j.owner||!gear){j.phase='lost';continue;}const remaining=j.route.slice(j.index),end=j.route.at(-1)!;if(!able(s,u)||d(u,remaining[0])!==0||!remaining.every(p=>wood(s,p))||!c.open(s,u,remaining)||Object.values(s.facilities).some(v=>v.id!==f.id&&v.hp>0&&d(v,end)===0))continue;let steps=Math.min(remaining.length-1,Math.floor(c.budget(s,u)));while(steps>0&&(c.cost?.(s,u,remaining.slice(0,steps+1))??steps)>c.budget(s,u))steps--;if(steps<1)continue;const travelled=remaining.slice(0,steps+1);j.index+=steps;Object.assign(u,j.route[j.index]);c.moved?.(s,u,travelled);j.lastProgress=s.turn;if(j.index===j.route.length-1){const id=`watch-post:${s.nextId++}`;s.facilities[id]={id,owner:j.owner,name:'Light woodland watch-post',kind:'watch-post',tier:1,...end,hp:30,maxHp:30,workers:j.staff};gear.facility=id;gear.active=true;delete s.watchJobs[j.id];}}}
/** Invoke BEFORE appending the hero's new survey trace. Existing own survey plus
 * a fresh non-own trace makes a dated disturbance, never identity/count. */
export function borderMemory(s:WatchState,u:Unit,route:Pos[]){
 if(s.players[u.owner]?.profile!=='elf_sindar'||s.players[u.owner].hero.id!==u.id||!able(s,u)||route.length<2)return;
 const previous=Object.values(s.borderSurveys).filter(q=>q.owner===u.owner&&q.points.some(p=>route.some(at=>d(p,at)===0))).sort((a,b)=>b.turn-a.turn||b.revision-a.revision)[0];
 if(previous&&!Object.values(s.borderReports).some(r=>r.owner===u.owner&&r.turn===s.turn)){
  const points=route.filter(at=>previous.points.some(p=>d(p,at)===0)&&Object.values(s.movementTraces).some(t=>t.owner!==u.owner&&!t.erased&&t.turn>=s.turn-1&&(t.turn>previous.turn||t.turn===previous.turn&&t.revision>previous.revision)&&t.route.some(p=>d(p,at)===0)));
  if(points.length){const id=`border:${s.nextId++}`;s.borderReports[id]={id,owner:u.owner,turn:s.turn,revision:s.revision,points:structuredClone(points),text:'Fresh crossing disturbance since this hero personally visited. Identity, numbers and current position unknown.'};}
 }
 const id=`border-survey:${s.nextId++}`;s.borderSurveys[id]={id,owner:u.owner,turn:s.turn,revision:s.revision,points:structuredClone(route)};
 for(const records of [s.borderReports,s.borderSurveys]){const ids=Object.keys(records);while(ids.length>128)delete records[ids.shift()!];}
}
export function validateWatches(s:WatchState,guestSeat?:string){const posts=new Set<string>();for(const[id,g]of Object.entries(s.watchGear)){if(id!==g.id||!s.players[g.owner]||(!guestSeat&&!s.facilities[g.facility])||(guestSeat&&g.owner!==guestSeat)||posts.has(g.facility))throw new Error('Duplicated watch equipment');posts.add(g.facility);}const workers=new Set<string>(),gears=new Set<string>();for(const[id,j]of Object.entries(s.watchJobs)){const cost=j.kind==='make'?stocks(0,10,5):stocks(2,5);if(id!==j.id||!s.players[j.owner]||(guestSeat&&j.owner!==guestSeat)||(!guestSeat&&!s.facilities[j.facility])||j.started>s.turn||j.lastProgress>s.turn||(['P','M','K','E']as const).some(k=>j.cost[k]!==cost[k]))throw new Error('Invalid paid watch project');if(j.kind!=='move')continue;if(s.players[j.owner].profile!=='elf_sindar'||!j.gear||!s.watchGear[j.gear]||!j.worker||(!guestSeat&&!s.units[j.worker])||j.staff<1||j.route.length<2||j.route.length>7||j.index>=j.route.length||j.route.some((p,i)=>p.x<0||p.y<0||p.x>=s.map.width||p.y>=s.map.height||(i>0&&d(p,j.route[i-1])!==1)))throw new Error('Invalid physical watch relocation');if(j.phase==='lost')continue;if(s.watchGear[j.gear].active||workers.has(j.worker)||gears.has(j.gear)||(s.units[j.worker]&&d(s.units[j.worker],j.route[j.index])!==0))throw new Error('Duplicate watch staff or active equipment');workers.add(j.worker);gears.add(j.gear);}for(const[id,r]of Object.entries({...s.borderReports,...s.borderSurveys}))if(id!==r.id||s.players[r.owner]?.profile!=='elf_sindar'||r.turn>s.turn||r.revision>s.revision||(guestSeat&&r.owner!==guestSeat)||r.points.some(p=>p.x<0||p.y<0||p.x>=s.map.width||p.y>=s.map.height))throw new Error('Invalid anonymous border report');}
export type WatchAction={kind:'watch-gear';mode:'make';facility:string}|{kind:'watch-gear';mode:'relocate';facility:string;worker:string;route:Pos[]};
