import {expect,it} from 'vitest';
import {createMatch,submit,preview,resolveWeek} from '../src/simulation/engine';
import {companionProduction,type CompanionKey} from '../src/content/companion-production';
import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';
import {recordObservedAttack} from '../src/simulation/intelligence';
import {relayReason} from '../src/simulation/relay-messages';
import {civilianReason} from '../src/simulation/civilians';
import {stocks} from '../src/simulation/types';
function produced(profile:string,key:CompanionKey){let s=createMatch([profile,'human_gondor'],19);const p=s.players.p1,core=s.facilities['p1:core'],q=companionProduction(profile,key)!;p.stock=stocks(999,999,999,999);p.sources=[...new Set([...p.sources,...q.recipe.access])];s.facilities.work={...core,id:'work',kind:q.recipe.facility,workers:1};const result=submit(s,{id:'companion:1',seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action:{kind:'produce',facility:'work',recipe:key}});expect(result.ok,result.reason).toBe(true);const reserved=preview(result.state,'p1');expect(reserved.facilities.work.job?.cost).toEqual(q.recipe.cost);for(const k of ['P','M','K','E']as const)expect(reserved.players.p1.stock[k]).toBe(p.stock[k]-q.recipe.cost[k]);s=result.state;for(let i=0;i<q.recipe.turns;i++)s=resolveWeek(s);return{s,q};}
it('all nine companions complete conserved paid production and checkpoint',()=>{for(const[profile,key]of [['manwe','courier-eagle'],['yavanna','root-guardian'],['nienna','memory-lantern'],['orome','hunting-hounds'],['tulkas','pack-aurochs'],['nessa','courier-stag'],['vana','songbird-swarm'],['este','rescue-hind'],['istari_grove','moth-clouds']]as const){const{s,q}=produced(profile,key);const output=q.stats?Object.values(s.units).find(u=>u.companion===key):Object.values(s.items).find(i=>i.companion===key);expect(output).toBeDefined();expect(output).toMatchObject(q.stats??q.item!);expect(decodeCheckpoint(encodeCheckpoint(s)).state.turn).toBe(s.turn);}});
it('paid courier species can carry existing dated reports through ordinary physical stations',()=>{for(const[profile,key]of [['manwe','courier-eagle'],['nessa','courier-stag']]as const){const{s}=produced(profile,key),u=Object.values(s.units).find(u=>u.companion===key)!,f=s.facilities['p1:core'];Object.assign(f,{x:4,y:4,kind:'safehouse'});Object.assign(u,{x:4,y:4});s.facilities.primary={...f,id:'primary',x:5};s.facilities.dest={...f,id:'dest',x:6};const enemy=Object.values(s.units).find(u=>u.owner==='p2'&&u.kind==='company')!;Object.assign(enemy,{x:4,y:3});recordObservedAttack(s,enemy);const report=Object.values(s.intelligenceReports).find(r=>r.owner==='p1'&&r.observations.some(o=>o.source===f.id))!;expect(report).toBeDefined();expect(relayReason(s,'p1',{courier:u.id,report:report.id,origin:f.id,primary:'primary',destination:'dest',route:[{x:4,y:4},{x:5,y:4},{x:6,y:4}]},()=>true)).toBe('');}});
it('paid rescue hind performs ordinary finite store handling without creating provisions',()=>{const{s}=produced('este','rescue-hind'),u=Object.values(s.units).find(u=>u.companion==='rescue-hind')!,f=s.facilities['p1:core'];Object.assign(u,{x:f.x,y:f.y});s.households.home={id:'home',owner:'p1',home:f.id,population:6,provisions:10,willing:true,x:f.x,y:f.y};expect(civilianReason(s,'p1',{mode:'withdraw',household:'home',unit:u.id,amount:5},{route:()=>true,busy:()=>false,connected:()=>true,cost:()=>1})).toBe('');});
it('rejects forged finite companion supply upkeep and capacity',()=>{const{s}=produced('manwe','courier-eagle'),u=Object.values(s.units).find(u=>u.companion==='courier-eagle')!;for(const patch of [{supply:0},{upkeep:stocks(0)},{maxHp:999},{loadClass:'large'}]){const forged=structuredClone(s);Object.assign(forged.units[u.id],patch);expect(()=>decodeCheckpoint(encodeCheckpoint(forged))).toThrow();}});
