import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {plantCrop,progressCrops,advanceCrop,type CropState} from '../src/simulation/crops';
function fixture(){const s:CropState={...createMatch(['vana','human_rohan'],12),crops:{}};const f=s.facilities['p1:core'];f.kind='crop-plot';const irrigation={...f,id:'irrigation',kind:'irrigation',x:f.x+1};s.facilities.irrigation=irrigation;s.players.p1.hero.status='living';s.players.p1.hero.readiness=6;const h={...s.units['p1:company:0'],id:s.players.p1.hero.id,kind:'hero' as const};s.units[h.id]=h;return{s,f};}
it('preserves paid seed and predetermined harvest through one adopted stage advance',()=>{const{s,f}=fixture();plantCrop(s,'p1',f.id,'irrigation');const crop=Object.values(s.crops)[0];const before=s.players.p1.stock.P;advanceCrop(s,'p1',crop.id,()=>true);expect(crop.stage).toBe(1);expect(crop.harvest).toBe(30);expect(s.players.p1.stock.P).toBe(before);expect(()=>advanceCrop(s,'p1',crop.id,()=>true)).toThrow();for(let i=0;i<2;i++){progressCrops(s);s.turn++;}expect(crop.status).toBe('harvested');expect(s.players.p1.stock.P).toBe(before-6+30);});
it('destroyed irrigation fails the existing crop without a harvest or refund',()=>{const{s,f}=fixture();plantCrop(s,'p1',f.id,'irrigation');s.facilities.irrigation.hp=0;const before=s.players.p1.stock.P;progressCrops(s);expect(Object.values(s.crops)[0].status).toBe('failed');expect(s.players.p1.stock.P).toBe(before);});
it('lost tending pauses; a cycle cannot be planted twice',()=>{const{s,f}=fixture();plantCrop(s,'p1',f.id,'irrigation');expect(()=>plantCrop(s,'p1',f.id,'irrigation')).toThrow();f.workers=0;progressCrops(s);expect(Object.values(s.crops)[0].stage).toBe(0);});

it('rejects captured irrigation and disconnected living hero before spending',()=>{const{s,f}=fixture();plantCrop(s,'p1',f.id,'irrigation');const c=Object.values(s.crops)[0];expect(()=>advanceCrop(s,'p1',c.id,()=>false)).toThrow(/connected/);s.facilities.irrigation.owner='p2';expect(()=>advanceCrop(s,'p1',c.id,()=>true)).toThrow(/irrigation/);expect(s.players.p1.hero.readiness).toBe(6);});
