import {it,expect} from 'vitest';import {createMatch,submit,resolveWeek,preview} from '../src/simulation/engine';import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';import {guestSnapshot} from '../src/network/protocol';import type {Match,Order} from '../src/simulation/types';import type {ToolState} from '../src/simulation/tool-services';import type {MountState} from '../src/simulation/remounts';import type {WatchState} from '../src/simulation/watch-posts';import {terrainObserved} from '../src/simulation/visibility';
type State=Match&ToolState&MountState&WatchState;
function fixture(profile:string){const s=Object.assign(createMatch([profile,'human_gondor'],3),{toolMetadata:{},toolJobs:{},mountLots:{},mountJobs:{},watchGear:{},watchJobs:{},borderReports:{},borderSurveys:{}})as State;s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};s.infrastructureSites={};const p=s.players.p1,u=s.units['p1:company:0'];p.stock={P:300,M:300,K:300,E:300};p.sources.push('metal','timber');p.research.push('tool-breach','tool-repair');p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',engineer:undefined,x:4,y:4,inventory:[]};s.facilities['p1:core'].kind='workshop';return s;}
function issue(s:State,action:unknown){const r=submit(s,{id:`integration:${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action}as Order);expect(r.ok,r.reason).toBe(true);return r.state as State;}
it('real production and refit commands fund one queue, preserve salvage/wear and survive checkpoint/privateprojection',()=>{let s=fixture('dwarf_nogrod');s=issue(s,{kind:'tool-service',mode:'make',facility:'p1:core',function:'breach'});s=resolveWeek(s)as State;const input=Object.keys(s.toolMetadata)[0];s.items[input].durability=33;s=issue(s,{kind:'tool-service',mode:'refit',facility:'p1:core',item:input,function:'repair'});expect(preview(s,'p1').players.p1.commitment).toBe(0);s=resolveWeek(s)as State;const output=Object.keys(s.toolMetadata)[0];expect(output).not.toBe(input);expect(s.items[output].durability).toBe(33);expect(decodeCheckpoint(encodeCheckpoint(s)).state.items[output].durability).toBe(33);expect((guestSnapshot(s,'p2')as State).toolMetadata).toEqual({});});
it('stripped watch-post stops being an observer while paid equipment enables the same physical post',()=>{let s=fixture('elf_sindar');for(const f of Object.values(s.facilities))if(f.owner==='p1'){f.x=0;f.y=0;}for(const u of Object.values(s.units))if(u.owner==='p1'){u.x=0;u.y=0;}s.facilities.watch={id:'watch',owner:'p1',name:'Watch',kind:'watch-post',x:20,y:20,hp:30,maxHp:30,workers:1,tier:1};s.map.terrain[20*s.map.width+20]='woodland';expect(terrainObserved(s,'p1',{x:21,y:20})).toBe(false);s=issue(s,{kind:'watch-gear',mode:'make',facility:'watch'});s=resolveWeek(s)as State;expect(terrainObserved(s,'p1',{x:21,y:20})).toBe(true);expect(decodeCheckpoint(encodeCheckpoint(s)).state.facilities.watch.workers).toBe(1);});
it('ordinary breeding and source remount commands preserve finite horses across checkpoint and privacy projection',()=>{
 let s=fixture('human_rohan');const rider=s.units['p1:company:0'],crew=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!,f=s.facilities['p1:training'];
 Object.assign(f,{x:4,y:4});Object.assign(rider,{x:6,y:4});Object.assign(crew,{x:4,y:4,move:3});s.mountLots.tired={id:'tired',owner:'p1',count:12,fatigue:4,stable:null,unit:rider.id};
 s=issue(s,{kind:'mounts',mode:'breed',facility:f.id});expect(preview(s,'p1').players.p1.operations).toBe(3);
 for(let i=0;i<3;i++)s=resolveWeek(s);
 const rested=Object.values(s.mountLots).find(q=>q.stable===f.id)!;expect(rested.count).toBe(12);
 s=issue(s,{kind:'mounts',mode:'exchange',rider:rider.id,lot:rested.id,crew:crew.id,route:[{x:4,y:4},{x:5,y:4},{x:6,y:4}]});
 const planned=preview(s,'p1');expect(planned.players.p1.operations).toBe(2);expect(planned.players.p1.commitment).toBe(0);expect(planned.mountLots[rested.id].unit).toBeNull();
 s=resolveWeek(s);expect(s.mountLots[rested.id].unit).toBe(rider.id);expect(s.mountLots.tired.fatigue).toBe(4);expect(s.mountLots.tired.stable).toBeNull();
 s=decodeCheckpoint(encodeCheckpoint(s)).state;expect(guestSnapshot(s,'p2').mountLots).toEqual({});s=resolveWeek(s);expect(s.mountLots.tired.stable).toBe(f.id);expect(Object.values(s.mountLots).reduce((n,q)=>n+q.count,0)).toBe(24);
});
it('source watch relocation uses one operation and commitment while retaining the stripped old foundation',()=>{
 let s=fixture('elf_sindar');s.map.terrain.fill('woodland');s.waterChannels={};s.preySites={};const worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;Object.assign(worker,{x:5,y:5});Object.assign(s.units[s.players.p1.hero.id],{x:5,y:4});
 s.facilities.watch={id:'watch',owner:'p1',name:'Watch',kind:'watch-post',x:5,y:5,hp:30,maxHp:30,workers:2,tier:1};
 s=issue(s,{kind:'watch-gear',mode:'make',facility:'watch'});s=resolveWeek(s);const gear=Object.keys(s.watchGear)[0];
 s=issue(s,{kind:'watch-gear',mode:'relocate',facility:'watch',worker:worker.id,route:[{x:5,y:5},{x:6,y:5}]});const projected=preview(s,'p1');expect(projected.players.p1.operations).toBe(2);expect(projected.players.p1.commitment).toBe(0);expect(projected.facilities.watch.workers).toBe(0);expect(projected.watchGear[gear].active).toBe(false);
 s=resolveWeek(s);expect(s.facilities.watch).toMatchObject({x:5,y:5,workers:0});expect(s.watchGear[gear].facility).not.toBe('watch');expect(s.facilities[s.watchGear[gear].facility]).toMatchObject({x:6,y:5,workers:2});expect(decodeCheckpoint(encodeCheckpoint(s)).state.watchGear[gear].active).toBe(true);
});
