import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {makeProtectionKit,fitGuard,startTemper,progressEquipmentServices,fittingReduction,fittingMovementPenalty,type EquipmentServiceState} from '../src/simulation/equipment-service';
function fixture(){const s=Object.assign(createMatch(['dwarf_belegost','human_rohan'],2),{protectionKits:{},armorFittings:{},equipmentServices:{}}) as EquipmentServiceState;const p=s.players.p1,u=s.units['p1:company:0'],f=s.facilities['p1:core'];f.kind='workshop';u.x=f.x;u.y=f.y;p.stock={P:100,M:100,K:100,E:100};p.sources.push('metal');p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',engineer:undefined,inventory:[]};s.items.armor={id:'armor',name:'Existing armor',owner:'p1',bearer:u.id,x:u.x,y:u.y,bonus:3,durability:40,maxDurability:100,crafted:true,materials:['metal']};u.inventory=['armor'];return{s,p,u,f};}
it('finite carried kit consumed once; fitting protects only selected ordinary frontal hazard for two phases',()=>{const{s,p,u,f}=fixture();makeProtectionKit(s,'p1',u.id,f.id,'arrows');expect(p.stock.M).toBe(95);fitGuard(s,'p1',u.id,'arrows');expect(p.operations).toBe(2);expect(p.hero.readiness).toBe(4);expect(s.protectionKits[u.id]).toBeUndefined();expect(fittingReduction(s,u.id,'arrows',false)).toBe(25);expect(fittingReduction(s,u.id,'impact',false)).toBe(0);expect(fittingReduction(s,u.id,'arrows',true)).toBe(0);s.revision+=2;expect(fittingReduction(s,u.id,'arrows',false)).toBe(0);expect(s.items.armor.durability).toBe(40);expect(()=>fitGuard(s,'p1',u.id,'arrows')).toThrow();});
it('paid temper queue pauses when company leaves workshop, conserves item and wear, then replaces prior fitting with real burden',()=>{const{s,p,u,f}=fixture();const id=startTemper(s,'p1',u.id,f.id,'impact',()=>true);expect(p.stock).toMatchObject({M:90,K:95});u.x+=4;progressEquipmentServices(s,()=>true);expect(s.equipmentServices[id]).toBeDefined();u.x=f.x;progressEquipmentServices(s,()=>true);expect(s.equipmentServices[id]).toBeUndefined();expect(fittingReduction(s,u.id,'impact',false)).toBe(20);expect(fittingMovementPenalty(s,u.id)).toBe(1);expect(s.items.armor).toMatchObject({id:'armor',durability:40,maxDurability:100});expect(p.hero.readiness).toBe(3);progressEquipmentServices(s,()=>true);expect(p.stock.M).toBe(90);});
it('captured workshop loses paid project without refund or free armor and broken armor disables fitting',()=>{const{s,p,u,f}=fixture();const id=startTemper(s,'p1',u.id,f.id,'impact',()=>true);f.owner='p2';progressEquipmentServices(s,()=>true);expect(s.equipmentServices[id].status).toBe('lost');expect(p.stock.M).toBe(90);expect(s.armorFittings[u.id]).toBeUndefined();});
it('broken or removed armor supplies neither protection nor movement burden; fitting never repairs it',()=>{const{s,u,f}=fixture();startTemper(s,'p1',u.id,f.id,'impact',()=>true);progressEquipmentServices(s,()=>true);s.items.armor.durability=0;expect(fittingReduction(s,u.id,'impact',false)).toBe(0);expect(fittingMovementPenalty(s,u.id)).toBe(0);expect(s.items.armor.durability).toBe(0);});
import {submit,resolveWeek} from '../src/simulation/engine';
import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';
import {guestSnapshot} from '../src/network/protocol';
import {movementPenalty} from '../src/simulation/conditions';
import type {Action} from '../src/simulation/types';
function issue(s:EquipmentServiceState,action:Action){const r=submit(s,{id:`service:${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});expect(r.ok,r.reason).toBe(true);return r.state;}
it('engine queued temper consumes weekly commitment once, persists burden and hides guest private fitting records',()=>{let{s}=fixture();s.map.terrain.fill('meadow');s.seaHazards={};s.shallowWater={};s.infrastructureSites={};const unit='p1:company:0';s=issue(s,{kind:'temper-armor',unit,facility:'p1:core',hazard:'impact'});s=resolveWeek(s);expect(s.players.p1.hero.readiness).toBeLessThanOrEqual(4);expect(s.armorFittings[unit]).toMatchObject({percent:20,burden:1});expect(movementPenalty(s,s.units[unit])).toBe(1);const saved=decodeCheckpoint(encodeCheckpoint(s)).state;expect(saved.armorFittings[unit].item).toBe('armor');expect(guestSnapshot(s,'p2').armorFittings).toEqual({});});
it('actual ordinary hit uses physical distance and opposite attacker to bypass the selected fitting',()=>{const make=(fitted:boolean,flank=false)=>{const setup=fixture();let{s}=setup;const{u}=setup;s.map.terrain.fill('meadow');s.seaHazards={};s.shallowWater={};s.infrastructureSites={};u.x=10;u.y=10;u.hp=100;u.maxHp=100;u.armor=0;const enemy=s.units['p2:company:0'];enemy.x=11;enemy.y=10;enemy.attack=20;if(fitted)s.armorFittings[u.id]={unit:u.id,owner:'p1',item:'armor',hazard:'impact',percent:20,until:null,burden:1};if(flank){const other=structuredClone(enemy);other.id='flanker';other.x=9;s.units[other.id]=other;}const r=submit(s,{id:'enemy:0',seat:'p2',seq:s.nextSeq.p2,turn:s.turn,revision:s.revision,action:{kind:'attack',unit:enemy.id,target:u.id}});expect(r.ok,r.reason).toBe(true);s=resolveWeek(r.state);return s.units[u.id].hp;};expect(make(true)).toBeGreaterThan(make(false));expect(make(true,true)).toBe(make(false));});
