import {assignLifter} from "../src/simulation/habitat-works";
import {expect,it} from 'vitest';
import {limits} from '../src/content/catalog';
import {createMatch} from '../src/simulation/engine';
import {startFieldwork,progressFieldworks,loadRepairKit,braceBreach,markFault,fieldworkBreachBonus,wearFieldTools,type FieldworkState} from '../src/simulation/fieldworks';
function fixture(profile='human_gondor'){const s:FieldworkState={...createMatch([profile,'human_rohan'],8),fieldworkJobs:{},fieldworks:{},repairKits:{},faultMarks:{}};s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};s.infrastructureSites={};const p=s.players.p1,f=s.facilities['p1:core'],worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!,engineer=s.units['p1:company:0'];Object.assign(f,{kind:'workshop',x:4,y:4});Object.assign(worker,{x:4,y:4});Object.assign(engineer,{name:'Field Engineers',engineer:'trained',x:4,y:4});p.stock={P:200,M:200,K:200,E:200};p.sources.push('timber','stone','metal');p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(engineer),id:p.hero.id,kind:'hero',engineer:undefined};return{s,p,f,worker,engineer};}
const route=()=>true;
it('fieldwork reserves a support plot and cannot bypass weak-city development caps',()=>{
 const{s,f,worker}=fixture('manwe');
 for(let i=0;i<limits('manwe').plots;i++)s.facilities[`full:${i}`]={...f,id:`full:${i}`,kind:'workshop',x:20,y:i+1};
 expect(()=>startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'barricade',material:'timber',x:4,y:5},route)).toThrow(/plot/);
});
it('paid real worker builds finite fieldwork after one staffed week; repeated progression creates no duplicate',()=>{const{s,p,f,worker}=fixture();const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'barricade',material:'timber',x:4,y:5},route);expect(p.stock).toMatchObject({P:190,M:185});expect(s.facilities[id]).toBeUndefined();progressFieldworks(s,route);expect(s.facilities[id]).toMatchObject({kind:'barricade',workers:0,hp:60});expect(s.fieldworks[id].material).toBe('timber');progressFieldworks(s,route);expect(Object.keys(s.fieldworks)).toHaveLength(1);expect(p.stock.M).toBe(185);});
it('interrupted crew and captured worksite cannot remotely build or refund',()=>{const{s,p,f,worker}=fixture();const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'gate',material:'stone',x:4,y:5},route);worker.x=20;progressFieldworks(s,route);expect(s.facilities[id]).toBeUndefined();f.owner='p2';progressFieldworks(s,route);expect(s.fieldworkJobs[id].status).toBe('lost');expect(p.stock.M).toBe(170);});
it('Gondor consumes carried compatible five Materials and engineer action to restore at most fifteen percent',()=>{const{s,p,f,worker,engineer}=fixture();const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'gate',material:'stone',x:4,y:5},route);s.units.lifter={...structuredClone(worker),id:'lifter'};assignLifter(s,'p1',id,'lifter');progressFieldworks(s,route);s.facilities[id].hp=92;loadRepairKit(s,'p1',engineer.id,f.id,'stone');const stock=p.stock.M;braceBreach(s,'p1',engineer.id,id);expect(s.facilities[id].hp).toBe(100);expect(s.repairKits[engineer.id]).toBeUndefined();expect(p.stock.M).toBe(stock);expect(p.hero.readiness).toBe(4);expect(p.operations).toBe(2);expect(()=>braceBreach(s,'p1',engineer.id,id)).toThrow();});
it('Gondor cannot revive destroyed structures or substitute incompatible kit material',()=>{const{s,f,worker,engineer}=fixture();const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'barricade',material:'timber',x:4,y:5},route);progressFieldworks(s,route);s.facilities[id].hp=20;loadRepairKit(s,'p1',engineer.id,f.id,'stone');expect(()=>braceBreach(s,'p1',engineer.id,id)).toThrow(/compatible/);s.facilities[id].hp=0;expect(()=>braceBreach(s,'p1',engineer.id,id)).toThrow();expect(s.repairKits[engineer.id].stock.M).toBe(5);});
it('Khazad marks damaged stone only; actual engineer breach gains twentyfive percent and normal tool wear remains',()=>{const{s,f,worker,engineer}=fixture('dwarf_khazad_dum');const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'barricade',material:'stone',x:4,y:5},route);progressFieldworks(s,route);s.facilities[id].hp=30;s.items.tools={id:'tools',name:'Field breach tools',owner:'p1',bearer:engineer.id,x:4,y:4,bonus:0,durability:20,maxDurability:20,crafted:true,materials:['metal']};engineer.inventory.push('tools');markFault(s,'p1',id,()=>true);expect(fieldworkBreachBonus(s,engineer,id)).toBe(25);wearFieldTools(s,engineer);expect(s.items.tools.durability).toBe(16);s.revision++;expect(fieldworkBreachBonus(s,engineer,id)).toBe(0);expect(s.facilities[id].hp).toBe(30);});

import {submit,resolveWeek,path} from '../src/simulation/engine';
import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';
import {guestSnapshot} from '../src/network/protocol';
import type {Match,Action} from '../src/simulation/types';
function issue(s:Match,action:Action){const r=submit(s,{id:`field:${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});expect(r.ok,r.reason).toBe(true);return r.state;}
it('real paid queues create engineers and tools; typed engineer identity survives display renaming',()=>{let{s,f}=fixture();f.kind='training';s=issue(s,{kind:'produce',facility:f.id,recipe:'engineers'});s=resolveWeek(s);s=resolveWeek(s);const e=Object.values(s.units).find(u=>u.id.startsWith('unit:')&&u.engineer==='trained')!;expect(e).toMatchObject({kind:'company',hp:60,attack:12});e.name='Renamed siege team';f=s.facilities[f.id];f.kind='workshop';s=issue(s,{kind:'produce',facility:f.id,recipe:'field-tools'});s=resolveWeek(s);expect(Object.values(s.items).some(i=>i.name==='Field breach tools')).toBe(true);s=decodeCheckpoint(encodeCheckpoint(s)).state;expect(s.units[e.id].engineer).toBe('trained');});
it('engine construction blocks physical passage and resumes after actual ordinary destruction without salvage',()=>{let{s}=fixture('troll_hold');const f=s.facilities['p1:core'],worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;s=issue(s,{kind:'fieldwork',worker:worker.id,facility:f.id,form:'barricade',material:'stone',x:4,y:5});s=resolveWeek(s);const id=Object.keys(s.fieldworks)[0],barrier=s.facilities[id],enemy=s.units['p2:company:0'];expect(path(s,{x:4,y:4},{x:4,y:5},false,enemy)).toBeNull();barrier.owner='p2';barrier.hp=1;const hero=s.units[s.players.p1.hero.id];hero.attack=50;const before=s.players.p1.stock.M;s=issue(s,{kind:'attack',unit:hero.id,target:id});s=resolveWeek(s);expect(s.facilities[id].hp).toBe(0);expect(path(s,{x:4,y:4},{x:4,y:5},false,s.units[hero.id])).not.toBeNull();expect(s.players.p1.stock.M).toBe(before);expect(guestSnapshot(s,'p2').fieldworkJobs).toEqual({});});
it('display-name forgery does not make a regular company an engineer and lost kits cannot copy resources',()=>{const{s,f,engineer}=fixture();delete engineer.engineer;expect(()=>loadRepairKit(s,'p1',engineer.id,f.id,'stone')).toThrow(/engineer/);engineer.engineer='trained';loadRepairKit(s,'p1',engineer.id,f.id,'stone');const before=s.players.p1.stock.M;engineer.alive=false;progressFieldworks(s,route);expect(s.repairKits[engineer.id]).toBeUndefined();expect(s.players.p1.stock.M).toBe(before);});
it('same response phase fault survey strengthens a real ordinary engineer breach before expiring',()=>{const fixtureState=fixture('dwarf_khazad_dum');let{s}=fixtureState;const{f,worker,engineer}=fixtureState;const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'barricade',material:'stone',x:4,y:5},route);progressFieldworks(s,route);s.facilities[id].owner='p2';s.facilities[id].hp=50;engineer.attack=20;s.items.tools={id:'tools',name:'Field breach tools',owner:'p1',bearer:engineer.id,x:4,y:4,bonus:0,durability:20,maxDurability:20,crafted:true,materials:['metal']};engineer.inventory.push('tools');const baseline=issue(structuredClone(s),{kind:'attack',unit:engineer.id,target:id});const ordinary=resolveWeek(baseline);s=issue(s,{kind:'read-fault',target:id});s=issue(s,{kind:'attack',unit:engineer.id,target:id});s=resolveWeek(s);expect(s.facilities[id].hp).toBeLessThan(ordinary.facilities[id].hp);expect(s.items.tools.durability).toBe(16);expect(s.players.p1.operations).toBe(2);expect(s.players.p1.commitment).toBe(0);while(s.combatPhase)s=resolveWeek(s);expect(decodeCheckpoint(encodeCheckpoint(s)).state.facilities[id].hp).toBe(s.facilities[id].hp);});
import {parseMatch} from '../src/simulation/schema';
it('guest tactical signals reject absent targets, invalid bounds, expired observations and duplicate IDs',()=>{const{s}=fixture();const g=guestSnapshot(s,'p1');const valid={id:'signal:1',kind:'grapple' as const,target:'p1:company:0',phase:'warning' as const,origin:{x:4,y:4},until:s.revision+1};for(const signals of [[{...valid,target:'missing'}],[{...valid,origin:{x:s.map.width,y:4}}],[{...valid,until:s.revision}],[valid,valid]]){g.tacticalSignals=signals;expect(()=>parseMatch(g,'p1')).toThrow(/tactical observations/);}g.tacticalSignals=[valid];expect(()=>parseMatch(g,'p1')).not.toThrow();});
