import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {finalProduction,finalKeys,finalDeviceReason,deployFinalDevice,consumeFinalItem,type FinalItem} from '../src/content/final-production';
import {movementZonePenalty,crossZones,pruneZones} from '../src/simulation/zones';
const owners=['dwarf_nogrod','dwarf_nogrod','dwarf_nogrod','melian','ilmare','human_numenor','dwarf_khazad_dum','elf_finarfin','elf_falmari','elf_sindar','elf_sindar','elf_avari','elf_nandor'];
it('all thirteen remaining named outputs have explicit finite faction-only ordinary recipes',()=>{expect(finalKeys).toHaveLength(13);for(let i=0;i<13;i++){const q=finalProduction(owners[i],finalKeys[i])!;expect(q.recipe.provisional).toBe(true);expect(q.recipe.turns).toBeGreaterThan(0);expect(finalProduction('human_rohan',finalKeys[i])).toBeUndefined();expect(q.source).toContain('silmarillion-game-report.md');}});
function fixture(profile='elf_nandor',key='root-snare'){const s=createMatch([profile,'human_rohan'],25),u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='company')!,q=finalProduction(profile,key)!;if(q.kind!=='item')throw Error('Expected equipment');const item={id:'gear',name:q.recipe.name,owner:'p1',bearer:u.id,x:u.x,y:u.y,crafted:true,...q.item,finalProduct:key}as FinalItem;s.items.gear=item;u.inventory.push(item.id);s.players.p1.operations=3;return{s,u,item};}
it('a carried purchased root snare becomes one real bounded movement obstacle and cannot be reused',()=>{const{s,u,item}=fixture(),at={x:u.x+1,y:u.y};s.map.terrain[at.y*s.map.width+at.x]='woodland';deployFinalDevice(s,'p1',u.id,item.id,at);expect(item.durability).toBe(0);expect(item.bearer).toBeNull();expect(u.inventory).not.toContain(item.id);expect(s.players.p1.operations).toBe(2);expect(movementZonePenalty(s,u,[u,at])).toBe(1);expect(finalDeviceReason(s,'p1',u.id,item.id,at)).not.toBe('');s.revision+=2;pruneZones(s);expect(movementZonePenalty(s,u,[u,at])).toBe(0);});
it('boundary device produces actual dated local tripwire reports without naming its crossing unit',()=>{const{s,u,item}=fixture('elf_sindar','boundary-ward'),at={x:u.x+1,y:u.y},enemy=Object.values(s.units).find(u=>u.owner==='p2'&&u.kind==='company')!;s.map.terrain[at.y*s.map.width+at.x]='grass';deployFinalDevice(s,'p1',u.id,item.id,at);crossZones(s,enemy,[u,at]);expect(s.events.at(-1)?.audience).toEqual(['p1']);expect(s.events.at(-1)?.text).not.toContain(enemy.id);});
it('physical utility consumes only actual worn durable equipment and never heavy carried items',()=>{const{s,u,item}=fixture('human_numenor','sea-ward');expect(consumeFinalItem(s,u,'sea-ward')).toBe(true);expect(item.durability).toBe(99);Object.assign(item,{heavy:true,carried:true});expect(consumeFinalItem(s,u,'sea-ward')).toBe(false);expect(item.durability).toBe(99);});
it('deploying a hero equipped device also removes its mirrored hero equipment identity',()=>{const{s,u,item}=fixture();s.units[s.players.p1.hero.id]={...structuredClone(u),id:s.players.p1.hero.id,kind:'hero',inventory:['gear']};const h=s.units[s.players.p1.hero.id];u.inventory=[];item.bearer=h.id;s.players.p1.hero.status='living';s.players.p1.hero.equipment=['gear'];const at={x:h.x+1,y:h.y};s.map.terrain[at.y*s.map.width+at.x]='woodland';deployFinalDevice(s,'p1',h.id,item.id,at);expect(s.players.p1.hero.equipment).toEqual([]);expect(h.inventory).toEqual([]);});
