import {expect,it} from 'vitest';
import {createMatch,submit,resolveWeek} from '../src/simulation/engine';
import {guestSnapshot} from '../src/network/protocol';
import {parseMatch} from '../src/simulation/schema';
import type {Action,Match} from '../src/simulation/types';
function setup(profile='elf_avari'){const s=createMatch([profile,'human_gondor'],82);s.map.terrain.fill('meadow');s.seaHazards={};s.shallowWater={};s.preySites={};s.infrastructureSites={};const p=s.players.p1;p.hero.status='living';p.hero.readiness=6;p.stock={P:100,M:100,K:100,E:100};s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero',x:10,y:9};Object.assign(s.units['p1:company:0'],{x:10,y:10,hp:100,maxHp:100,move:8});Object.assign(s.units['p1:company:1'],{x:10,y:11,hp:100,maxHp:100,move:8});return s;}
function issue(s:Match,seat:string,action:Action){const r=submit(s,{id:`${seat}-${s.revision}-${s.nextSeq[seat]}`,seat,seq:s.nextSeq[seat],turn:s.turn,revision:s.revision,action});expect(r.ok,r.reason).toBe(true);return r.state;}
const pair=[{unit:'p1:company:0',route:[{x:10,y:10},{x:11,y:10}]},{unit:'p1:company:1',route:[{x:10,y:11},{x:11,y:11}]}];
it('Avari pays two ordinary movements and one tactical commitment, saves privately and cannot move twice',()=>{let s=setup();s=resolveWeek(issue(s,'p1',{kind:'formation-power',mode:'rendezvous',movement:'advance',members:pair}));expect(s.players.p1.operations).toBe(1);expect(s.players.p1.commitment).toBe(0);expect(s.players.p1.hero.readiness).toBe(4);expect(()=>parseMatch(s)).not.toThrow();const guest=guestSnapshot(s,'p2');expect(guest.formationOrders).toEqual({});expect(()=>parseMatch(guest,'p2')).not.toThrow();const duplicate=submit(s,{id:'duplicate',seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action:{kind:'move',unit:pair[0].unit,x:11,y:10}});expect(duplicate.ok).toBe(false);s=resolveWeek(s);expect(s.units[pair[0].unit].x).toBe(11);expect(s.units[pair[1].unit].x).toBe(11);expect(s.players.p1.operations).toBe(1);});
it('paired retreats avoid only mutual coordination loss and remain subject to a real normal pursuit hit',()=>{let s=setup();Object.assign(s.units['p2:company:0'],{x:9,y:10,attack:8});s=issue(s,'p1',{kind:'formation-power',mode:'rendezvous',movement:'retreat',members:pair});s=issue(s,'p2',{kind:'declare-tactical',order:{kind:'pursuit',unit:'p2:company:0',target:'p1:company:0'}});s=resolveWeek(s);s=resolveWeek(s);expect(s.units[pair[0].unit].hp).toBeLessThan(100);expect(s.units[pair[0].unit].x).toBe(11);for(const m of pair)expect(s.units[m.unit].effects.some(e=>e.kind==='cohesion-loss'&&e.value>0)).toBe(false);});
it('Muster reserves all three movements and rejects a fourth ordinary operation without manufacturing an attack',()=>{let s=setup('eonwe');const third={...structuredClone(s.units['p1:company:0']),id:'third',x:12,y:12};s.units.third=third;Object.assign(s.facilities['p1:core'],{x:12,y:10});Object.assign(s.sites[0],{x:12,y:10});const members=[pair[0],{unit:pair[1].unit,route:[{x:10,y:11},{x:11,y:11},{x:12,y:11}]},{unit:'third',route:[{x:12,y:12},{x:13,y:12},{x:13,y:11},{x:13,y:10}]}];s=resolveWeek(issue(s,'p1',{kind:'formation-power',mode:'muster',relay:'p1:core',objective:s.sites[0].id,members}));expect(s.players.p1.operations).toBe(0);expect(s.players.p1.stock).toMatchObject({P:85,M:90});expect(()=>parseMatch(s)).not.toThrow();const extra=submit(s,{id:'fourth',seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action:{kind:'exchange'}});expect(extra.ok).toBe(false);s=resolveWeek(s);expect(s.units.third.x).toBe(13);while(s.combatPhase)s=resolveWeek(s);expect(s.sites[0].owner).toBe('p1');});
it('a captured relay preserves only the written fallback with no new operation or remote destination',()=>{let s=setup('eonwe');const third={...structuredClone(s.units['p1:company:0']),id:'third',x:12,y:12};s.units.third=third;Object.assign(s.facilities['p1:core'],{x:12,y:10});Object.assign(s.sites[0],{x:12,y:10});const members=[pair[0],{unit:pair[1].unit,route:[{x:10,y:11},{x:11,y:11},{x:12,y:11}]},{unit:'third',route:[{x:12,y:12},{x:13,y:12},{x:13,y:11},{x:13,y:10}]}];s=resolveWeek(issue(s,'p1',{kind:'formation-power',mode:'muster',relay:'p1:core',objective:s.sites[0].id,members,commission:{unit:pair[0].unit,route:[{x:10,y:10},{x:11,y:10}]}}));s.facilities['p1:core'].workers=0;s=resolveWeek(s);expect(s.units[pair[0].unit].x).toBe(11);expect(s.units[pair[1].unit].x).toBe(10);expect(s.units.third.x).toBe(12);expect(s.players.p1.operations).toBe(0);expect(Object.values(s.formationOrders)).toHaveLength(0);});
it('rendezvous does not erase an uninvolved formation coordination penalty',()=>{let s=setup();s.units.uninvolved={...structuredClone(s.units['p1:company:0']),id:'uninvolved',x:9,y:11};s=resolveWeek(issue(s,'p1',{kind:'formation-power',mode:'rendezvous',movement:'retreat',members:pair}));s=resolveWeek(s);expect(s.units.uninvolved.effects.some(e=>e.kind==='cohesion-loss'&&e.value>0)).toBe(true);});
it('Watch Rotation exchanges posts created through real survey movement and paid ordinary garrison assignments',()=>{let s=setup('elf_fingolfin');Object.assign(s.units[s.players.p1.hero.id],{x:10,y:8});Object.assign(s.facilities['p1:core'],{x:10,y:8});s.facilities.second={...structuredClone(s.facilities['p1:core']),id:'second',kind:'beacon',x:12,y:11};Object.assign(s.units['p1:company:1'],{x:12,y:9});s=issue(s,'p1',{kind:'move',unit:'p1:company:0',x:10,y:9});s=issue(s,'p1',{kind:'move',unit:'p1:company:1',x:12,y:10});s=resolveWeek(s);const surveys=Object.values(s.routeSurveys).filter(q=>q.owner==='p1');expect(surveys).toHaveLength(2);const first=surveys.find(q=>q.route.at(-1)?.x===10)!,second=surveys.find(q=>q.route.at(-1)?.x===12)!;s=issue(s,'p1',{kind:'post-garrison',unit:'p1:company:0',post:'p1:core',survey:first.id});s=issue(s,'p1',{kind:'post-garrison',unit:'p1:company:1',post:'second',survey:second.id});s=resolveWeek(s);expect(s.garrisonPosts['p1:company:0'].post).toBe('p1:core');s=issue(s,'p1',{kind:'formation-power',mode:'rotation',members:[{unit:'p1:company:0',route:[{x:10,y:9},{x:11,y:9},{x:12,y:9},{x:12,y:10}]},{unit:'p1:company:1',route:[{x:12,y:10},{x:11,y:10},{x:10,y:10},{x:10,y:9}]}]});s=resolveWeek(s);expect(s.players.p1.operations).toBe(1);s=resolveWeek(s);expect(s.garrisonPosts['p1:company:0'].post).toBe('second');expect(s.garrisonPosts['p1:company:1'].post).toBe('p1:core');expect(()=>parseMatch(s)).not.toThrow();});
it('simultaneous formation and pursuit outcomes are independent of network arrival order across twelve stored seeds',()=>{for(let seed=1;seed<=12;seed++){const base=setup();base.rng=seed;Object.assign(base.units['p2:company:0'],{x:9,y:10,attack:8});const formation:Action={kind:'formation-power',mode:'rendezvous',movement:'retreat',members:pair},pursuit:Action={kind:'declare-tactical',order:{kind:'pursuit',unit:'p2:company:0',target:'p1:company:0'}};let a=issue(issue(structuredClone(base),'p1',formation),'p2',pursuit),b=issue(issue(structuredClone(base),'p2',pursuit),'p1',formation);a=resolveWeek(resolveWeek(a));b=resolveWeek(resolveWeek(b));expect(a).toEqual(b);expect(()=>parseMatch(a)).not.toThrow();}});
it('hero captivity blocks formation commands without changing stocks, readiness or the one occupied slot',()=>{const s=setup();s.players.p1.hero.status='captive';s.players.p1.hero.captor='p2';s.units[s.players.p1.hero.id].active=false;const before=structuredClone(s);const r=submit(s,{id:'captive-plan',seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action:{kind:'formation-power',mode:'rendezvous',movement:'advance',members:pair}});expect(r.ok).toBe(false);expect(s).toEqual(before);expect(s.players.p1.hero.status).toBe('captive');});
