import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {prepareFormation,resolveFormations,formationReason,assignPost,recordFormationObservation,interruptFormation,type FormationState} from '../src/simulation/formation-orders';
import type {Match,Pos} from '../src/simulation/types';
const path=(_s:Match,a:Pos,b:Pos)=>[a,b];
function fixture(profile='elf_avari'){const s:FormationState={...createMatch([profile,'human_gondor'],88),formationOrders:{},garrisonPosts:{},garrisonReports:{}};s.map.terrain.fill('meadow');s.infrastructureSites={};const p=s.players.p1;p.hero.status='living';p.hero.readiness=6;p.stock.P=100;p.stock.M=100;s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero',x:10,y:9};Object.assign(s.units['p1:company:0'],{x:10,y:10,move:8});Object.assign(s.units['p1:company:1'],{x:10,y:11,move:8});return{s,p};}
const members=[{unit:'p1:company:0',route:[{x:10,y:10},{x:11,y:10}]},{unit:'p1:company:1',route:[{x:10,y:11},{x:11,y:11}]}];
it('Avari synchronizes two real paid movements without movement or damage bonus and rechecks blocked exits',()=>{const{s,p}=fixture();const q=prepareFormation(s,'p1',{mode:'rendezvous',movement:'advance',members},path);expect(p.hero.readiness).toBe(4);expect(s.units[members[0].unit].x).toBe(10);s.revision++;resolveFormations(s,path);expect(s.units[members[0].unit].x).toBe(11);expect(s.units[members[1].unit].x).toBe(11);expect(s.formationOrders[q.id]).toBeUndefined();});
it('blocked paired route or interrupted signal cannot silently grant movement',()=>{const{s}=fixture();prepareFormation(s,'p1',{mode:'rendezvous',movement:'advance',members},path);s.revision++;resolveFormations(s,()=>null);expect(s.units[members[0].unit].x).toBe(10);expect(s.units[members[1].unit].x).toBe(10);});
it('Watch Rotation requires real existing garrison assignments and keeps only personally observed route reports',()=>{const{s,p}=fixture('elf_fingolfin');const f=s.facilities['p1:core'];Object.assign(f,{x:10,y:9});s.facilities.post={...structuredClone(f),id:'post',kind:'watchtower',x:12,y:11};s.routeSurveys.road={id:'road',owner:'p1',route:[{x:10,y:10},{x:11,y:10},{x:12,y:10}],turn:1,revision:0};Object.assign(s.units['p1:company:1'],{x:12,y:10});assignPost(s,'p1','p1:company:0',f.id,'road');assignPost(s,'p1','p1:company:1','post','road');const a={mode:'rotation' as const,members:[{unit:'p1:company:0',route:[{x:10,y:10},{x:11,y:10},{x:12,y:10}]},{unit:'p1:company:1',route:[{x:12,y:10},{x:12,y:9},{x:11,y:9}]}]};expect(formationReason(s,'p1',a,path)).toBe('');prepareFormation(s,'p1',a,path);expect(p.hero.readiness).toBe(3);s.revision++;resolveFormations(s,path);expect(s.garrisonPosts['p1:company:0'].post).toBe('post');const enemy=s.units['p2:company:0'];Object.assign(enemy,{x:11,y:10});recordFormationObservation(s,enemy,[{x:12,y:10},{x:11,y:10}]);expect(Object.values(s.garrisonReports).some(r=>r.owner==='p1')).toBe(true);});
it('Eonwe reserves exactly three routes and exact stocks; severed staffed relay preserves only one written fallback',()=>{const{s,p}=fixture('eonwe');const u={...structuredClone(s.units['p1:company:0']),id:'third',x:9,y:10};s.units[u.id]=u;const f=s.facilities['p1:core'];Object.assign(f,{x:12,y:10});s.sites[0].x=12;s.sites[0].y=10;const a={mode:'muster' as const,relay:f.id,objective:s.sites[0].id,members:[members[0],members[1],{unit:u.id,route:[{x:9,y:10},{x:9,y:11},{x:10,y:11},{x:11,y:11}]}],commission:{unit:'p1:company:0',route:[{x:10,y:10},{x:11,y:10}]}};expect(formationReason(s,'p1',a,path)).toMatch(/distinct|occupied|rally/);a.members[2].route=[{x:9,y:10},{x:9,y:9},{x:9,y:8},{x:10,y:8},{x:11,y:8},{x:12,y:8},{x:12,y:9}];a.members[1].route=[{x:10,y:11},{x:11,y:11},{x:12,y:11}];u.x=9;prepareFormation(s,'p1',a,path);expect(p.stock).toMatchObject({P:85,M:90});interruptFormation(s,p.hero.id,1);s.revision++;resolveFormations(s,path);expect(Object.values(s.tacticalOrders).filter(q=>q.kind==='fallback').map(q=>q.unit)).toEqual(['p1:company:0']);expect(s.units.third.x).toBe(9);});
