import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {startFieldwork,progressFieldworks} from '../src/simulation/fieldworks';
import {habitatReason,applyHabitatPower,progressHabitat,recordHabitatTravel,trailConvoyReason,assignLifter,interruptHabitat,blockTrail,type HabitatState} from '../src/simulation/habitat-works';
const route=()=>true;
function fixture(profile='yavanna'){const s:HabitatState={...createMatch([profile,'human_gondor'],82),vegetation:{},livingBarriers:{},oldTrails:{},trailProjects:{},heroTrailSurveys:{}};s.map.terrain.fill('meadow');const p=s.players.p1;p.hero.status='living';p.hero.readiness=6;p.stock.M=100;p.stock.P=100;p.sources.push('stone');const h={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero' as const,x:4,y:4};s.units[h.id]=h;const f=s.facilities['p1:core'];Object.assign(f,{x:4,y:4});const worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;Object.assign(worker,{x:4,y:4});s.map.terrain[5*s.map.width+4]='woodland';s.vegetation.grove={id:'grove',x:4,y:5,mature:true,altered:false};return{s,p,h,f,worker};}
it('Living Buttress reconfigures mature vegetation into finite destructible barrier without materials or respawn',()=>{const{s,p,f}=fixture(),before=p.stock.M;applyHabitatPower(s,'p1',{mode:'living-buttress',vegetation:'grove',facility:f.id},route);const id=Object.keys(s.livingBarriers)[0];expect(s.facilities[id].hp).toBe(60);expect(p.stock.M).toBe(before);expect(p.hero.readiness).toBe(3);expect(s.vegetation.grove.altered).toBe(true);s.turn++;progressHabitat(s,route);expect(s.facilities[id].hp).toBe(0);expect(()=>applyHabitatPower(s,'p1',{mode:'living-buttress',vegetation:'grove',facility:f.id},route)).toThrow();});
it('Shoulder substitutes only the real lifting role of a fully paid tagged phase, preserving mainworker requirements',()=>{const{s,p,h,f,worker}=fixture('tulkas');const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'gate',material:'stone',x:4,y:5},route);const paid=p.stock.M;progressFieldworks(s,route);expect(s.facilities[id]).toBeUndefined();applyHabitatPower(s,'p1',{mode:'shoulder-burden',job:id},route);expect(p.stock.M).toBe(paid);worker.supplied=false;progressFieldworks(s,route);expect(s.facilities[id]).toBeUndefined();worker.supplied=true;h.x=20;progressFieldworks(s,route);expect(s.facilities[id]).toBeUndefined();h.x=4;progressFieldworks(s,route);expect(s.facilities[id].hp).toBe(100);});
it('an ordinary separate supplied lifting worker fulfills the same tagged role',()=>{const{s,f,worker}=fixture('tulkas');const lifter={...structuredClone(worker),id:'lifter'};s.units[lifter.id]=lifter;const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'gate',material:'stone',x:4,y:5},route);expect(()=>assignLifter(s,'p1',id,worker.id)).toThrow();assignLifter(s,'p1',id,lifter.id);progressFieldworks(s,route);expect(s.facilities[id].hp).toBe(100);});
it('Nandor requires actual hero survey and a supplied worker, restores only authored trail and never unlocks heavy convoys',()=>{const{s,p,h,f,worker}=fixture('elf_nandor');const tiles=[{x:4,y:4},{x:4,y:5}];for(const at of tiles)s.map.terrain[at.y*s.map.width+at.x]='woodland';s.oldTrails.old={id:'old',tiles,blocked:true,waystation:f.id};const a={mode:'old-trail' as const,trail:'old',worker:worker.id};expect(habitatReason(s,'p1',a,route)).toMatch(/survey/);h.y=5;recordHabitatTravel(s,h,tiles);const before=p.stock.M;applyHabitatPower(s,'p1',a,route);expect(p.stock.M).toBe(before-5);expect(trailConvoyReason(s,tiles,10)).not.toBe('');progressHabitat(s,route);expect(s.oldTrails.old.blocked).toBe(false);expect(trailConvoyReason(s,tiles,10)).toBe('');expect(trailConvoyReason(s,tiles,21)).not.toBe('');});
it('a damaged Tulkas loses the week lifting substitution and cannot silently restart the role',()=>{const{s,h,f,worker}=fixture('tulkas');const id=startFieldwork(s,'p1',{worker:worker.id,facility:f.id,kind:'gate',material:'stone',x:4,y:5},route);applyHabitatPower(s,'p1',{mode:'shoulder-burden',job:id},route);interruptHabitat(s,h.id,1);progressFieldworks(s,route);expect(s.facilities[id]).toBeUndefined();expect(s.fieldworkJobs[id].lifting?.unit).toBeUndefined();});
it('trail patrol interrupts restoration and renewed physical obstruction stops only its actual frontage',()=>{const{s,h,f,worker}=fixture('elf_nandor'),tiles=[{x:4,y:4},{x:4,y:5}];for(const at of tiles)s.map.terrain[at.y*s.map.width+at.x]='woodland';s.oldTrails.old={id:'old',tiles,blocked:true,waystation:f.id};h.y=5;recordHabitatTravel(s,h,tiles);applyHabitatPower(s,'p1',{mode:'old-trail',trail:'old',worker:worker.id},route);const enemy=s.units['p2:company:0'];Object.assign(enemy,{x:5,y:5});progressHabitat(s,route);expect(s.oldTrails.old.blocked).toBe(true);enemy.x=20;progressHabitat(s,route);expect(s.oldTrails.old.blocked).toBe(false);enemy.x=5;blockTrail(s,'p2',enemy.id,'old');expect(s.oldTrails.old.blocked).toBe(true);expect(trailConvoyReason(s,[{x:20,y:20},{x:21,y:20}],10)).toBe('');});
