import {expect,it} from 'vitest';
import {createMatch,submit,resolveWeek} from '../src/simulation/engine';
import {parseMatch} from '../src/simulation/schema';
import {guestSnapshot} from '../src/network/protocol';
import {recordPatrolMovement} from '../src/simulation/patrols';
import type {Action,Match} from '../src/simulation/types';
function issue(s:Match,action:Action){const r=submit(s,{id:`p1-${s.revision}-${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});expect(r.ok,r.reason).toBe(true);return r.state;}
function fixture(profile:string){const s=createMatch([profile,'human_gondor'],81);s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};s.oldTrails={};s.vegetation={};s.preySites={};const p=s.players.p1;p.hero.status='living';p.hero.readiness=6;p.stock={P:100,M:100,K:100,E:100};p.sources.push('stone');const worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;Object.assign(worker,{x:4,y:4});s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero',x:4,y:4};Object.assign(s.facilities['p1:core'],{x:4,y:4});return s;}
it('Tulkas pays ordinary tagged recipe once and supplies only lifting while preserving worker operation and weeklyhero budget',()=>{let s=fixture('tulkas');const worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;s=issue(s,{kind:'fieldwork',worker:worker.id,facility:'p1:core',form:'gate',material:'stone',x:4,y:5});s.combatPhase=1;s=resolveWeek(s);const job=Object.keys(s.fieldworkJobs)[0];expect(s.fieldworkJobs[job].lifting).toEqual({});const paid=s.players.p1.stock.M;s=issue(s,{kind:'habitat-power',mode:'shoulder-burden',job});s=resolveWeek(s);expect(s.facilities[job].hp).toBe(100);expect(s.players.p1.stock.M).toBeGreaterThanOrEqual(paid);expect(s.players.p1.hero.readiness).toBe(3);expect(()=>parseMatch(s)).not.toThrow();});
it('actual hero movement records trailproof and normal restoration remains private and persistent',()=>{let s=fixture('elf_nandor');const p=s.players.p1,h=s.units[p.hero.id],worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!,tiles=[{x:4,y:4},{x:4,y:5}];for(const at of tiles)s.map.terrain[at.y*s.map.width+at.x]='woodland';s.oldTrails.old={id:'old',tiles,blocked:true,waystation:'p1:core'};h.y=5;recordPatrolMovement(s,h,tiles);expect(Object.values(s.heroTrailSurveys)).toHaveLength(1);s=issue(s,{kind:'habitat-power',mode:'old-trail',trail:'old',worker:worker.id});s=resolveWeek(s);expect(s.oldTrails.old.blocked).toBe(false);expect(()=>parseMatch(s)).not.toThrow();expect(guestSnapshot(s,'p2').heroTrailSurveys).toEqual({});});
it('livingbuttress uses existingwoodland, obeysweakcityplotcaps and expires without Materials',()=>{let s=fixture('yavanna');s.vegetation.grove={id:'grove',x:4,y:5,mature:true,altered:false};s.map.terrain[5*s.map.width+4]='woodland';s.combatPhase=1;s=issue(s,{kind:'habitat-power',mode:'living-buttress',vegetation:'grove',facility:'p1:core'});s=resolveWeek(s);expect(Object.values(s.livingBarriers)).toHaveLength(1);expect(s.vegetation.grove.altered).toBe(true);expect(()=>parseMatch(s)).not.toThrow();s=resolveWeek(s);expect(Object.values(s.livingBarriers)).toHaveLength(0);expect(s.vegetation.grove.altered).toBe(true);});
it('a living barrier destroyed by an actual attack leaves no invalid live metadata in a tactical checkpoint',()=>{let s=fixture('yavanna');s.vegetation.grove={id:'grove',x:4,y:5,mature:true,altered:false};s.map.terrain[5*s.map.width+4]='woodland';s.combatPhase=1;s=resolveWeek(issue(s,{kind:'habitat-power',mode:'living-buttress',vegetation:'grove',facility:'p1:core'}));const id=Object.keys(s.livingBarriers)[0],enemy=s.units['p2:company:0'];Object.assign(enemy,{x:5,y:5,attack:200});const result=submit(s,{id:'destroy-barrier',seat:'p2',seq:s.nextSeq.p2,turn:s.turn,revision:s.revision,action:{kind:'attack',unit:enemy.id,target:id}});expect(result.ok,result.reason).toBe(true);result.state.combatPhase=1;s=resolveWeek(result.state);expect(s.facilities[id].hp).toBe(0);expect(s.livingBarriers[id]).toBeUndefined();expect(()=>parseMatch(s)).not.toThrow();});
