import {expect,it} from 'vitest';
import {createMatch,submit,resolveWeek,preview} from '../src/simulation/engine';
import type {Action} from '../src/simulation/types';
import {carryHeavy,dropHeavy,heavyCarryReason,heavyLoad,heavyCargoCapacity,heavySprintReason,heavyMovementLimit,settleHeavyEquipment,validateHeavyEquipment,type HeavyItem} from '../src/simulation/heavy-equipment';
function setup(profile='troll_hold'){const s=createMatch([profile,'human_rohan'],6),p=s.players.p1,f=s.facilities['p1:core'],worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;worker.x=f.x;worker.y=f.y;s.units[p.hero.id]={...structuredClone(worker),id:p.hero.id,kind:'hero',inventory:[],effects:[]};p.hero.status='living';p.operations=3;s.items.plate={id:'plate',name:'Stonehide Plate',owner:'p1',bearer:null,x:f.x,y:f.y,bonus:4,attackBonus:0,durability:100,maxDurability:100,materials:['stone'],crafted:true,heavy:true}as HeavyItem;return{s,p,worker,h:s.units[p.hero.id]};}
it('Troll physically carries one existing heavy item without porter or free armor and uses normal load capacity',()=>{const{s,p,h}=setup(),armor=h.armor,supply=h.supply;carryHeavy(s,'p1','plate',h.id);expect(s.items.plate.bearer).toBe(h.id);expect(h.inventory).toEqual(['plate']);expect(h.armor).toBe(armor);expect(h.supply).toBe(supply);expect(heavyLoad(s,h)).toBe(10);expect(heavyCargoCapacity(s,h,20)).toBe(10);expect(heavySprintReason(s,h)).toMatch(/sprint/);expect(p.operations).toBe(2);expect(()=>validateHeavyEquipment(s)).not.toThrow();});
it('other heroes need a real worker porter who keeps item identity at its physical position',()=>{const{s,h,worker}=setup('human_gondor');expect(heavyCarryReason(s,'p1','plate',h.id)).toMatch(/porter/);carryHeavy(s,'p1','plate',worker.id);worker.x++;dropHeavy(s,'p1','plate');expect(s.items.plate).toMatchObject({bearer:null,x:worker.x,y:worker.y});expect(worker.inventory).toEqual([]);expect(heavyLoad(s,worker)).toBe(0);expect(s.items.plate.durability).toBe(100);});
it('rejects duplicate heavy load, remote pickup and invalid carried checkpoint flags',()=>{const{s,h}=setup();s.items.second={...s.items.plate,id:'second'};carryHeavy(s,'p1','plate',h.id);expect(heavyCarryReason(s,'p1','second',h.id)).toMatch(/one/);(s.items.plate as HeavyItem).heavy=undefined;expect(()=>validateHeavyEquipment(s)).toThrow();});

it('carrying limits walking and death preserves the physical piece at the actual final location',()=>{const{s,h}=setup();carryHeavy(s,'p1','plate',h.id);expect(heavyMovementLimit(s,h)).toBe(1);h.x++;h.alive=false;settleHeavyEquipment(s);expect(s.items.plate).toMatchObject({bearer:null,x:h.x,y:h.y});expect((s.items.plate as HeavyItem).carried).toBeUndefined();expect(h.inventory).toEqual([]);expect(Object.keys(s.items)).toEqual(['plate']);});
it('an equipped wearable is not a rolled cargo load and remote pickup is refused',()=>{const{s,h}=setup();s.items.plate.x=h.x+3;expect(heavyCarryReason(s,'p1','plate',h.id)).toMatch(/Adjacent/);s.items.plate.x=h.x;carryHeavy(s,'p1','plate',h.id);delete(s.items.plate as HeavyItem).carried;expect(heavyLoad(s,h)).toBe(0);expect(heavySprintReason(s,h)).toBe('');expect(heavyMovementLimit(s,h)).toBe(Infinity);expect(()=>validateHeavyEquipment(s)).not.toThrow();});
it('ordinary carry then real travel fits the same item at the bearer position exactly once',()=>{
 const fixture=setup();let s=fixture.s;const id=fixture.worker.id,armor=s.units[id].armor,origin={x:s.items.plate.x,y:s.items.plate.y};s.players.p2.ai=false;s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};s.infrastructureSites={};
 const issue=(action:Action)=>submit(s,{id:`carried-fit:${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});
 const commit=(action:Action)=>{const r=issue(action);expect(r.ok,r.reason).toBe(true);s=resolveWeek(r.state);};
 commit({kind:'carry-heavy',item:'plate',carrier:id});commit({kind:'move',unit:id,x:origin.x,y:origin.y+1});commit({kind:'move',unit:id,x:origin.x,y:origin.y+2});
 expect(s.items.plate.y).toBe(origin.y);expect(s.units[id].armor).toBe(armor);
 const fit=issue({kind:'equip',unit:id,item:'plate'});expect(fit.ok,fit.reason).toBe(true);const fitted=preview(fit.state,'p1');expect(fitted.units[id].armor).toBe(armor+4);expect(fitted.units[id].inventory).toEqual(['plate']);expect(fitted.items.plate.carried).toBeUndefined();
 s=resolveWeek(fit.state);expect(issue({kind:'equip',unit:id,item:'plate'}).ok).toBe(false);
 s.items.remote={...s.items.plate,id:'remote',bearer:null,x:origin.x,y:origin.y};expect(issue({kind:'equip',unit:id,item:'remote'}).ok).toBe(false);
});
