import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {initializePrey,prepareHunting,resolveHunting,interruptHunting,validateHunting,type HuntingState} from '../src/simulation/hunting';
import type {Match,Pos} from '../src/simulation/types';
const path=(_s:Match,a:Pos,b:Pos)=>[a,b];
function fixture(){const s:HuntingState={...createMatch(['wolf_pack','human_gondor'],81),preySites:{},huntingJobs:{},huntingReports:{}};s.map.terrain.fill('meadow');const u=s.units['p1:company:0'];Object.assign(u,{x:10,y:10,move:8});initializePrey(s,[{id:'prey:p1',x:11,y:10,habitat:'meadow',initial:12,remaining:12,harvested:0,yieldP:4}]);return{s,u};}
it('ordinary hunting consumes finite authored inventory exactly once and cannot manufacture replacement prey',()=>{const{s,u}=fixture(),before=s.players.p1.stock.P;prepareHunting(s,'p1',{mode:'hunt',unit:u.id,prey:'prey:p1',amount:2,route:[{x:10,y:10},{x:11,y:10}]},path);resolveHunting(s,path);expect(s.preySites['prey:p1'].remaining).toBe(10);expect(s.players.p1.stock.P).toBe(before+8);resolveHunting(s,path);expect(s.preySites['prey:p1'].remaining).toBe(10);expect(()=>initializePrey(s,[s.preySites['prey:p1']])).toThrow();validateHunting(s);});
it('a blocked hunt grants no provisions and an unknown site is unavailable',()=>{const{s,u}=fixture(),before=s.players.p1.stock.P;expect(()=>prepareHunting(s,'p1',{mode:'hunt',unit:u.id,prey:'unknown',amount:2,route:[u,{x:11,y:10}]},path)).toThrow();prepareHunting(s,'p1',{mode:'hunt',unit:u.id,prey:'prey:p1',amount:2,route:[{x:10,y:10},{x:11,y:10}]},path);resolveHunting(s,()=>null);expect(s.players.p1.stock.P).toBe(before);expect(s.preySites['prey:p1'].remaining).toBe(12);});
it('Wolf survey spends source costs but produces only dated private evidence after physical movement',()=>{const{s,u}=fixture(),p=s.players.p1;p.hero.status='living';p.hero.readiness=6;const h={...structuredClone(u),id:p.hero.id,kind:'hero' as const};s.units[h.id]=h;const before=p.stock.P;prepareHunting(s,'p1',{mode:'survey',unit:h.id,route:[{x:10,y:10},{x:11,y:10}]},path);expect(p.stock.P).toBe(before-2);expect(p.hero.readiness).toBe(3);expect(Object.values(s.huntingReports)).toHaveLength(0);resolveHunting(s,path);expect(h.x).toBe(11);expect(Object.values(s.huntingReports)[0].prey[0].remaining).toBe(12);expect(s.preySites['prey:p1'].remaining).toBe(12);expect(()=>validateHunting(s,'p2')).toThrow();});
it('checkpoint conservation rejects invented replenishment',()=>{const{s}=fixture();s.preySites['prey:p1'].remaining++;expect(()=>validateHunting(s)).toThrow();});
it('injury interrupts physical survey without refund or fabricated report',()=>{const{s,u}=fixture(),p=s.players.p1;p.hero.status='living';p.hero.readiness=6;const h={...structuredClone(u),id:p.hero.id,kind:'hero' as const};s.units[h.id]=h;prepareHunting(s,'p1',{mode:'survey',unit:h.id,route:[{x:10,y:10},{x:11,y:10}]},path);interruptHunting(s,h.id,0);expect(Object.values(s.huntingJobs)).toHaveLength(1);interruptHunting(s,h.id,1);resolveHunting(s,path);expect(Object.values(s.huntingReports)).toHaveLength(0);expect(h.x).toBe(10);expect(p.hero.readiness).toBe(3);});
it('invalid authoring is atomic and cannot partially replenish the world',()=>{const{s}=fixture();expect(()=>initializePrey(s,[{id:'invalid',x:12,y:10,habitat:'meadow',initial:2,remaining:3,harvested:0,yieldP:4}])).toThrow();expect(s.preySites.invalid).toBeUndefined();});
it('ordinary hunting can harvest remaining prey without leaving its current site, while survey still requires travel',()=>{const{s,u}=fixture();u.x=11;prepareHunting(s,'p1',{mode:'hunt',unit:u.id,prey:'prey:p1',amount:2,route:[{x:11,y:10}]},path);resolveHunting(s,path);expect(s.preySites['prey:p1'].remaining).toBe(10);});
