import {expect,it} from 'vitest';
import {createMatch,submit,preview,resolveWeek} from '../src/simulation/engine';
import {parseMatch} from '../src/simulation/schema';
import {guestSnapshot} from '../src/network/protocol';
import {recordRecoverableInjury,startCare} from '../src/simulation/recovery';
import type {Match,Action} from '../src/simulation/types';
const order=(s:Match,a:Action)=>submit(s,{id:`support-${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action:a});
function hero(s:Match){const p=s.players.p1;p.hero.status='living';s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero',x:4,y:4};}
it('inspection changes only upcoming actual worksite wear; save and private views keep scoped evidence',()=>{let s=createMatch(['aule','human_gondor'],1);hero(s);const core=s.facilities['p1:core'],before=core.hp;const r=order(s,{kind:'inspect-worksite',facility:core.id});expect(r.ok,r.reason).toBe(true);expect(preview(r.state,'p1').players.p1.operations).toBe(2);s=resolveWeek(r.state);expect(s.facilities[core.id].hp).toBe(before-2);expect(s.facilities['p2:core'].hp).toBe(s.facilities['p2:core'].maxHp-4);expect(()=>parseMatch(s)).not.toThrow();expect(()=>parseMatch(guestSnapshot(s,'p2'),'p2')).not.toThrow();expect(guestSnapshot(s,'p2').routineWorksiteWear[core.id]).toBeUndefined();});
it('paid care evacuation command keeps existing injury and consumes ordinary operation and travel provisions',()=>{const s=createMatch(['este','human_gondor'],1);hero(s);const u=s.units['p1:company:0'];u.x=4;u.y=5;s.facilities.a={...s.facilities['p1:core'],id:'a',kind:'refuge',x:4,y:5};s.facilities.b={...s.facilities.a,id:'b',x:5,y:5};recordRecoverableInjury(s,u,Math.ceil(u.maxHp/4));startCare(s,'p1',{unit:u.id,facility:'a'},()=>true);const q=Object.values(s.recoveries)[0];q.remaining=1;const before=s.players.p1.stock.P;const r=order(s,{kind:'evacuate-care',care:q.id,destination:'b',route:[{x:4,y:5},{x:5,y:5}]});expect(r.ok,r.reason).toBe(true);const view=preview(r.state,'p1');expect(view.players.p1.operations).toBe(2);expect(view.players.p1.stock.P).toBe(before-2);expect(view.recoveries[q.id]).toMatchObject({injury:q.injury,remaining:1,facility:'b',lastProgress:s.turn});expect(()=>parseMatch(view)).not.toThrow();});
it('real local knowledge command creates dated private record and strict save rejects forged remote evidence',()=>{let s=createMatch(['ulmo','human_gondor'],1);hero(s);s.map.terrain[4*s.map.width+5]='water';const r=order(s,{kind:'inspect-local',point:{x:5,y:4}});expect(r.ok,r.reason).toBe(true);s=preview(r.state,'p1');expect(s.localKnowledgeReports.p1.detail).toMatchObject({kind:'water',flow:'unknown',draft:'unknown'});expect(()=>parseMatch(s)).not.toThrow();const view=guestSnapshot(s,'p2');expect(view.localKnowledgeReports).toEqual({});expect(()=>parseMatch(view,'p2')).not.toThrow();s.localKnowledgeReports.p1.revision=s.revision+1;expect(()=>parseMatch(s)).toThrow();});
