import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {inspectLocalKnowledge,recordLocalKnowledgeMovement,validateLocalKnowledge,pruneLocalKnowledge,type KnowledgeState} from '../src/simulation/local-knowledge';
function setup(profile:string){const s=createMatch([profile,'human_rohan'],7)as KnowledgeState,p=s.players.p1,f=s.facilities['p1:core'],u=s.units['p1:company:0'];s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',x:f.x,y:f.y,inventory:[],effects:[]};p.hero.status='living';return {s,h:s.units[p.hero.id],f,u};}
const checks={visible:()=>true,connected:()=>true};
it('Ulmo observes existing local water hazards only and keeps unknown flow unknown',()=>{const{s,h}=setup('ulmo'),point={x:h.x+1,y:h.y};s.map.terrain[point.y*s.map.width+point.x]='water';const before=structuredClone(s.players.p1.stock);const q=inspectLocalKnowledge(s,'p1',point,checks);expect(q.detail).toMatchObject({kind:'water',flow:'unknown',shallow:false});expect(s.players.p1.stock).toEqual(before);expect(()=>inspectLocalKnowledge(s,'p1',{x:h.x+9,y:h.y},checks)).toThrow(/local/);});
it('Osse inspection is one local channel per week and old report remains dated after hazards change',()=>{const{s,h}=setup('osse'),point={x:h.x+1,y:h.y};s.map.terrain[point.y*s.map.width+point.x]='water';s.shallowWater[`${point.x},${point.y}`]=true;s.seaHazards[`${point.x},${point.y}`]={wave:1,fog:false,handling:0};const q=inspectLocalKnowledge(s,'p1',point,checks);expect(q.detail).toMatchObject({kind:'water',draft:'shallow',wave:1});s.seaHazards[`${point.x},${point.y}`].wave=3;expect(q.detail).toMatchObject({wave:1});expect(()=>inspectLocalKnowledge(s,'p1',point,checks)).toThrow(/week/);});
it('Vana reports cultivated recovery conditions without growing crops or minting supplies',()=>{const{s,h,f}=setup('vana');f.kind='crop-plot';const before=structuredClone(s);const q=inspectLocalKnowledge(s,'p1',h,checks);expect(q.detail).toMatchObject({kind:'plant',viable:false,recoverable:true});expect(s.facilities).toEqual(before.facilities);expect(s.players).toEqual(before.players);});
it('wolf encounters distinguish own recent pack traces without exposing identity or remote route',()=>{const{s,h,u}=setup('wolf_pack');u.kind='beast';u.x=h.x;u.y=h.y;recordLocalKnowledgeMovement(s,u,[{x:h.x-1,y:h.y},h]);const q=inspectLocalKnowledge(s,'p1',h,checks);expect(q.detail).toEqual({kind:'scent',ownPack:true});expect(JSON.stringify(q)).not.toContain(u.id);s.turn+=2;pruneLocalKnowledge(s);expect(()=>inspectLocalKnowledge(s,'p1',h,checks)).toThrow(/trace/);});
it('Ent root memory observes actual heavy passage in one connected grove and never identity',()=>{const{s,h,u}=setup('ent_grove');s.vegetation.grove={id:'grove',x:h.x,y:h.y,mature:true,altered:false};u.loadClass='large';u.x=h.x;u.y=h.y;recordLocalKnowledgeMovement(s,u,[{x:h.x-1,y:h.y},h]);expect(()=>inspectLocalKnowledge(s,'p1',h,{...checks,connected:()=>false})).toThrow(/connected/);const q=inspectLocalKnowledge(s,'p1',h,checks);expect(q.detail).toEqual({kind:'grove',disturbance:'heavy-passage',direction:'east'});expect(()=>validateLocalKnowledge(s,'p2')).toThrow();expect(()=>validateLocalKnowledge(structuredClone(s))).not.toThrow();});
it('occupied lair records anonymous actual silk contact and destruction stops later reports',()=>{
 const{s,h,f,u}=setup('spider_brood');f.workers=1;s.facilities.a={...f,id:'a',kind:'crossing-anchor',x:f.x+1};s.facilities.b={...f,id:'b',kind:'crossing-anchor',x:f.x+3};
 s.crossings.web={id:'web',owner:'p1',kind:'silk',from:'a',to:'b',crew:u.id,tiles:[{x:f.x+1,y:f.y},{x:f.x+2,y:f.y},{x:f.x+3,y:f.y}],hp:60,maxHp:60,phase:'ready',started:s.turn,lastProgress:s.turn};u.x=f.x+2;u.y=f.y;
 recordLocalKnowledgeMovement(s,u,[{x:u.x,y:u.y-1},u]);const q=s.localKnowledgeReports!.p1;expect(q.detail).toEqual({kind:'tremor',direction:'south',eventTurn:s.turn,eventRevision:s.revision});expect(q.point).toEqual({x:f.x,y:f.y});expect(JSON.stringify(q)).not.toContain(u.id);
 s.crossings.web.hp=0;s.revision++;recordLocalKnowledgeMovement(s,u,[{x:u.x-1,y:u.y},u]);expect(s.localKnowledgeReports!.p1).toEqual(q);
 expect(h.alive).toBe(true);
});
it('unknown local trace never gains foreign identity, and hidden evidence never reaches guest validation',()=>{
 const{s,h}=setup('wolf_pack'),other=s.units['p2:company:0'];other.x=h.x;other.y=h.y;recordLocalKnowledgeMovement(s,other,[{x:h.x-1,y:h.y},h]);const q=inspectLocalKnowledge(s,'p1',h,checks);expect(q.detail).toEqual({kind:'scent',ownPack:false});expect(JSON.stringify(q)).not.toContain('p2');
 const guest=structuredClone(s);guest.localGroundTraces={};guest.groveDisturbances={};expect(()=>validateLocalKnowledge(guest,'p1')).not.toThrow();guest.localKnowledgeReports!.p1.revision++;expect(()=>validateLocalKnowledge(guest,'p1')).toThrow();
});
it('local scent preserves the actual trace phase expiry and erased status',()=>{
 const{s,h}=setup('wolf_pack'),u=s.units['p2:company:0'],route=[{x:h.x-1,y:h.y},{x:h.x,y:h.y}];u.x=h.x;u.y=h.y;s.movementTraces.actual={id:'actual',owner:u.owner,unit:u.id,route,turn:s.turn,revision:s.revision,expiresRevision:s.revision+1,erased:false};recordLocalKnowledgeMovement(s,u,route);expect(s.localGroundTraces![`${h.x},${h.y}`].expiresRevision).toBe(s.revision+1);s.revision+=2;pruneLocalKnowledge(s);expect(()=>inspectLocalKnowledge(s,'p1',h,checks)).toThrow(/trace/);
 s.movementTraces.actual.revision=s.revision;s.movementTraces.actual.expiresRevision=s.revision+2;s.movementTraces.actual.erased=true;recordLocalKnowledgeMovement(s,u,route);expect(s.localGroundTraces![`${h.x},${h.y}`]).toBeUndefined();
});
