import {expect,it} from 'vitest';
import {createMatch,submit,resolveWeek} from '../src/simulation/engine';
import {spawnVessel} from '../src/simulation/naval';
import type {Match,Action} from '../src/simulation/types';
function fixture(profile:string){const s=createMatch([profile,'human_rohan'],18);s.map.terrain.fill('meadow');s.seaHazards={};s.shallowWater={};s.infrastructureSites={};s.map.terrain[5*s.map.width+4]='water';s.map.terrain[5*s.map.width+5]='water';const f=s.facilities['p1:core'];Object.assign(f,{kind:'harbor',x:4,y:4});const crew=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;Object.assign(crew,{x:4,y:4});const p=s.players.p1;p.stock={P:500,M:500,K:500,E:500};p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(crew),id:p.hero.id,kind:'hero'};const v=spawnVessel(s,'p1',f.id,crew.id,{x:4,y:5});v.hp=40;return {s,v};}
function order(s:Match,action:Action){const r=submit(s,{id:`temporal:${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});expect(r.ok,r.reason).toBe(true);return r.state;}
it('Uinen two-phase calm affects an actual queued voyage before expiring',()=>{const fixtureState=fixture('uinen'),v=fixtureState.v;let s=fixtureState.s;s.seaHazards['5,5']={wave:2,fog:false,handling:0};s=order(s,{kind:'sail',ship:v.id,route:[{x:4,y:5},{x:5,y:5}]});s=order(s,{kind:'naval-power',power:'field',ship:v.id});const turn=s.turn;for(let i=0;i<4&&s.turn===turn;i++)s=resolveWeek(s);expect(s.vessels[v.id].x).toBe(5);expect(s.vessels[v.id].hp).toBe(38);});
it('Osse two-phase surf affects real coastal travel rather than expiring before ships progress',()=>{const fixtureState=fixture('osse'),v=fixtureState.v;let s=fixtureState.s;s=order(s,{kind:'sail',ship:v.id,route:[{x:4,y:5},{x:5,y:5}]});s=order(s,{kind:'naval-power',power:'field',x:5,y:5});const turn=s.turn;for(let i=0;i<4&&s.turn===turn;i++)s=resolveWeek(s);expect(s.vessels[v.id].x).toBe(5);expect(s.vessels[v.id].hp).toBe(38);});
it('phase sailing advances at most one weekly movement budget and charges vessel upkeep once',()=>{const fixtureState=fixture('uinen'),v=fixtureState.v;let s=fixtureState.s;for(let x=4;x<=10;x++)s.map.terrain[5*s.map.width+x]='water';s=order(s,{kind:'sail',ship:v.id,route:Array.from({length:7},(_,i)=>({x:4+i,y:5}))});s=order(s,{kind:'naval-power',power:'field',ship:v.id});s=resolveWeek(s);expect(s.vessels[v.id].index).toBe(3);expect(s.players.p1.stock).toMatchObject({P:498,M:499});const stock=structuredClone(s.players.p1.stock);s=resolveWeek(s);expect(s.players.p1.stock).toEqual(stock);expect(s.vessels[v.id].index).toBe(3);const upkeep=Object.values(s.units).filter(u=>u.owner==='p1'&&u.alive&&u.active).reduce((sum,u)=>sum+u.upkeep.M,0);s=resolveWeek(s);expect(s.vessels[v.id].index).toBe(3);expect(s.players.p1.stock.M).toBe(stock.M-upkeep);});
it('sandbox exposes sparse deterministic real coastal hazards without making every water tile hazardous',()=>{const a=createMatch(['uinen','elf_falmari'],22),b=createMatch(['uinen','elf_falmari'],22);expect(a.seaHazards).toEqual(b.seaHazards);const hazards=Object.entries(a.seaHazards);expect(hazards.length).toBeGreaterThan(0);expect(hazards.length).toBeLessThan(a.map.terrain.filter(t=>t==='water').length);expect(hazards.some(([,h])=>h.wave>0)).toBe(true);expect(hazards.some(([,h])=>h.fog)).toBe(true);for(const[key]of hazards){const[x,y]=key.split(',').map(Number);expect(a.map.terrain[y*a.map.width+x]).toBe('water');expect(a.map.terrain[y*a.map.width+x-1]).not.toBe('water');}});
