import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {spawnVessel,navalOrderReason,startNavalOrder,progressVessels,validateVesselState,vesselCapacity} from '../src/simulation/naval';
import {navalProductionKeys,navalProduction} from '../src/content/naval-production';
import {stocks} from '../src/simulation/types';
function setup(profile='human_numenor',key='expedition-ship'){const s=createMatch([profile,'human_rohan'],21),p=s.players.p1,c=s.facilities['p1:core'],w=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;p.stock=stocks(500,500,500,500);s.facilities.port={...c,id:'port',kind:'harbor',workers:1,x:5,y:5};w.x=5;w.y=5;for(let x=6;x<=11;x++){s.map.terrain[5*s.map.width+x]='water';s.waterChannels[`${x},5`]={x,y:5,depth:2,flow:'still'};}const v=spawnVessel(s,'p1','port',w.id,{x:6,y:5},key);return{s,p,v};}
it('four source-qualified named hull classes require their exact owners and retain finite production recipes',()=>{const owners=['elf_falmari','human_numenor','osse','uinen'];for(let i=0;i<4;i++){const q=navalProduction(owners[i],navalProductionKeys[i])!;expect(q.recipe.kind).toBe('vessel');expect(q.recipe.provisional).toBe(true);expect(q.recipe.turns).toBeGreaterThan(0);expect(navalProduction('human_rohan',navalProductionKeys[i])).toBeUndefined();}});
it('an Expedition Ship actually carries40 cargo and pays its larger crew upkeep; forgery fails',()=>{const{s,p,v}=setup();expect(vesselCapacity(s,v)).toBe(40);expect(navalOrderReason(s,'p1',{kind:'load-cargo',ship:v.id,cargo:stocks(40)})).toBe('');startNavalOrder(s,'p1',{kind:'load-cargo',ship:v.id,cargo:stocks(40)});const before={...p.stock};progressVessels(s);expect(p.stock.P).toBe(before.P-3);expect(p.stock.M).toBe(before.M-2);expect(v.cargo.P).toBe(40);expect(()=>validateVesselState(s,v)).not.toThrow();v.maxHp=80;expect(()=>validateVesselState(s,v)).toThrow();});
it('deep expedition draft is blocked by a real shallow channel while a shallow skiff can sail it',()=>{const a=setup();a.s.waterChannels['7,5'].depth=1;expect(navalOrderReason(a.s,'p1',{kind:'sail',ship:a.v.id,route:[{x:6,y:5},{x:7,y:5}]})).toMatch(/draft/i);const b=setup('osse','storm-skiff');b.s.waterChannels['7,5'].depth=1;expect(navalOrderReason(b.s,'p1',{kind:'sail',ship:b.v.id,route:[{x:6,y:5},{x:7,y:5}]})).toBe('');});
it('storm skiff construction resists actual wave hull damage but does not cancel cargo loss',()=>{const{s,v}=setup('osse','storm-skiff');v.cargo=stocks(10);s.seaHazards['7,5']={wave:1,fog:false,handling:0};startNavalOrder(s,'p1',{kind:'sail',ship:v.id,route:[{x:6,y:5},{x:7,y:5}]});progressVessels(s);expect(v.hp).toBe(v.maxHp);expect(v.cargo.P).toBe(6);});
it('protected fishing craft reduces actual ordinary storm cargo loss without generating fish or immunity',()=>{const{s,v}=setup('uinen','protected-fishing-craft');v.cargo=stocks(10);s.seaHazards['7,5']={wave:1,fog:false,handling:0};startNavalOrder(s,'p1',{kind:'sail',ship:v.id,route:[{x:6,y:5},{x:7,y:5}]});progressVessels(s);expect(v.cargo.P).toBe(8);expect(v.hp).toBe(v.maxHp-1);});
it('only an actual embarked supplied Current Guide removes one handling delay',()=>{const{s,v}=setup('uinen','protected-fishing-craft'),u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='company')!;Object.assign(u,{military:'current-guides',x:v.x,y:v.y});s.seaHazards[`${v.x},${v.y}`]={wave:0,fog:false,handling:2};startNavalOrder(s,'p1',{kind:'load-cargo',ship:v.id,cargo:stocks(1)});expect(v.handlingRemaining).toBe(3);v.phase='idle';delete v.handling;v.passenger=u.id;startNavalOrder(s,'p1',{kind:'load-cargo',ship:v.id,cargo:stocks(1)});expect(v.handlingRemaining).toBe(2);u.supplied=false;v.phase='idle';delete v.handling;startNavalOrder(s,'p1',{kind:'load-cargo',ship:v.id,cargo:stocks(1)});expect(v.handlingRemaining).toBe(3);});

import {submit,preview,resolveWeek} from '../src/simulation/engine';
import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';
import type {Match,Action} from '../src/simulation/types';
const order=(s:Match,action:Action)=>submit(s,{id:`named-hull:${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});
it('all four named hulls complete normal paid queues with existing reserved crew and save their actual class',()=>{const owners=['elf_falmari','human_numenor','osse','uinen'];for(let n=0;n<4;n++){const q=navalProduction(owners[n],navalProductionKeys[n])!;let s=createMatch([owners[n],'human_rohan'],71);s.players.p1.stock=stocks(500,500,500,500);s.players.p1.sources=[...new Set([...s.players.p1.sources,...q.recipe.access])];s.facilities.port={...s.facilities['p1:core'],id:'port',kind:'harbor',workers:1,x:4,y:4};s.map.terrain[5*s.map.width+4]='water';const w=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;w.x=4;w.y=4;const queued=order(s,{kind:'produce',facility:'port',recipe:q.recipe.id});expect(queued.ok,queued.reason).toBe(true);const reserved=preview(queued.state,'p1');expect(reserved.facilities.port.job?.crew).toBe(w.id);expect(reserved.players.p1.stock.M).toBe(500-q.recipe.cost.M);expect(order(queued.state,{kind:'move',unit:w.id,x:3,y:4}).ok).toBe(false);s=queued.state;for(let i=0;i<q.recipe.turns;i++)s=resolveWeek(s);const v=Object.values(s.vessels)[0];expect(v).toMatchObject({hullClass:q.recipe.id,name:q.recipe.name,crew:w.id,maxHp:q.hull.hp,move:q.hull.move});expect(decodeCheckpoint(encodeCheckpoint(s)).state.vessels[v.id].hullClass).toBe(q.recipe.id);}});

import {logisticsReason} from '../src/simulation/logistics-support';
it('physical redistribution respects each named hull capacity instead of a global twenty-stock limit',()=>{const{s,v}=setup();const w={...structuredClone(s.units[v.crew]),id:'second-crew',x:5,y:5};s.units[w.id]=w;const second=spawnVessel(s,'p1','port',w.id,{x:6,y:5},'expedition-ship');v.cargo=stocks(40);const request={mode:'redistribute' as const,method:'ordinary' as const,harbor:'port',loads:[{ship:v.id,cargo:stocks(),passenger:null},{ship:second.id,cargo:stocks(40),passenger:null}]};expect(logisticsReason(s,'p1',request,()=>[])).toBe('');request.loads[1].cargo.P=41;v.cargo.P=41;expect(logisticsReason(s,'p1',request,()=>[])).toMatch(/capacity/);});
it('actual worn paid sea ward consumes durability only against remaining environmental hull damage',async()=>{const{s,v}=setup(),u=s.units[v.crew],{finalProduction}=await import('../src/content/final-production'),q=finalProduction('human_numenor','sea-ward')!;if(q.kind!=='item')throw Error('gear');s.items.ward={id:'ward',name:q.recipe.name,owner:'p1',bearer:u.id,x:u.x,y:u.y,crafted:true,...q.item,finalProduct:'sea-ward'};u.inventory.push('ward');s.seaHazards['7,5']={wave:1,fog:false,handling:0};startNavalOrder(s,'p1',{kind:'sail',ship:v.id,route:[{x:6,y:5},{x:7,y:5}]});progressVessels(s);expect(v.hp).toBe(v.maxHp-1);expect(s.items.ward.durability).toBe(99);});
