import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {advanceNightRegions,initializeNight} from '../src/simulation/night-work';
import {trainScout,finishScoutTraining,startNightPatrol,advanceNightPatrols,recordNightMovement,publishNightReports,type NightPatrolState} from '../src/simulation/night-patrol';
it('ordinary trained scout physically patrols and publishes only actual dated local crossings',()=>{
 const s=createMatch(['human_gondor','human_rohan'],1) as NightPatrolState;Object.assign(s,{nightRegions:{},scoutCredentials:{},nightPatrols:{},nightReports:{},personalNightSurveys:{},nightBearingUses:{}});initializeNight(s);const u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='company')!;u.x=3;u.y=3;u.move=5;s.players.p1.stock.P=100;s.players.p1.stock.K=100;trainScout(s,'p1',u.id);s.turn++;finishScoutTraining(s);const route=[{x:3,y:3},{x:3,y:2}];const id=startNightPatrol(s,'p1',{unit:u.id,route,method:'ordinary'},()=>true,()=>2);advanceNightPatrols(s,()=>true,()=>2);expect(u.y).toBe(3);s.revision++;advanceNightPatrols(s,()=>true,()=>2);expect(u.y).toBe(2);const enemy=Object.values(s.units).find(v=>v.owner==='p2'&&v.kind==='company')!;enemy.x=3;enemy.y=2;recordNightMovement(s,enemy,[{x:2,y:2},{x:3,y:2}]);expect(Object.keys(s.nightReports)).toHaveLength(0);s.turn++;s.revision++;publishNightReports(s);const report=Object.values(s.nightReports)[0];expect(report).toMatchObject({owner:'p1',patrol:id,verified:true});expect(report.observations).toHaveLength(1);expect(JSON.stringify(report)).not.toContain(enemy.id);
});
it('Night Bearings needs normal scout training and an actually completed personal survey',()=>{
 const s=createMatch(['tilion','human_gondor'],7) as NightPatrolState;Object.assign(s,{nightRegions:{},scoutCredentials:{},nightPatrols:{},nightReports:{},personalNightSurveys:{},nightBearingUses:{}});initializeNight(s);const p=s.players.p1,u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='company')!;u.x=3;u.y=3;u.move=5;p.stock.P=200;p.stock.K=200;s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',move:5};p.hero.status='living';p.hero.readiness=6;trainScout(s,'p1',u.id);for(let i=0;i<3;i++){s.turn++;advanceNightRegions(s);finishScoutTraining(s);}const a={unit:p.hero.id,companion:u.id,method:'moon' as const,route:[{x:3,y:3},{x:3,y:2}]};const first=startNightPatrol(s,'p1',a,()=>true,()=>1);expect(s.nightPatrols[first].delay).toBe(1);advanceNightPatrols(s,()=>true,()=>1);s.revision++;advanceNightPatrols(s,()=>true,()=>1);expect(s.units[p.hero.id].y).toBe(2);expect(u.y).toBe(2);for(let i=0;i<3;i++){s.turn++;s.revision++;advanceNightRegions(s);publishNightReports(s);}const second=startNightPatrol(s,'p1',{...a,route:[{x:3,y:2},{x:3,y:3}]},()=>true,()=>1);expect(s.nightPatrols[second].delay).toBe(0);advanceNightPatrols(s,()=>true,()=>1);expect(u.y).toBe(3);expect(s.nightBearingUses.p1).toBe(s.turn);
});
it('a blocked patrol creates no personal survey and unvisited remote crossings produce no report facts',()=>{
 const s=createMatch(['tilion','human_gondor'],2) as NightPatrolState;Object.assign(s,{nightRegions:{},scoutCredentials:{},nightPatrols:{},nightReports:{},personalNightSurveys:{},nightBearingUses:{}});initializeNight(s);const p=s.players.p1,u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='company')!;s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',x:3,y:3};p.hero.status='living';p.hero.readiness=6;startNightPatrol(s,'p1',{unit:p.hero.id,method:'moon',route:[{x:3,y:3},{x:3,y:2}]},()=>true,()=>1);advanceNightPatrols(s,()=>true,()=>1);s.revision++;advanceNightPatrols(s,()=>false,()=>1);expect(Object.keys(s.personalNightSurveys)).toHaveLength(0);const enemy=Object.values(s.units).find(u=>u.owner==='p2')!;recordNightMovement(s,enemy,[{x:20,y:20},{x:21,y:20}]);s.turn++;publishNightReports(s);expect(Object.values(s.nightReports)[0].observations).toEqual([]);
});
