import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {createBasinScenario} from '../src/content/scenario';
import {initializeWaterChannels,draftRouteReason,startLogging,progressLogging,validateOrdinaryEnvironment,type OrdinaryEnvironmentState} from '../src/simulation/ordinary-environment';
import {inspectLocalKnowledge} from '../src/simulation/local-knowledge';
import {stocks} from '../src/simulation/types';
it('authored channel flow follows actual connected water and shallow depth blocks a laden ordinary hull',()=>{
 const s=createMatch(['osse','human_rohan'],4)as OrdinaryEnvironmentState;initializeWaterChannels(s);const channel=Object.values(s.waterChannels!).find(q=>q.depth===1)!;expect(channel).toBeDefined();const scenario=createBasinScenario(s.map.width);expect(scenario.waterChannels[`${channel.x},${channel.y}`]).toEqual(channel);
 const v={cargo:stocks(20),passenger:null};expect(draftRouteReason(s,v,[channel])).toMatch(/draft/);expect(draftRouteReason(s,{cargo:stocks(),passenger:null},[channel])).toBe('');for(const q of Object.values(s.waterChannels!))if(q.flow==='south')expect(s.map.terrain[(q.y+1)*s.map.width+q.x]).toBe('water');expect(()=>validateOrdinaryEnvironment(s)).not.toThrow();
});
function fixture(){const s=createMatch(['ent_grove','human_rohan'],4)as OrdinaryEnvironmentState,p=s.players.p1,f=s.facilities['p1:core'],u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;u.x=f.x;u.y=f.y;p.stock=stocks(100,100,100,100);p.operations=3;s.vegetation.tree={id:'tree',x:u.x+1,y:u.y,mature:true,altered:false};s.map.terrain[u.y*s.map.width+u.x+1]='woodland';s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',effects:[],inventory:[]};p.hero.status='living';return{s,p,f,u};}
it('paid ordinary logging consumes one tree once, produces finite materials and actual Ent logging evidence',()=>{
 const{s,p,f,u}=fixture();const id=startLogging(s,'p1',u.id,'tree',f.id);expect(p.stock).toEqual(stocks(95,98,100,100));expect(p.operations).toBe(2);expect(()=>startLogging(s,'p1',u.id,'tree',f.id)).toThrow();progressLogging(s);expect(p.stock.M).toBe(108);expect(s.vegetation.tree).toMatchObject({mature:false,altered:true});expect(s.loggingJobs![id]).toBeUndefined();progressLogging(s);expect(p.stock.M).toBe(108);expect(()=>startLogging(s,'p1',u.id,'tree',f.id)).toThrow();const q=inspectLocalKnowledge(s,'p1',s.vegetation.tree,{visible:()=>true,connected:()=>true});expect(q.detail).toEqual({kind:'grove',disturbance:'logging',direction:'east'});expect(()=>validateOrdinaryEnvironment(s)).not.toThrow();
});
it('logging pauses on missing crew or worksite and never turns interruption into a resource refund',()=>{const{s,p,f,u}=fixture();startLogging(s,'p1',u.id,'tree',f.id);const paid=p.stock.M;u.x+=5;progressLogging(s);expect(p.stock.M).toBe(paid);u.x-=5;f.hp=0;progressLogging(s);expect(p.stock.M).toBe(paid);expect(Object.values(s.loggingJobs!)[0].status).toBe('lost');expect(s.vegetation.tree.mature).toBe(true);});
it('Osse reads authored safe draft/current flow and inspection does not change navigation or stock',()=>{const s=createMatch(['osse','human_rohan'],4)as OrdinaryEnvironmentState;initializeWaterChannels(s);const q=Object.values(s.waterChannels!).find(q=>q.flow==='south'&&q.depth===2)!,p=s.players.p1,base=s.units['p1:company:0'];s.units[p.hero.id]={...structuredClone(base),id:p.hero.id,kind:'hero',x:q.x-1,y:q.y,effects:[],inventory:[]};p.hero.status='living';const stock={...p.stock};const report=inspectLocalKnowledge(s,'p1',q,{visible:()=>true,connected:()=>true});expect(report.detail).toMatchObject({kind:'water',flow:'south',safeDraft:2,draft:'deep'});expect(p.stock).toEqual(stock);});
it('logging validator rejects duplicate reservations and prevents a consumed tree from being rematured',()=>{const{s,u,f}=fixture();const id=startLogging(s,'p1',u.id,'tree',f.id);s.loggingJobs!.copy={...s.loggingJobs![id],id:'copy'};expect(()=>validateOrdinaryEnvironment(s)).toThrow(/Duplicate/);delete s.loggingJobs!.copy;progressLogging(s);s.vegetation.tree.mature=true;expect(()=>validateOrdinaryEnvironment(s)).toThrow(/consumed/);});
