import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {recordPatrolMovement,inspectTrace,prepareStarwatch,localTraceSites,type PatrolState} from '../src/simulation/patrols';
function fixture(profile='vaire'){const s:PatrolState={...createMatch([profile,'human_rohan'],7),movementTraces:{},routeSurveys:{},patrolWatches:{},patrolReports:{}};s.map.terrain.fill('meadow');s.seaHazards={};s.shallowWater={};s.infrastructureSites={};const p=s.players.p1;p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero',x:4,y:4};return{s,p,h:s.units[p.hero.id]};}
it('Vaire inspects real local traces into a dated report without current identity or remote position',()=>{const{s,p}=fixture();const u=s.units['p2:company:0'];Object.assign(u,{x:5,y:4});recordPatrolMovement(s,u,[{x:4,y:4},{x:5,y:4}]);const id=inspectTrace(s,'p1',{x:4,y:4});expect(p.hero.readiness).toBe(4);const report=s.patrolReports[id];expect(report.points).toEqual([{x:4,y:4},{x:5,y:4}]);u.x=20;u.y=20;expect(JSON.stringify(report)).not.toContain(u.id);expect(report.points.at(-1)).toEqual({x:5,y:4});});
it('trace inspection rejects remote, erased and expired tracks without payment',()=>{const{s,p}=fixture();expect(()=>inspectTrace(s,'p1',{x:20,y:20})).toThrow();const u=s.units['p2:company:0'];Object.assign(u,{x:5,y:4});recordPatrolMovement(s,u,[{x:4,y:4},{x:5,y:4}]);for(const t of Object.values(s.movementTraces))t.erased=true;expect(()=>inspectTrace(s,'p1',{x:4,y:4})).toThrow();for(const t of Object.values(s.movementTraces))t.erased=false;s.turn+=2;expect(()=>inspectTrace(s,'p1',{x:4,y:4})).toThrow();expect(p.hero.readiness).toBe(6);});
it('Starwatch needs a real survey and emits only fixed exposed route crossings once per phase',()=>{const{s,p,h}=fixture('varda');Object.assign(h,{x:6,y:4});recordPatrolMovement(s,h,[{x:4,y:4},{x:5,y:4},{x:6,y:4}]);const survey=Object.keys(s.routeSurveys)[0];prepareStarwatch(s,'p1',survey,()=>true);expect(p.hero.readiness).toBe(3);const enemy=s.units['p2:company:0'];Object.assign(enemy,{x:5,y:5});recordPatrolMovement(s,enemy,[{x:5,y:3},{x:5,y:4},{x:5,y:5}]);expect(Object.values(s.patrolReports)[0].points).toEqual([{x:5,y:4}]);recordPatrolMovement(s,enemy,[{x:5,y:4},{x:5,y:5}]);expect(Object.keys(s.patrolReports)).toHaveLength(1);s.revision++;enemy.effects.push({kind:'concealed',value:1,source:'test',until:100});recordPatrolMovement(s,enemy,[{x:5,y:4},{x:5,y:5}]);expect(Object.keys(s.patrolReports)).toHaveLength(1);});
it('unvisited routes, flying units and malformed teleport segments cannot fabricate surveys or tracks',()=>{const{s,h}=fixture('varda');expect(()=>prepareStarwatch(s,'p1','invented',()=>true)).toThrow();h.flying=true;h.landed=false;recordPatrolMovement(s,h,[{x:3,y:4},{x:4,y:4}]);expect(Object.keys(s.movementTraces)).toHaveLength(0);h.flying=false;expect(()=>recordPatrolMovement(s,h,[{x:0,y:0},{x:4,y:4}])).toThrow();expect(Object.keys(s.routeSurveys)).toHaveLength(0);});

it('anonymous trace projection exposes only actual hero-local presence, never route or owner',()=>{const{s,h}=fixture();const u=s.units['p2:company:0'];Object.assign(u,{x:5,y:4});recordPatrolMovement(s,u,[{x:4,y:4},{x:5,y:4}]);expect(localTraceSites(s,'p1')).toEqual([{x:4,y:4}]);h.x=10;expect(localTraceSites(s,'p1')).toEqual([]);});

import {submit,resolveWeek,preview} from '../src/simulation/engine';
import {guestSnapshot} from '../src/network/protocol';
import {parseMatch} from '../src/simulation/schema';
import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';
import type {Match,Action} from '../src/simulation/types';
function issue(s:Match,seat:string,action:Action){return submit(s,{id:`patrol:${seat}:${s.nextSeq[seat]}`,seat,seq:s.nextSeq[seat],turn:s.turn,revision:s.revision,action});}
it('actual engine movement leaves inspectable local traces; guest preview gets no fabricated report or hidden route',()=>{let{s}=fixture();Object.assign(s.units['p2:company:0'],{x:4,y:4});const moved=issue(s,'p2',{kind:'move',unit:'p2:company:0',x:5,y:4});expect(moved.ok,moved.reason).toBe(true);s=resolveWeek(moved.state);expect(Object.keys(s.movementTraces)).toHaveLength(1);const view=guestSnapshot(s,'p1');expect(view.movementTraces).toEqual({});expect(view.routeSurveys).toEqual({});expect(view.traceContacts).toEqual([{x:4,y:4}]);expect(()=>parseMatch(view,'p1')).not.toThrow();expect(()=>parseMatch(view)).toThrow();const local=issue(view,'p1',{kind:'inspect-trace',x:4,y:4});expect(local.ok,local.reason).toBe(true);expect(preview(local.state,'p1').patrolReports).toEqual({});const real=issue(s,'p1',{kind:'inspect-trace',x:4,y:4});expect(real.ok,real.reason).toBe(true);s=resolveWeek(real.state);while(s.combatPhase)s=resolveWeek(s);expect(Object.keys(s.patrolReports)).toHaveLength(1);expect(decodeCheckpoint(encodeCheckpoint(s)).state.patrolReports).toEqual(s.patrolReports);expect(guestSnapshot(s,'p2').patrolReports).toEqual({});});
it('ordinary beast and construct formations can declare fallback and armed pursuit without gaining hero powers',()=>{for(const kind of ['beast','construct'] as const){const{s}=fixture('wolf_pack'),u=s.units['p1:company:0'],enemy=s.units['p2:company:0'];Object.assign(u,{kind,x:4,y:4,attack:10});Object.assign(enemy,{x:5,y:4});const fallback=issue(s,'p1',{kind:'declare-tactical',order:{kind:'fallback',unit:u.id,route:[{x:4,y:4},{x:4,y:5}]}});expect(fallback.ok,fallback.reason).toBe(true);const pursuit=issue(s,'p1',{kind:'declare-tactical',order:{kind:'pursuit',unit:u.id,target:enemy.id}});expect(pursuit.ok,pursuit.reason).toBe(true);expect(()=>parseMatch(preview(pursuit.state,'p1'))).not.toThrow();expect(issue(s,'p1',{kind:'tactical-power',mode:'shielded-withdrawal',unit:u.id}).ok).toBe(false);}});
