import {expect,it} from 'vitest';
import {createMatch,submit,resolveWeek} from '../src/simulation/engine';
import {abilityAvailability,resolveAbility} from '../src/simulation/abilities';
import {guestSnapshot} from '../src/network/protocol';
import {parseMatch} from '../src/simulation/schema';
import type {Action,Match} from '../src/simulation/types';
function setup(profile='tilion'){const s=createMatch([profile,'human_gondor'],81);s.map.terrain.fill('meadow');s.seaHazards={};s.shallowWater={};s.preySites={};s.infrastructureSites={};const p=s.players.p1;p.hero.status='living';p.hero.readiness=6;p.stock.E=50;s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero',x:9,y:8,attack:18};Object.assign(s.units['p1:company:0'],{x:10,y:10,hp:100,maxHp:100});Object.assign(s.units['p2:company:0'],{x:12,y:10,hp:100,maxHp:100,attack:10});for(const u of Object.values(s.units))if(u.id==='p2:company:1'){u.x=25;u.y=25;}return s;}
function issue(s:Match,seat:string,action:Action){const r=submit(s,{id:`${seat}-${s.revision}-${s.nextSeq[seat]}`,seat,seq:s.nextSeq[seat],turn:s.turn,revision:s.revision,action});expect(r.ok,r.reason).toBe(true);return r.state;}
it('normal prepared ranged attack pays one operation, exposes a response phase and deals one ordinary hit',()=>{let s=setup();s=issue(s,'p2',{kind:'declare-tactical',order:{kind:'ranged-attack',unit:'p2:company:0',target:'p1:company:0'}});s=resolveWeek(s);expect(s.units['p1:company:0'].hp).toBe(100);expect(s.players.p2.operations).toBe(2);expect(()=>parseMatch(s)).not.toThrow();s=resolveWeek(s);expect(s.units['p1:company:0'].hp).toBeLessThan(100);expect(Object.keys(s.tacticalOrders)).toHaveLength(0);});
it('Tilion interrupts a real declared attack on an ordinary ally, not a fabricated effect marker',()=>{let s=setup();const enemy=s.units['p2:company:0'];enemy.effects.push({kind:'prepared-attack',value:1,until:100,source:'attack:p1:company:0'});expect(abilityAvailability(s,'p1','field',enemy.id)).toMatch(/prepared/);s=issue(s,'p2',{kind:'declare-tactical',order:{kind:'ranged-attack',unit:enemy.id,target:'p1:company:0'}});s=resolveWeek(s);const guest=guestSnapshot(s,'p1');expect(abilityAvailability(guest,'p1','field',enemy.id)).toBe('');s=issue(s,'p1',{kind:'cast',power:'field',target:enemy.id});s=resolveWeek(s);expect(s.units['p1:company:0'].hp).toBe(100);expect(s.units[enemy.id].hp).toBeLessThan(100);expect(Object.keys(s.tacticalOrders)).toHaveLength(0);expect(()=>parseMatch(guest,'p1')).not.toThrow();expect(()=>parseMatch({...s,attackPreparations:guest.attackPreparations})).toThrow();});
it('Gandalf cancels only the selected actual ranged preparation in the burst, leaving a melee pursuit alone',()=>{let s=setup('istari_gandalf');s=issue(s,'p2',{kind:'declare-tactical',order:{kind:'ranged-attack',unit:'p2:company:0',target:'p1:company:0'}});s=resolveWeek(s);const enemy=s.units['p2:company:0'];resolveAbility(s,'p1','field',enemy.id,{damage:()=>{},event:()=>{}});expect(Object.keys(s.tacticalOrders)).toHaveLength(0);Object.assign(enemy,{x:11,y:10});s=issue(s,'p2',{kind:'declare-tactical',order:{kind:'pursuit',unit:enemy.id,target:'p1:company:0'}});s=resolveWeek(s);resolveAbility(s,'p1','field',enemy.id,{damage:()=>{},event:()=>{}});expect(Object.values(s.tacticalOrders).some(q=>q.kind==='pursuit')).toBe(true);});
it('solid cover or target closing to melee cancels a ranged preparation without refund',()=>{let s=setup();s=resolveWeek(issue(s,'p2',{kind:'declare-tactical',order:{kind:'ranged-attack',unit:'p2:company:0',target:'p1:company:0'}}));s.units['p1:company:0'].x=11;s=resolveWeek(s);expect(s.units['p1:company:0'].hp).toBe(100);expect(s.players.p2.operations).toBe(2);});
it('one-phase Gandalf warning resolves before a simultaneously declared ranged shot and cancels its real command',()=>{let s=setup('istari_gandalf');s=issue(s,'p1',{kind:'cast',power:'field',target:'p2:company:0'});s=issue(s,'p2',{kind:'declare-tactical',order:{kind:'ranged-attack',unit:'p2:company:0',target:'p1:company:0'}});s=resolveWeek(s);expect(s.units['p1:company:0'].hp).toBe(100);expect(s.warnings).toHaveLength(1);s=resolveWeek(s);expect(s.units['p1:company:0'].hp).toBe(100);expect(s.units['p2:company:0'].hp).toBeLessThan(100);expect(Object.keys(s.tacticalOrders)).toHaveLength(0);});
it('an unseen preparer does not leak target identity and a forged free ranged preparation is rejected',()=>{let s=setup();s=resolveWeek(issue(s,'p2',{kind:'declare-tactical',order:{kind:'ranged-attack',unit:'p2:company:0',target:'p1:company:0'}}));const forged=structuredClone(s);forged.players.p2.operations=3;expect(()=>parseMatch(forged)).toThrow(/Unpaid/);for(const u of Object.values(s.units))if(u.owner==='p1'){u.x=1;u.y=1;}expect(guestSnapshot(s,'p1').attackPreparations).toEqual([]);});
it('Orome recognizes and interrupts an actual ranged preparation with its normal physical charge',()=>{let s=setup('orome');Object.assign(s.units[s.players.p1.hero.id],{x:10,y:9,move:5,attack:18});s=resolveWeek(issue(s,'p2',{kind:'declare-tactical',order:{kind:'ranged-attack',unit:'p2:company:0',target:'p1:company:0'}}));const a:Action={kind:'charge-power',mode:'hunter-interception',target:'p2:company:0',members:[{unit:s.players.p1.hero.id,route:[{x:10,y:9},{x:11,y:9},{x:12,y:9}]}]};expect(submit(guestSnapshot(s,'p1'),{id:'orome-guest',seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action:a}).ok).toBe(true);s=issue(s,'p1',a);expect(Object.values(s.charges)).toHaveLength(0);s=resolveWeek(s);expect(s.players.p1.hero.readiness).toBe(4);expect(s.units['p1:company:0'].hp).toBe(100);expect(s.units['p2:company:0'].hp).toBeLessThan(100);expect(Object.values(s.tacticalOrders)).toHaveLength(0);});
