import {expect,it} from 'vitest';
import {createMatch,submit,resolveWeek,preview,kill} from '../src/simulation/engine';
import {parseMatch} from '../src/simulation/schema';
import {guestSnapshot} from '../src/network/protocol';
import {recipe} from '../src/content/catalog';
import type {Action,Match} from '../src/simulation/types';
function issue(s:Match,a:Action,seat='p1'){const r=submit(s,{id:`${seat}-${s.nextSeq[seat]}`,seat,seq:s.nextSeq[seat],turn:s.turn,revision:s.revision,action:a});expect(r.ok,r.reason).toBe(true);return r.state;}
function setup(){let s=createMatch(['vaire','human_gondor'],127);s.players.p2.ai=false;for(const k of ['P','M','K','E']as const)s.players.p1.stock[k]=2000;s=resolveWeek(issue(s,{kind:'produce',facility:'p1:core',recipe:'component'}));s=issue(s,{kind:'produce',facility:'p1:core',recipe:'hero'});for(let i=0;i<recipe('vaire','hero')!.turns;i++)s=resolveWeek(s);s=resolveWeek(issue(s,{kind:'build',building:'archive',x:4,y:5}));const archive=Object.values(s.facilities).find(f=>f.owner==='p1'&&f.kind==='archive')!.id;s=resolveWeek(issue(s,{kind:'produce',facility:archive,recipe:'plan-equipment'}));s=resolveWeek(issue(s,{kind:'preserve-plan',archive,recipe:'equipment'}));s=resolveWeek(issue(s,{kind:'build',building:'workshop',x:5,y:5}));const shop=Object.values(s.facilities).find(f=>f.owner==='p1'&&f.kind==='workshop')!.id;return {s,archive,shop,plan:Object.keys(s.productionPlans)[0]};}
it('normal creation unlocks and preserves a plan, actual enemy archive destruction enables paid reproduction and private checkpoints',()=>{const prepared=setup();let s=prepared.s;const {archive,shop,plan}=prepared;const attacker=s.units['p2:company:0'];Object.assign(attacker,{x:4,y:6,attack:500});s=resolveWeek(issue(s,{kind:'attack',unit:attacker.id,target:archive},'p2'));while(s.combatPhase)s=resolveWeek(s);expect(s.facilities[archive].hp).toBe(0);s=issue(s,{kind:'remember-workshop',plan,facility:shop});s=issue(s,{kind:'produce',facility:shop,recipe:'equipment'});const view=preview(s,'p1');expect(view.players.p1.commitment).toBe(0);expect(view.facilities[shop].job?.cost).toEqual(recipe('vaire','equipment')!.cost);s=resolveWeek(s);const remaining=s.facilities[shop].job?.remaining;expect(parseMatch(s)).toEqual(s);expect(guestSnapshot(s,'p2').productionPlans).toEqual({});expect(()=>parseMatch(guestSnapshot(s,'p2'),'p2')).not.toThrow();if(remaining){s=resolveWeek(s);expect(s.facilities[shop].job?.remaining).toBe(remaining);s=resolveWeek(issue(s,{kind:'remember-workshop',plan,facility:shop}));}expect(s.facilities[shop].job).toBeUndefined();expect(Object.values(s.items).filter(i=>i.owner==='p1')).toHaveLength(1);});
it('death drops the same plan and save validation rejects duplicate copies or foreign recipe substitution',()=>{const {s,plan}=setup();kill(s,s.players.p1.hero.id);expect(s.productionPlans[plan].carrier).toBeNull();expect(()=>parseMatch(s)).not.toThrow();s.productionPlans.copy={...s.productionPlans[plan],id:'copy'};expect(()=>parseMatch(s)).toThrow(/plan/);});
it('nearby enemy can observe and destroy a dropped plan without learning its archive or research',()=>{const{s,plan}=setup();const h=s.units[s.players.p1.hero.id],u=s.units['p2:company:0'];kill(s,h.id);Object.assign(u,{x:h.x,y:h.y});const view=guestSnapshot(s,'p2');expect(view.productionPlans[plan]).toMatchObject({id:plan,carrier:null,archive:'undisclosed'});expect(view.productionPlans[plan].workshop).toBeUndefined();expect(()=>parseMatch(view,'p2')).not.toThrow();const destroyed=resolveWeek(issue(s,{kind:'destroy-plan',plan,unit:u.id},'p2'));expect(destroyed.productionPlans[plan]).toBeUndefined();Object.assign(u,{x:30,y:30});expect(guestSnapshot(s,'p2').productionPlans[plan]).toBeUndefined();});
