import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {recordObservedAttack} from '../src/simulation/intelligence';
import {startRelayMessage,prepareSecondSignal,progressRelayMessages,type RelayState} from '../src/simulation/relay-messages';
it('reroutes one actual dated report after real primary failure without teleporting or copying observations',()=>{
 const s=createMatch(['ilmare','human_gondor'],1) as RelayState;Object.assign(s,{relayMessages:{},secondSignals:{},relayDeliveries:{},witnessChainUses:{}});s.map.terrain.fill('meadow');const p=s.players.p1,f=s.facilities['p1:core'],u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;Object.assign(f,{x:4,y:4,kind:'safehouse'});u.x=4;u.y=4;u.move=2;s.facilities.primary={...f,id:'primary',x:5,y:4};s.facilities.dest={...f,id:'dest',x:6,y:4};s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero'};p.hero.status='living';p.hero.readiness=6;p.stock.M=100;p.stock.K=100;const enemy=Object.values(s.units).find(u=>u.owner==='p2'&&u.kind==='company')!;enemy.x=4;enemy.y=3;recordObservedAttack(s,enemy);const report=Object.values(s.intelligenceReports).find(r=>r.owner==='p1'&&r.observations.some(o=>o.source===f.id))!;const before=JSON.stringify(report);
 const id=startRelayMessage(s,'p1',{report:report.id,courier:u.id,origin:f.id,primary:'primary',destination:'dest',route:[{x:4,y:4},{x:5,y:4},{x:6,y:4}]},()=>true);
 prepareSecondSignal(s,'p1',id,[{x:4,y:4},{x:4,y:5},{x:5,y:5},{x:6,y:5},{x:6,y:4}],()=>true,()=>true);expect(p.stock.M).toBe(85);expect(p.stock.K).toBe(95);s.facilities.primary.hp=0;progressRelayMessages(s,()=>false,(_s,_u,r)=>r.length-1);expect(u.x).toBe(4);expect(Object.values(s.secondSignals)[0].used).toBe(false);progressRelayMessages(s,()=>true,(_s,_u,r)=>r.length-1);expect(s.relayMessages[id].phase).toBe('travel');expect(u.x).toBe(5);expect(u.y).toBe(5);s.turn++;progressRelayMessages(s,()=>true,(_s,_u,r)=>r.length-1);expect(u.x).toBe(6);expect(s.relayMessages[id].phase).toBe('delivered');expect(Object.values(s.secondSignals)[0].used).toBe(true);expect(JSON.stringify(s.intelligenceReports[report.id])).toBe(before);const delivered=Object.values(s.relayDeliveries)[0];expect(delivered.report).toBe(report.id);expect(delivered.provenance).toEqual(expect.arrayContaining([expect.objectContaining({station:f.id}),expect.objectContaining({station:'dest'})]));const count=Object.keys(s.relayDeliveries).length;progressRelayMessages(s,()=>true,(_s,_u,r)=>r.length-1);expect(Object.keys(s.relayDeliveries)).toHaveLength(count);
});
