import {expect,it} from 'vitest';
import {createMatch,resolveWeek,submit,preview} from '../src/simulation/engine';
import {parseMatch} from '../src/simulation/schema';
import {guestSnapshot} from '../src/network/protocol';
import type {Action,Match} from '../src/simulation/types';
const issue=(s:Match,action:Action)=>submit(s,{id:`rations-${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});
it('packs paid finite reserves for one Sauron company, upkeep consumes them before bank stocks and guests see no reserve',()=>{let s=createMatch(['sauron','human_gondor'],1);const p=s.players.p1;p.hero.status='living';s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero'};s.facilities.depot={...structuredClone(s.facilities['p1:core']),id:'depot',kind:'depot',x:4,y:5};const u=s.units['p1:company:0'];const before=p.stock.P;const r=issue(s,{kind:'pack-rations',unit:u.id,facility:'depot',amount:5});expect(r.ok,r.reason).toBe(true);const view=preview(r.state,'p1');expect(view.units[u.id].reserveProvisions).toBe(5);expect(view.players.p1.stock.P).toBe(before-5);expect(view.players.p1.operations).toBe(2);expect(issue(r.state,{kind:'pack-rations',unit:'p1:company:1',facility:'depot',amount:1}).ok).toBe(false);s=resolveWeek(r.state);expect(s.units[u.id].reserveProvisions).toBe(5-u.upkeep.P);expect(()=>parseMatch(s)).not.toThrow();const guest=guestSnapshot(s,'p2');expect(guest.units[u.id]?.reserveProvisions).toBeUndefined();});
it('rejects foreign reserve capacity and forged multiple reserve parties',()=>{const s=createMatch(['human_gondor','sauron'],1);expect(issue(s,{kind:'pack-rations',unit:'p1:company:0',facility:'p1:core',amount:5}).ok).toBe(false);s.units['p1:company:0'].reserveProvisions=5;expect(()=>parseMatch(s)).toThrow();});
it('diplomacy gear discounts only actual courier upkeep and consumes durability only after full affordable payment',async()=>{const {payReservedUpkeep}=await import('../src/simulation/reserved-rations');const s=createMatch(['elf_finarfin','human_gondor'],1),u=s.units['p1:company:0'],p=s.players.p1;u.upkeep={P:2,M:1,K:0,E:0};s.items.kit={id:'kit',name:'Diplomacy tools',owner:'p1',bearer:u.id,crafted:true,finalProduct:'diplomacy-tools',bonus:0,attackBonus:0,durability:2,maxDurability:100,materials:['textile'],x:u.x,y:u.y};u.inventory.push('kit');s.relayMessages.message={id:'message',owner:'p1',report:'report',courier:u.id,origin:'origin',primary:'primary',destination:'destination',route:[{x:u.x,y:u.y}],index:0,x:u.x,y:u.y,started:s.turn,lastProgress:s.turn-1,phase:'travel',provenance:[]};p.stock={P:1,M:0,K:0,E:0};expect(payReservedUpkeep(s,u)).toBe(false);expect(s.items.kit.durability).toBe(2);expect(p.stock.P).toBe(1);p.stock.M=1;expect(payReservedUpkeep(s,u)).toBe(true);expect(p.stock).toEqual({P:0,M:0,K:0,E:0});expect(s.items.kit.durability).toBe(1);s.relayMessages.message.phase='delivered';p.stock={P:2,M:1,K:0,E:0};expect(payReservedUpkeep(s,u)).toBe(true);expect(s.items.kit.durability).toBe(1);expect(p.stock.P).toBe(0);});
