import {expect,it} from 'vitest';
import {createMatch,submit,resolveWeek} from '../src/simulation/engine';
import {parseMatch} from '../src/simulation/schema';
import {guestSnapshot} from '../src/network/protocol';
import type {Action,Match} from '../src/simulation/types';
function command(s:Match,seat:string,action:Action){return submit(s,{id:`${seat}-${s.revision}-${s.nextSeq[seat]}`,seat,seq:s.nextSeq[seat],turn:s.turn,revision:s.revision,action});}
function fixture(profile='wolf_pack'){const s=createMatch([profile,'human_gondor'],77);s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};for(const q of Object.values(s.preySites))q.habitat='meadow';const p=s.players.p1;p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero',x:10,y:10,move:6,effects:[]};Object.assign(s.units['p1:company:0'],{x:10,y:11,move:6});Object.assign(s.units['p2:company:0'],{x:14,y:10});Object.assign(s.preySites['prey:p1'],{x:11,y:10});return s;}
it('scout power spends one hero action and delivers anonymous contacts rather than enemy caster records',()=>{let s=fixture('istari_veil');const c=command(s,'p1',{kind:'scout-power',mode:'borrowed-shadow',point:{x:11,y:10}});expect(c.ok,c.reason).toBe(true);s=resolveWeek(c.state);expect(s.players.p1.hero.readiness).toBe(4);expect(s.players.p1.commitment).toBe(0);expect(s.players.p1.operations).toBe(3);expect(()=>parseMatch(s)).not.toThrow();const guest=guestSnapshot(s,'p2');expect(Object.keys(guest.scoutShadows)).toHaveLength(0);expect(guest.contacts).toContainEqual({x:11,y:10});expect(()=>parseMatch(guest,'p2')).not.toThrow();});
it('weekly survey reserves hero and source costs, moves physically and persists a private dated report',()=>{let s=fixture();const c=command(s,'p1',{kind:'hunting',mode:'survey',unit:s.players.p1.hero.id,route:[{x:10,y:10},{x:11,y:10}]});expect(c.ok,c.reason).toBe(true);expect(command(c.state,'p1',{kind:'move',unit:s.players.p1.hero.id,x:9,y:10}).ok).toBe(false);s=resolveWeek(c.state);expect(Object.values(s.huntingReports)).toHaveLength(1);expect(s.preySites['prey:p1'].remaining).toBe(12);expect(s.units[s.players.p1.hero.id].x).toBe(11);expect(()=>parseMatch(s)).not.toThrow();const guest=guestSnapshot(s,'p2');expect(Object.keys(guest.huntingReports)).toHaveLength(0);expect(()=>parseMatch(guest,'p2')).not.toThrow();});
it('ordinary hunt consumes actual finite prey and roundtrip never replenishes it',()=>{let s=fixture();const c=command(s,'p1',{kind:'hunting',mode:'hunt',unit:'p1:company:0',prey:'prey:p1',amount:2,route:[{x:10,y:11},{x:11,y:11},{x:11,y:10}]});expect(c.ok,c.reason).toBe(true);s=resolveWeek(c.state);expect(s.preySites['prey:p1'].remaining).toBe(10);expect(parseMatch(JSON.parse(JSON.stringify(s))).preySites['prey:p1'].remaining).toBe(10);});
it('pending paid hunting survives tactical checkpoint, rejects forged budget, and hides remote prey inventory',()=>{let s=fixture();const h=s.players.p1.hero.id;s.combatPhase=1;const c=command(s,'p1',{kind:'hunting',mode:'survey',unit:h,route:[{x:10,y:10},{x:11,y:10}]});expect(c.ok,c.reason).toBe(true);s=resolveWeek(c.state);expect(Object.keys(s.huntingJobs)).toHaveLength(1);expect(()=>parseMatch(s)).not.toThrow();const forged=structuredClone(s);forged.players.p1.commitment=1;expect(()=>parseMatch(forged)).toThrow(/Unpaid hunting/);for(const u of Object.values(s.units))if(u.owner==='p2'){u.x=28;u.y=28;}const guest=guestSnapshot(s,'p2');expect(guest.preySites['prey:p1']).toBeUndefined();expect(Object.keys(guest.huntingJobs)).toHaveLength(0);expect(()=>parseMatch(guest,'p2')).not.toThrow();});
