import {expect,it} from 'vitest';
import {createMatch,submit,preview,resolveWeek} from '../src/simulation/engine';
import {secondaryProduction,type SecondaryKey,type SecondaryUnit} from '../src/content/secondary-production';
import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';
import {stocks,type Match,type Action} from '../src/simulation/types';
const order=(s:Match,action:Action)=>submit(s,{id:`secondary:${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action});
function produced(profile:string,key:SecondaryKey){let s=createMatch([profile,'human_gondor'],19);const p=s.players.p1,core=s.facilities['p1:core'],q=secondaryProduction(profile,key)!;p.stock=stocks(999,999,999,999);p.sources=[...new Set([...p.sources,...q.recipe.access])];s.facilities.work={...core,id:'work',kind:'workshop',workers:1};const result=order(s,{kind:'produce',facility:'work',recipe:key});expect(result.ok,result.reason).toBe(true);const reserved=preview(result.state,'p1');expect(reserved.facilities.work.job?.cost).toEqual(q.recipe.cost);for(const k of ['P','M','K','E']as const)expect(reserved.players.p1.stock[k]).toBe(p.stock[k]-q.recipe.cost[k]);s=result.state;for(let i=0;i<q.recipe.turns;i++)s=resolveWeek(s);const unit=Object.values(s.units).find(u=>(u as SecondaryUnit).secondary===key)!;expect(unit).toBeDefined();expect(unit).toMatchObject(q.stats);return{s,id:unit.id};}
it('all four exact secondary products complete paid staffed queues with real stats and survive checkpoint',()=>{for(const[profile,key]of [['eagle_eyrie','rescue-flight'],['wolf_pack','pack-runner'],['spider_brood','venom-stalker'],['troll_hold','troll-siege-crew']]as const){const{s,id}=produced(profile,key);expect(s.facilities.work.job).toBeUndefined();expect((decodeCheckpoint(encodeCheckpoint(s)).state.units[id]as SecondaryUnit).secondary).toBe(key);}});
it('produced Venom Stalker applies ordinary curable poison through an actual hostile attack',()=>{const{s,id}=produced('spider_brood','venom-stalker'),u=s.units[id],t=Object.values(s.units).find(u=>u.owner==='p2'&&u.kind==='company')!;t.x=u.x+1;t.y=u.y;s.map.terrain[t.y*s.map.width+t.x]='grass';t.hp=t.maxHp=150;t.armor=0;s.players.p1.relations.p2='war';s.players.p2.relations.p1='war';const r=order(s,{kind:'attack',unit:id,target:t.id});expect(r.ok,r.reason).toBe(true);let next=resolveWeek(r.state);expect(next.units[t.id].effects.some(e=>e.kind==='poison')).toBe(true);const hp=next.units[t.id].hp;next=resolveWeek(next);expect(next.units[t.id].hp).toBeLessThan(hp);});
it('produced Troll Siege Crew deals its structural bonus without an invented siege magazine',()=>{const{s,id}=produced('troll_hold','troll-siege-crew'),u=s.units[id];s.facilities.target={...s.facilities['p2:core'],id:'target',kind:'gate',x:u.x+1,y:u.y,hp:500,maxHp:500};s.map.terrain[u.y*s.map.width+u.x+1]='grass';s.players.p1.relations.p2='war';s.players.p2.relations.p1='war';const r=order(s,{kind:'attack',unit:id,target:'target'});expect(r.ok,r.reason).toBe(true);const next=resolveWeek(r.state);expect(500-next.facilities.target.hp).toBe(17); // Seeded21 gross (16 base +4 crew +1 roll), less4 facility armor.
expect(next.units[id].siege).toBeUndefined();});
it('produced Rescue Flight performs paid ordinary physical rescue without creating or committing its hero',()=>{const initial=produced('eagle_eyrie','rescue-flight'),id=initial.id;let s=initial.s;const takeoff=order(s,{kind:'land',unit:id});expect(takeoff.ok,takeoff.reason).toBe(true);s=resolveWeek(takeoff.state);const c=s.units[id],u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;u.x=c.x;u.y=c.y;expect(c.landed).toBe(false);const to={x:c.x+2,y:c.y};s.map.terrain[to.y*s.map.width+to.x]='grass';const r=order(s,{kind:'logistics',mode:'rescue-flight',carrier:id,unit:u.id,to});expect(r.ok,r.reason).toBe(true);const reserved=preview(r.state,'p1');expect(reserved.players.p1.stock.P).toBe(s.players.p1.stock.P-2);expect(reserved.players.p1.operations).toBe(s.players.p1.operations-1);expect(reserved.players.p1.hero.status).toBe('uncreated');let next=resolveWeek(r.state);expect(next.units[u.id].x).toBe(next.units[id].x);next=resolveWeek(next);expect(next.units[u.id]).toMatchObject(to);expect(next.units[id]).toMatchObject(to);expect(Object.keys(next.logisticsJobs)).toEqual([]);});
it('rejects forged finite secondary supply upkeep and capacity',()=>{const{s,id}=produced('wolf_pack','pack-runner');for(const patch of [{supply:0},{upkeep:stocks(0)},{maxHp:999},{loadClass:'large'}]){const forged=structuredClone(s);Object.assign(forged.units[id],patch);expect(()=>decodeCheckpoint(encodeCheckpoint(forged))).toThrow();}});
