import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {secondaryKeys,secondaryProduction,secondaryCapabilities,secondaryVenomHit,progressSecondaryVenom,type SecondaryUnit} from '../src/content/secondary-production';
const owners=['eagle_eyrie','wolf_pack','spider_brood','troll_hold'];
it('authorizes each exact secondary output only for its source faction with paid finite recipes',()=>{const names=['Rescue Flights','Runners','Venom Stalkers','Siege Crews'];for(let n=0;n<4;n++){const p=secondaryProduction(owners[n],secondaryKeys[n])!;expect(p.recipe.name).toBe(names[n]);expect(p.recipe.provisional).toBe(true);expect(p.recipe.turns).toBeGreaterThan(0);expect(p.recipe.supply).toBeGreaterThan(0);expect(p.source).toContain('§10');for(let m=0;m<4;m++)if(m!==n)expect(secondaryProduction(owners[m],secondaryKeys[n])).toBeUndefined();expect(secondaryProduction('melkor_dark_architect',secondaryKeys[n])).toBeUndefined();} });
it('provides distinct physical capabilities and returns isolated content',()=>{const a=secondaryProduction('eagle_eyrie','rescue-flight')!;expect(a.stats.flying).toBe(true);expect(a.capabilities.rescuePassengers).toBe(1);a.recipe.cost.P=0;expect(secondaryProduction('eagle_eyrie','rescue-flight')!.recipe.cost.P).toBeGreaterThan(0);expect(secondaryProduction('wolf_pack','pack-runner')!.stats.move).toBeGreaterThan(5);expect(secondaryProduction('troll_hold','troll-siege-crew')!.capabilities.structuralAttackBonus).toBe(4);});
function spiders(){const s=createMatch(['spider_brood','human_gondor'],17),u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='beast')! as SecondaryUnit,t=Object.values(s.units).find(u=>u.owner==='p2'&&u.kind==='company')!;Object.assign(u,secondaryProduction('spider_brood','venom-stalker')!.stats,{secondary:'venom-stalker'});t.x=u.x+1;t.y=u.y;return{s,u,t};}
it('actual adjacent successful venom hits cause bounded ordinary poison; misses and constructs do not',()=>{const{s,u,t}=spiders();const hp=t.hp;secondaryVenomHit(s,u,t,0);expect(t.effects).toEqual([]);secondaryVenomHit(s,u,t,1);s.revision++;progressSecondaryVenom(s);expect(t.hp).toBe(hp-2);progressSecondaryVenom(s);expect(t.hp).toBe(hp-2);s.revision++;progressSecondaryVenom(s);expect(t.hp).toBe(hp-4);expect(t.effects.some(e=>e.kind==='poison')).toBe(false);t.kind='construct';secondaryVenomHit(s,u,t,1);expect(t.effects.some(e=>e.kind==='poison')).toBe(false);});
it('does not grant secondary powers by name alone or foreign metadata, and removing ordinary poison prevents its tick',()=>{const{s,u,t}=spiders();u.owner='p2';expect(secondaryCapabilities(s,u)).toBeUndefined();secondaryVenomHit(s,u,t,1);expect(t.effects).toEqual([]);u.owner='p1';secondaryVenomHit(s,u,t,1);t.effects=t.effects.filter(e=>e.kind!=='poison');const hp=t.hp;s.revision++;progressSecondaryVenom(s);expect(t.hp).toBe(hp);});

import {logisticsReason,startLogistics,progressLogistics,validateLogisticsState,type LogisticsRequest} from '../src/simulation/logistics-support';
it('ordinary Rescue Flight pays stocks and operation without hero, carrying the same passenger over physical phases',()=>{const s=createMatch(['eagle_eyrie','human_gondor'],9),p=s.players.p1,c=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='beast')! as SecondaryUnit,u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;Object.assign(c,secondaryProduction('eagle_eyrie','rescue-flight')!.stats,{secondary:'rescue-flight',landed:false});u.x=c.x;u.y=c.y;const at={x:c.x+2,y:c.y};s.map.terrain[at.y*s.map.width+at.x]='plain';const route=()=>[{x:c.x,y:c.y},{x:c.x+1,y:c.y},at];const a={mode:'rescue-flight',carrier:c.id,unit:u.id,to:at} as LogisticsRequest,stock=p.stock.P,ready=p.hero.readiness,ops=p.operations;expect(logisticsReason(s,'p1',a,route)).toBe('');startLogistics(s,'p1',a,route);expect(p.stock.P).toBe(stock-2);expect(p.operations).toBe(ops-1);expect(p.hero.readiness).toBe(ready);expect(()=>validateLogisticsState(s)).not.toThrow();s.revision++;progressLogistics(s,route);expect(u.x).toBe(at.x-1);expect(c.x).toBe(u.x);s.revision++;progressLogistics(s,route);expect(u.x).toBe(at.x);expect(c.x).toBe(at.x);expect(Object.keys(s.logisticsJobs)).toEqual([]);});
it('Scout Flights cannot impersonate rescuers and a killed real carrier leaves the same stranded passenger',()=>{const s=createMatch(['eagle_eyrie','human_gondor'],9),c=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='beast')! as SecondaryUnit,u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;c.landed=false;u.x=c.x;u.y=c.y;const at={x:c.x+2,y:c.y};s.map.terrain[at.y*s.map.width+at.x]='plain';const points=[{x:c.x,y:c.y},{x:c.x+1,y:c.y},at],route=()=>points;const a={mode:'rescue-flight',carrier:c.id,unit:u.id,to:at} as LogisticsRequest;expect(logisticsReason(s,'p1',a,route)).toMatch(/Rescue Flight/);Object.assign(c,secondaryProduction('eagle_eyrie','rescue-flight')!.stats,{secondary:'rescue-flight',landed:false});startLogistics(s,'p1',a,route);s.revision++;progressLogistics(s,route);const x=u.x;c.alive=false;s.revision++;progressLogistics(s,route);expect(u.alive).toBe(true);expect(u.x).toBe(x);expect(Object.values(s.logisticsJobs)[0]).toMatchObject({status:'lost',passenger:u.id});expect(()=>validateLogisticsState(s)).not.toThrow();});
