import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {prepareLanding,bindLanding,completeLanding,surgePassage,surgeFootingPenalty,authorizeCurrentCrossing,currentAllows,type ShoreState} from '../src/simulation/shore-powers';
function fixture(profile='ulmo'){const s=Object.assign(createMatch([profile,'human_rohan'],3),{shorePreparations:{},currentCrossings:{},shallowWater:{"5,4":true}}) as ShoreState;s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.infrastructureSites={};const p=s.players.p1,u=s.units['p1:company:0'];p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',engineer:undefined,x:4,y:4};u.x=4;u.y=4;s.map.terrain[4*s.map.width+5]='water';return{s,p,u};}
it('Ulmo footing preparation affects only existing shallow crossing, ends after two phases and braces counter it',()=>{const{s,p}=fixture();const enemy=s.units['p2:company:0'];enemy.x=5;enemy.y=4;surgePassage(s,'p1',enemy.id,{x:5,y:4},()=>true);expect(p.hero.readiness).toBe(4);expect(surgeFootingPenalty(s,enemy)).toBe(1);enemy.effects.push({kind:'brace',value:1,until:99,source:'test'});expect(surgeFootingPenalty(s,enemy)).toBe(0);enemy.effects=[];s.revision+=2;expect(surgeFootingPenalty(s,enemy)).toBe(0);});
it('current authorization never moves or copies loaded convoy and permits only paid carrier on surveyed span',()=>{const{s,p,u}=fixture();s.convoys.convoy={id:'convoy',owner:'p1',carrier:u.id,origin:'p1:core',destination:'p1:training',cargo:{P:10,M:0,K:0,E:0},supplies:{P:3,M:0,K:0,E:0},capacity:20,route:[{x:4,y:4},{x:5,y:4},{x:6,y:4}],index:0,x:4,y:4,phase:'travel',started:s.turn,lastProgress:s.turn-1};const before=structuredClone(s.convoys.convoy);authorizeCurrentCrossing(s,'p1','convoy',before.route,()=>true,()=>false);expect(p.hero.readiness).toBe(3);expect(s.convoys.convoy).toEqual(before);expect(currentAllows(s,u,{x:5,y:4})).toBe(true);expect(currentAllows(s,s.units['p2:company:0'],{x:5,y:4})).toBe(false);s.turn++;expect(currentAllows(s,u,{x:5,y:4})).toBe(false);});
it('ordinary marine unloading loses cohesion; paid landing removes only that new loss without restoring old cohesion',()=>{const{s,p,u}=fixture('human_numenor');s.vessels.ship={id:'ship',owner:'p1',name:'Transport',x:5,y:4,hp:50,maxHp:50,move:3,crew:'p1:worker:0',passenger:u.id,aboardHero:null,cargo:{P:0,M:0,K:0,E:0},fogSpent:false,phase:'idle',route:[],index:0,lastProgress:s.turn-1,handlingRemaining:0};u.effects.push({kind:'cohesion-loss',value:1,until:100,source:'morale:1'});prepareLanding(s,'p1','ship',u.id,{x:4,y:4},()=>false);expect(p.hero.readiness).toBe(4);bindLanding(s,'ship',u.id,{x:4,y:4});completeLanding(s,'ship',u,{x:4,y:4});expect(u.effects.find(e=>e.kind==='cohesion-loss')?.value).toBe(1);completeLanding(s,'ship',u,{x:4,y:4});expect(u.effects.find(e=>e.kind==='cohesion-loss')?.value).toBe(2);});
it('higher ground and interrupted Ulmo remove footing without damage; blocked landing never accepts preparation',()=>{const{s}=fixture();const u=s.units['p2:company:0'];u.x=5;u.y=4;surgePassage(s,'p1',u.id,{x:5,y:4},()=>true);u.x=6;expect(surgeFootingPenalty(s,u)).toBe(0);u.x=5;s.units[s.players.p1.hero.id].active=false;expect(surgeFootingPenalty(s,u)).toBe(0);const n=fixture('human_numenor');expect(()=>prepareLanding(n.s,'p1','missing',n.u.id,{x:4,y:4},()=>true)).toThrow();});
it('current cannot be reused after actual far-bank passage and contested endpoints reject without readiness cost',()=>{const{s,p,u}=fixture();s.convoys.c={id:'c',owner:'p1',carrier:u.id,origin:'p1:core',destination:'p1:training',cargo:{P:4,M:0,K:0,E:0},supplies:{P:3,M:0,K:0,E:0},capacity:20,route:[{x:4,y:4},{x:5,y:4},{x:6,y:4}],index:0,x:4,y:4,phase:'travel',started:s.turn,lastProgress:s.turn-1};const tiles=s.convoys.c.route;expect(()=>authorizeCurrentCrossing(s,'p1','c',tiles,()=>true,p=>p.x===6)).toThrow(/open banks/);expect(p.hero.readiness).toBe(6);authorizeCurrentCrossing(s,'p1','c',tiles,()=>true,()=>false);consumeCurrentAtBank(s,u,tiles);expect(currentAllows(s,u,{x:5,y:4})).toBe(false);expect(()=>authorizeCurrentCrossing(s,'p1','c',tiles,()=>true,()=>false)).toThrow(/already/);});
import {consumeCurrentAtBank} from '../src/simulation/shore-powers';
import {submit,resolveWeek,path} from '../src/simulation/engine';
import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';
import {guestSnapshot} from '../src/network/protocol';
import type {Action} from '../src/simulation/types';
function issue(s:ShoreState,a:Action){const r=submit(s,{id:`shore:${s.nextSeq.p1}`,seat:'p1',seq:s.nextSeq.p1,turn:s.turn,revision:s.revision,action:a});expect(r.ok,r.reason).toBe(true);return r.state;}
it('engine current crosses real water at normal speed and preserves cargo, then saves without permanent ferry',()=>{const setup=fixture();let{s}=setup;const{u}=setup;s.facilities['p1:training'].x=6;s.facilities['p1:training'].y=4;s.convoys.c={id:'c',owner:'p1',carrier:u.id,origin:'p1:core',destination:'p1:training',cargo:{P:4,M:0,K:0,E:0},supplies:{P:3,M:0,K:0,E:0},capacity:20,route:[{x:4,y:4},{x:4,y:3},{x:5,y:3},{x:6,y:3},{x:6,y:4}],index:0,x:4,y:4,phase:'travel',started:s.turn,lastProgress:s.turn-1};delete s.shallowWater['5,4'];expect(path(s,u,{x:5,y:4},false,u)).toBeNull();s=issue(s,{kind:'current-crossing',convoy:'c',tiles:[{x:4,y:4},{x:5,y:4},{x:6,y:4}]});s=resolveWeek(s);expect(s.units[u.id]).toMatchObject({x:6,y:4});expect(s.convoys.c.cargo.P).toBe(4);expect(s.convoys.c.phase).toBe('unloading');expect(Object.values(s.currentCrossings)[0].consumed).toBe(true);expect(path(s,s.units[u.id],{x:5,y:4},false,s.units[u.id])).toBeNull();expect(guestSnapshot(s,'p2').currentCrossings).toEqual({});expect(decodeCheckpoint(encodeCheckpoint(s)).state.convoys.c.cargo.P).toBe(4);});
it('actual paid marine landing stays organized across response phases until ordinary unloading completes',()=>{const setup=fixture('human_numenor');let{s}=setup;const{u}=setup;u.x=5;const worker=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;worker.x=5;worker.y=4;s.vessels.ship={id:'ship',owner:'p1',name:'Transport',x:5,y:4,hp:80,maxHp:80,move:4,crew:worker.id,passenger:u.id,aboardHero:null,cargo:{P:0,M:0,K:0,E:0},fogSpent:false,phase:'idle',route:[],index:0,lastProgress:s.turn-1,handlingRemaining:0};s=issue(s,{kind:'coastal-landing',ship:'ship',unit:u.id,tile:{x:4,y:4}});s=issue(s,{kind:'disembark',ship:'ship',unit:u.id,landing:{x:4,y:4}});s=resolveWeek(s);while(s.combatPhase)s=resolveWeek(s);expect(s.vessels.ship.passenger).toBeNull();expect(s.units[u.id]).toMatchObject({x:4,y:4});expect(s.units[u.id].effects.some(e=>e.kind==='cohesion-loss')).toBe(false);expect(Object.values(s.shorePreparations).filter(q=>q.kind==='landing')).toHaveLength(0);});
it('actual Ulmo hostile ford order projects anonymous footing but no enemy preparation identity',()=>{let{s}=fixture();const enemy=s.units['p2:company:0'];enemy.x=5;enemy.y=4;s=issue(s,{kind:'surge-passage',unit:enemy.id,tile:{x:5,y:4}});s=resolveWeek(s);const guest=guestSnapshot(s,'p2');expect(guest.shorePreparations).toEqual({});expect(guest.units[enemy.id].effects.some(e=>e.kind==='shore-footing'&&e.source==='shallow:5,4')).toBe(true);expect(surgeFootingPenalty(guest,guest.units[enemy.id])).toBe(1);});
it('a newly rooted current span pauses at the near bank instead of splitting a one-week passage',()=>{const setup=fixture();let{s}=setup;const{u}=setup;u.move=2;s.facilities['p1:training'].x=6;s.facilities['p1:training'].y=4;delete s.shallowWater['5,4'];s.convoys.c={id:'c',owner:'p1',carrier:u.id,origin:'p1:core',destination:'p1:training',cargo:{P:4,M:0,K:0,E:0},supplies:{P:3,M:0,K:0,E:0},capacity:20,route:[{x:4,y:4},{x:4,y:3},{x:5,y:3},{x:6,y:3},{x:6,y:4}],index:0,x:4,y:4,phase:'travel',started:s.turn,lastProgress:s.turn-1};s=issue(s,{kind:'current-crossing',convoy:'c',tiles:[{x:4,y:4},{x:5,y:4},{x:6,y:4}]});s.zones.z={id:'z',owner:'p2',kind:'roots',x:5,y:4,dx:0,dy:0,radius:1,until:100,triggered:false};s=resolveWeek(s);expect(s.units[u.id]).toMatchObject({x:4,y:4});expect(s.convoys.c.cargo.P).toBe(4);expect(s.convoys.c.pauseReason).toMatch(/whole.*passage/);delete s.zones.z;s=resolveWeek(s);expect(s.units[u.id]).toMatchObject({x:4,y:4});expect(s.convoys.c.cargo.P).toBe(4);});
