import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {stocks} from '../src/simulation/types';
import {agreeWarbandReward,payWarbandReward,recordWarbandParticipation,progressWarbandRewards,validateWarbandRewards,type RewardState} from '../src/simulation/warband-rewards';
function setup(){const s=createMatch(['orc_fortress_clan','human_rohan'],9)as RewardState,p=s.players.p1,u=s.units['p1:company:0'],f=s.facilities['p1:core'];p.stock=stocks(100,100,100,100);p.operations=3;s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',x:f.x,y:f.y,effects:[],inventory:[]};p.hero.status='living';u.x=f.x;u.y=f.y;return {s,p,u,f,h:s.units[p.hero.id]};}
it('timely fulfilled participating reward costs full stocks and prevents one new dispute only',()=>{const{s,p,u,f}=setup();u.effects.push({kind:'cohesion-loss',value:2,until:1000000,source:'old-grievance'});const old=structuredClone(s.grievances);agreeWarbandReward(s,'p1',u.id,stocks(5,3),s.turn);recordWarbandParticipation(s,u);payWarbandReward(s,'p1',u.id,f.id);expect(p.stock).toEqual(stocks(95,97,100,100));expect(p.operations).toBe(1);expect(u.effects.find(e=>e.kind==='cohesion-loss')?.value).toBe(2);expect(s.grievances).toEqual(old);expect(()=>payWarbandReward(s,'p1',u.id,f.id)).toThrow();expect(()=>validateWarbandRewards(s)).not.toThrow();});
it('payment without hero suffers ordinary distribution friction and late default is once only',()=>{const{s,p,u,f,h}=setup();h.active=false;agreeWarbandReward(s,'p1',u.id,stocks(5),s.turn);recordWarbandParticipation(s,u);payWarbandReward(s,'p1',u.id,f.id);expect(u.effects.find(e=>e.kind==='cohesion-loss')?.value).toBe(1);s.turn++;p.operations=3;agreeWarbandReward(s,'p1',u.id,stocks(5),s.turn);recordWarbandParticipation(s,u);s.turn++;progressWarbandRewards(s);expect(u.effects.find(e=>e.kind==='cohesion-loss')?.value).toBe(2);progressWarbandRewards(s);expect(u.effects.find(e=>e.kind==='cohesion-loss')?.value).toBe(2);expect(p.stock.P).toBe(95);});
it('new agreement cannot reuse previous participation or receive a second weekly passive discount',()=>{const{s,p,u,f}=setup();agreeWarbandReward(s,'p1',u.id,stocks(5),s.turn);recordWarbandParticipation(s,u);payWarbandReward(s,'p1',u.id,f.id);p.operations=3;agreeWarbandReward(s,'p1',u.id,stocks(5),s.turn);expect(()=>payWarbandReward(s,'p1',u.id,f.id)).toThrow(/participat/);recordWarbandParticipation(s,u);payWarbandReward(s,'p1',u.id,f.id);expect(u.effects.find(e=>e.kind==='cohesion-loss')?.value).toBe(1);expect(()=>validateWarbandRewards(s,'p2')).toThrow();});
it('insufficient payout never partially spends and forged paid history is invalid',()=>{const{s,p,u,f}=setup();agreeWarbandReward(s,'p1',u.id,stocks(5,3),s.turn);recordWarbandParticipation(s,u);p.stock.M=2;const before=structuredClone(s);expect(()=>payWarbandReward(s,'p1',u.id,f.id)).toThrow(/stocks/);expect(s).toEqual(before);s.warbandAgreements![u.id].status='paid';expect(()=>validateWarbandRewards(s)).toThrow();});
