import {it,expect} from 'vitest';import {createMatch} from '../src/simulation/engine';import {queueWatchGear,progressWatchGear,startReweave,watchActive,borderMemory,type WatchState} from '../src/simulation/watch-posts';
function fixture(){const s=Object.assign(createMatch(['elf_sindar','human_rohan'],3),{watchGear:{},watchJobs:{},borderReports:{},borderSurveys:{}})as WatchState;s.map.terrain.fill('woodland');const p=s.players.p1,f=s.facilities['p1:training'],u=Object.values(s.units).find(u=>u.owner==='p1'&&u.kind==='worker')!;Object.assign(f,{kind:'watch-post',x:4,y:4,workers:1});Object.assign(u,{x:4,y:4});p.stock={P:100,M:100,K:100,E:100};p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(u),id:p.hero.id,kind:'hero',x:4,y:4};return{s,p,f,u};}
const checks={open:()=>true,surveyed:()=>true,budget:()=>3,moved:()=>{}};
it('paid ordinary gear creation enables one real staffed post and cannot duplicate its equipment',()=>{const{s,p,f}=fixture();expect(watchActive(s,f.id)).toBe(false);queueWatchGear(s,'p1',f.id);expect(p.stock).toMatchObject({M:90,K:95});progressWatchGear(s,checks);expect(watchActive(s,f.id)).toBe(true);expect(()=>queueWatchGear(s,'p1',f.id)).toThrow();});
it('Reweave removes old observation immediately, physically moves one staff and gear identity while keeping old foundations, then only new site activates',()=>{const{s,p,f,u}=fixture();queueWatchGear(s,'p1',f.id);progressWatchGear(s,checks);const gear=Object.keys(s.watchGear)[0];startReweave(s,'p1',f.id,u.id,[{x:4,y:4},{x:5,y:4},{x:6,y:4}],checks);expect(f.workers).toBe(0);expect(watchActive(s,f.id)).toBe(false);expect(p.hero.readiness).toBe(3);expect(u.x).toBe(4);progressWatchGear(s,checks);expect(f).toMatchObject({x:4,y:4,workers:0});expect(u.x).toBe(6);expect(watchActive(s,f.id)).toBe(false);expect(s.facilities[s.watchGear[gear].facility]).toMatchObject({x:6,y:4,workers:1,hp:30});expect(watchActive(s,s.watchGear[gear].facility)).toBe(true);expect(Object.keys(s.watchGear)).toEqual([gear]);});
it('lost woodland pauses real workers without restoring old observation or minting staff',()=>{const{s,f,u}=fixture();queueWatchGear(s,'p1',f.id);progressWatchGear(s,checks);startReweave(s,'p1',f.id,u.id,[{x:4,y:4},{x:5,y:4}],checks);s.map.terrain[4*s.map.width+5]='meadow';progressWatchGear(s,checks);expect(f.workers).toBe(0);expect(u.x).toBe(4);expect(watchActive(s,f.id)).toBe(false);});
it('Border Memory reports only anonymous fresh disturbance on a physically revisited route once each week',()=>{const{s,p}=fixture();const h=s.units[p.hero.id],route=[{x:4,y:4},{x:5,y:4}];s.borderSurveys.old={id:'old',owner:'p1',points:route,turn:s.turn,revision:0};s.movementTraces.enemy={id:'enemy',owner:'p2',route,turn:s.turn,revision:1,erased:false};s.revision=2;borderMemory(s,h,route);expect(Object.values(s.borderReports)).toHaveLength(1);expect(JSON.stringify(s.borderReports)).not.toContain('p2');borderMemory(s,h,route);expect(Object.values(s.borderReports)).toHaveLength(1);});
it('staff and gear cannot activate remotely when normal movement allows only part of the woodland route',()=>{const{s,f,u}=fixture();queueWatchGear(s,'p1',f.id);progressWatchGear(s,checks);startReweave(s,'p1',f.id,u.id,[{x:4,y:4},{x:5,y:4},{x:6,y:4}],checks);progressWatchGear(s,{...checks,budget:()=>2,cost:(_s,_u,route)=>route.length});expect(u.x).toBe(5);expect(f.workers).toBe(0);expect(Object.values(s.watchGear)[0].active).toBe(false);expect(Object.values(s.watchJobs)[0].staff).toBe(1);});
it('Border Memory cannot borrow another company survey or reinterpret tracks predating the hero visit',()=>{const{s,p}=fixture(),h=s.units[p.hero.id],route=[{x:4,y:4},{x:5,y:4}];s.routeSurveys.company={id:'company',owner:'p1',route,turn:s.turn,revision:0};s.movementTraces.t={id:'t',owner:'p2',route,turn:s.turn,revision:0,erased:false};s.revision=1;borderMemory(s,h,route);expect(Object.keys(s.borderReports)).toHaveLength(0);s.revision=2;borderMemory(s,h,route);expect(Object.keys(s.borderReports)).toHaveLength(0);});
