import {expect,it} from 'vitest';
import {createMatch} from '../src/simulation/engine';
import {prepareWorksiteSupport,evacuateWorksite,progressWorksiteSupports,type WorksiteState,type WorksiteChecks} from '../src/simulation/worksite-support';
function fixture(profile='istari_ember'){const s:WorksiteState={...createMatch([profile,'human_rohan'],5),worksiteSupports:{}};const p=s.players.p1,f=s.facilities['p1:core'];Object.assign(f,{x:4,y:4,workers:3,kind:'research'});f.job={id:'existing',recipe:'technique',remaining:2,started:1,cost:{P:0,M:20,K:30,E:10},supply:0,binding:0,great:0};s.facilities.refuge={...structuredClone(f),id:'refuge',kind:'refuge',x:6,workers:1,job:undefined};p.hero.status='living';p.hero.readiness=6;s.units[p.hero.id]={...structuredClone(s.units['p1:company:0']),id:p.hero.id,kind:'hero',x:4,y:4};const checks:WorksiteChecks={connected:()=>true,openRoute:()=>true,observedApproach:()=>false};const request={site:f.id,refuge:'refuge',route:[{x:4,y:4},{x:5,y:4},{x:6,y:4}]};return{s,p,f,checks,request};}
it('Ember pays actual supplies, transfers only existing staff once and leaves abandoned work paused',()=>{const{s,p,f,checks,request}=fixture();const before={...p.stock};const id=prepareWorksiteSupport(s,'p1',request,checks);expect(p.stock.P).toBe(before.P-10);expect(p.stock.M).toBe(before.M-10);expect(p.hero.readiness).toBe(3);evacuateWorksite(s,'p1',id,checks);expect(f.workers).toBe(0);expect(s.facilities.refuge.workers).toBe(4);expect(f.job?.remaining).toBe(2);expect(()=>evacuateWorksite(s,'p1',id,checks)).toThrow();});
it('cut routes and captured refuges cannot teleport or duplicate staff',()=>{const{s,f,checks,request}=fixture();const id=prepareWorksiteSupport(s,'p1',request,checks);checks.openRoute=()=>false;expect(()=>evacuateWorksite(s,'p1',id,checks)).toThrow();expect(f.workers).toBe(3);checks.openRoute=()=>true;s.facilities.refuge.owner='p2';expect(()=>evacuateWorksite(s,'p1',id,checks)).toThrow();expect(f.workers).toBe(3);});
it('Namo responds once to an observed direct approach, never concealed infiltration',()=>{const{s,f,checks,request}=fixture('namo');const id=prepareWorksiteSupport(s,'p1',request,checks);progressWorksiteSupports(s,checks);expect(f.workers).toBe(3);expect(()=>evacuateWorksite(s,'p1',id,checks)).toThrow(/observed/);checks.observedApproach=()=>true;progressWorksiteSupports(s,checks);expect(f.workers).toBe(0);expect(s.worksiteSupports[id].used).toBe(true);progressWorksiteSupports(s,checks);expect(s.facilities.refuge.workers).toBe(4);});
it('rejects unsurveyed teleport routes and expires preparation before a later week',()=>{const{s,f,checks,request}=fixture();expect(()=>prepareWorksiteSupport(s,'p1',{...request,route:[request.route[0],request.route[2]]},checks)).toThrow();const id=prepareWorksiteSupport(s,'p1',request,checks);s.turn++;expect(()=>evacuateWorksite(s,'p1',id,checks)).toThrow();expect(f.workers).toBe(3);});

import {submit,resolveWeek,preview} from '../src/simulation/engine';
import {parseMatch} from '../src/simulation/schema';
import {guestSnapshot} from '../src/network/protocol';
import {encodeCheckpoint,decodeCheckpoint} from '../src/persistence/checkpoints';
import type {Action,Match} from '../src/simulation/types';
function command(s:Match,seat:string,action:Action){return submit(s,{id:`worksite-${seat}-${s.nextSeq[seat]}`,seat,seq:s.nextSeq[seat],turn:s.turn,revision:s.revision,action});}
it('engine prepares and evacuates within one week, pauses the paid job, and persists private state',()=>{const{s,f,request}=fixture();s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};s.infrastructureSites={};s.facilities.refuge.job=undefined;const paid=command(s,'p1',{kind:'worksite-support',...request});expect(paid.reason).toBe('Order reserved; resolves with the week');expect(paid.ok).toBe(true);const projected=preview(paid.state,'p1'),id=Object.keys(projected.worksiteSupports)[0];expect(projected.players.p1.commitment).toBe(0);expect(projected.players.p1.operations).toBe(3);const evacuation=command(paid.state,'p1',{kind:'evacuate-worksite',id});expect(evacuation.ok).toBe(true);const next=resolveWeek(evacuation.state);expect(next.facilities[f.id].workers).toBe(0);expect(next.facilities[f.id].job?.remaining).toBe(2);expect(next.facilities.refuge.workers).toBe(4);expect(decodeCheckpoint(encodeCheckpoint(next)).state.worksiteSupports[id].used).toBe(true);expect(parseMatch(guestSnapshot(next,'p2'),'p2').worksiteSupports).toEqual({});});
it('engine rejects a route with hostile occupation or water before paying',()=>{const{s,request}=fixture();s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};s.infrastructureSites={};Object.assign(s.units['p2:company:0'],{x:5,y:4});expect(command(s,'p1',{kind:'worksite-support',...request}).ok).toBe(false);Object.assign(s.units['p2:company:0'],{x:25,y:25});s.map.terrain[4*s.map.width+5]='water';expect(command(s,'p1',{kind:'worksite-support',...request}).ok).toBe(false);expect(s.players.p1.hero.readiness).toBe(6);});
it('engine warns on observed armed approach before production but concealed infiltration does not trigger',()=>{for(const concealed of [false,true]){const{s,f,request}=fixture('namo');s.map.terrain.fill('meadow');s.waterChannels={};s.seaHazards={};s.shallowWater={};s.infrastructureSites={};const enemy=s.units['p2:company:0'];Object.assign(enemy,{x:4,y:6});if(concealed)enemy.effects.push({kind:'concealed',value:1,source:'test',until:10000});const prepared=command(s,'p1',{kind:'worksite-support',...request});expect(prepared.ok).toBe(true);const next=resolveWeek(prepared.state);expect(next.facilities[f.id].workers).toBe(concealed?3:0);expect(next.facilities[f.id].job?.remaining).toBe(concealed?1:2);}});
it('an unstaffed evacuated farm produces no income at a remote refuge',()=>{const{s,f}=fixture();delete f.job;f.kind='farm';const staffed=structuredClone(s);f.workers=0;const abandoned=resolveWeek(s),normal=resolveWeek(staffed);expect(normal.players.p1.stock.P-abandoned.players.p1.stock.P).toBe(15);});
