import {companionRole} from "../content/companion-production";
import type {Action,Match} from '../simulation/types';
import {path} from '../simulation/engine';
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(name:string,label:string)=>`<button data-action="${name}">${label}</button>`;
export function panel(s:Match,seat:string):string{
 const p=s.players[seat],homes=Object.values(s.households).filter(h=>h.owner===seat);if(!p||!homes.length)return '';
 const options=(pairs:[string,string][])=>pairs.map(([id,label])=>`<option value="${esc(id)}">${esc(label)}</option>`).join('');
 const units=Object.values(s.units).filter(u=>u.owner===seat&&u.alive&&(['worker','company'].includes(u.kind)||companionRole(s,u)==='rescue'));const refuges=Object.values(s.facilities).filter(f=>f.hp>0&&f.kind==='refuge');
 const power=p.profile==='nessa'?button('civil-nessa','Review Gather the Stragglers'):p.profile==='hobbit_shire'?button('civil-hobbit',"Review Neighbors’ Stores"):'';
 return `<details><summary>Civilian groups and household stores</summary><p>Finite civilian groups and deposited provisions. Each order consumes one strategic operation. Deposit and withdrawal require a free owned carrier at the household and an owned staffed supply site. No population or food is created.</p><label>Household<select id="civil-household">${options(homes.map(h=>[h.id,`${h.population} people · ${h.provisions}P · (${h.x},${h.y})`]))}</select></label><label>Existing worker, company, or rescue hind carrier<select id="civil-unit">${options(units.map(u=>[u.id,`${u.name} (${u.x},${u.y})`]))}</select></label><label>Provisions amount<input id="civil-amount" type="number" min="1" max="20" step="1" value="10"></label>${button('civil-deposit','Review deposit')}${button('civil-withdraw','Review withdrawal')}<label>Receiving refuge<select id="civil-refuge">${options(refuges.map(f=>[f.id,`${f.name} · ${f.owner} (${f.x},${f.y})`]))}</select></label><p>Transfers follow the reviewed physical route within normal carrying pace. Whole civilian groups require capacity ≤12 and normal rations of 1P per six people. Ordinary transfers need a staffed relay stable. Stores use existing carriers, capacity20P, and 2P transport. Foreign refuges require a current explicit acceptance plus mutual alliance.</p>${button('civil-people','Review ordinary civilian transfer')}${button('civil-stores','Review ordinary store convoy')}${power}<p>${p.profile==='nessa'?'Gather the Stragglers: 3 readiness and weekly hero commitment; substitutes only the relay stable, keeps rations, capacity and ordinary order.':p.profile==='hobbit_shire'?"Neighbors’ Stores: up to10 existing household P, 3 readiness, weekly hero commitment, exact2P transport and normal convoy order.":''}</p><label>Guest seat to accept<select id="civil-guest">${options(Object.keys(s.players).filter(id=>id!==seat).map(id=>[id,id]))}</select></label>${button('civil-consent','Review acceptance at selected owned refuge')}<label>Lost physical cargo<select id="civil-job">${options(Object.values(s.civilianJobs).filter(j=>j.owner===seat&&j.phase==='lost').map(j=>[j.id,`${j.population} people / ${j.provisions}P at (${j.x},${j.y})`]))}</select></label>${button('civil-recover','Review recovery at cargo position')}<p>Carrier loss strands cargo at its actual position. Recovery retains identity and costs2P plus one operation. Receiving stores remain local until withdrawn; moving a household requires withdrawing its stored P first.</p></details>`;
}
export function actionBuilder(name:string,s:Match,seat:string,value:(id:string)=>string):Action|undefined{
 if(!name.startsWith('civil-')||!s.players[seat])return;
 const household=value('civil-household'),carrier=value('civil-unit'),destination=value('civil-refuge'),amount=Number(value('civil-amount'));
 if(name==='civil-consent')return{kind:'civilian',mode:'consent',guest:value('civil-guest'),refuge:destination};
 if(['civil-deposit','civil-withdraw'].includes(name)){if(!Number.isSafeInteger(amount)||amount<1)return;return{kind:'civilian',mode:name==='civil-deposit'?'deposit':'withdraw',household,unit:carrier,amount};}
 const u=s.units[carrier];if(!u)return;
 if(name==='civil-recover'){const j=s.civilianJobs[value('civil-job')],f=j&&s.facilities[j.destination];if(!j||!f)return;const route=path(s,u,f,u.flying,u);if(!route)return;return{kind:'civilian',mode:'recover',job:j.id,carrier,route};}
 const f=s.facilities[destination];if(!f)return;const route=path(s,u,f,u.flying,u);if(!route)return;
 if(name==='civil-people'||name==='civil-nessa')return{kind:'civilian',mode:'people',household,carrier,destination,route,method:name==='civil-nessa'?'nessa':'ordinary'};
 if((name==='civil-stores'||name==='civil-hobbit')&&Number.isSafeInteger(amount)&&amount>0)return{kind:'civilian',mode:'stores',household,carrier,destination,route,amount,method:name==='civil-hobbit'?'hobbit':'ordinary'};
}
