import type {Match,Pos,Action} from '../simulation/types';import {path} from '../simulation/engine';import type {ToolState,ToolAction,ToolFunction} from '../simulation/tool-services';import type {MountState,MountAction} from '../simulation/remounts';import type {WatchState,WatchAction} from '../simulation/watch-posts';
type State=Match&ToolState&MountState&WatchState;type Result=ToolAction|MountAction|WatchAction;
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const select=(id:string,label:string,entries:[string,string][])=>`<label>${label}<select id="${id}">${entries.map(([id,text])=>`<option value="${esc(id)}">${esc(text)}</option>`).join('')}</select></label>`;
const button=(id:string,text:string)=>`<button data-action="${id}">${text}</button>`;
export function panel(s:State,seat:string,selected?:Pos):string{const p=s.players[seat],facilities=Object.values(s.facilities).filter(f=>f.owner===seat&&f.hp>0),units=Object.values(s.units).filter(u=>u.owner===seat&&u.alive),items=Object.values(s.items).filter(i=>i.owner===seat),tools=items.filter(i=>s.toolMetadata[i.id]);let html=`<details><summary>Finite tools and field repairs</summary><p>Standard tools require their own researched function. Research Tool breach / Tool repair in the research queue first. Ordinary production15M5K, one week. Forge repair kits use researched Tool repair; each construct repair consumes one locally made kit plus its normal materials and action. Field repair20M5K, two engineer weeks, at most20 existing durability and4 tool wear; wounds are unchanged.</p>${select('service-forge','Staffed forge',facilities.filter(f=>f.kind==='workshop').map(f=>[f.id,f.name]))}${select('service-function','Researched destination function',[['breach','Breach tools'],['repair','Field repair tools'],...(p.profile==='istari_forge'?[['repair-kit','Single-use Forge construct repair kit']as[string,string]]:[])])}${button('service-make','Review standard tool production')}${select('service-tool','Existing standard tool',tools.map(i=>[i.id,`${i.name} · ${i.durability}/${i.maxDurability} · salvage ceiling ${s.toolMetadata[i.id].salvageM}M/${s.toolMetadata[i.id].salvageK}K`]))}${p.profile==='dwarf_nogrod'?`<p>Modular Refit:3 readiness, weekly commitment,10M5K. Original tool consumed; new function retains its wear and salvage ceiling. Rare/unique equipment is ineligible.</p>${button('service-refit','Review Modular Refit')}`:''}${select('service-engineer','Engineer with repair tools',units.filter(u=>u.engineer).map(u=>[u.id,u.name]))}${select('service-target','Existing damaged equipment',items.filter(i=>i.durability<i.maxDurability).map(i=>[i.id,`${i.name} · ${i.durability}/${i.maxDurability}`]))}${button('service-repair','Review paid field equipment repair')}</details>`;
 if(p.profile==='human_rohan')html+=`<details><summary>Finite remount circuit</summary><p>Ordinary stable breeding:12 mounts,30P10M, three staffed weeks. Existing tired horses never disappear during an exchange. Mount fatigue is distinct from rider fatigue and wounds.</p>${select('mount-stable','Staffed stable',facilities.filter(f=>['stable','training'].includes(f.kind)).map(f=>[f.id,f.name]))}${button('mount-breed','Review mount breeding')}${select('mount-lot','Existing stable mount lot',Object.values(s.mountLots).filter(q=>q.owner===seat&&q.stable&&!q.unit).map(q=>[q.id,`${q.id} · ${q.count} mounts · fatigue ${q.fatigue}`]))}${button('mount-rest','Review normal mount recovery')}<p>Recovery costs5P/week and restores two mount-fatigue points. Remount Circuit costs3 readiness, one weekly commitment,5P and a normal transfer operation. Handler must physically leave the stable, reach the rider, then return with the tired horses.</p>${select('mount-rider','Existing rider company',units.filter(u=>Object.values(s.mountLots).some(q=>q.unit===u.id)).map(u=>[u.id,`${u.name} (${u.x},${u.y}) · mount fatigue ${Object.values(s.mountLots).find(q=>q.unit===u.id)?.fatigue??0}`]))}${select('mount-crew','Handler at stable',units.filter(u=>u.kind==='worker').map(u=>[u.id,`${u.name} (${u.x},${u.y})`]))}${button('mount-exchange','Review Remount Circuit')}</details>`;
 if(p.profile==='elf_sindar')html+=`<details><summary>Relocate the woodland watch</summary><p>Build a Watch-post through ordinary construction, then fund its10M5K equipment queue. Unfitted or stripped posts grant no observation or concealment. Reweave costs3 readiness, weekly commitment,5M+2P and one worker order. Existing staff and equipment physically move; the old position loses its functions immediately.</p>${select('watch-post','Existing woodland watch-post',facilities.filter(f=>f.kind==='watch-post').map(f=>[f.id,`${f.name} (${f.x},${f.y}) · ${f.workers} staff`]))}${button('watch-make','Review watch equipment')}${select('watch-worker','Worker at post',units.filter(u=>u.kind==='worker').map(u=>[u.id,u.name]))}<div class="form-row"><label>New watch x<input id="watch-x" type="number" min="0" max="${s.map.width-1}" value="${selected?.x??0}"></label><label>New watch y<input id="watch-y" type="number" min="0" max="${s.map.height-1}" value="${selected?.y??0}"></label></div>${button('watch-relocate','Review Reweave the Watch')}${Object.values(s.borderReports).filter(q=>q.owner===seat).slice(-3).map(q=>`<p>Week ${q.turn}: ${esc(q.text)}</p>`).join('')}</details>`;
 return html;}
export function actionBuilder(name:string,s:State,seat:string,value:(id:string)=>string):Result|undefined{if(!s.players[seat])return;const fn=value('service-function') as ToolFunction;if(name==='service-make')return{kind:'tool-service',mode:'make',facility:value('service-forge'),function:fn};if(name==='service-refit')return{kind:'tool-service',mode:'refit',facility:value('service-forge'),item:value('service-tool'),function:fn};if(name==='service-repair')return{kind:'tool-service',mode:'repair',unit:value('service-engineer'),tool:value('service-tool'),target:value('service-target')};if(name==='mount-breed')return{kind:'mounts',mode:'breed',facility:value('mount-stable')};if(name==='mount-rest')return{kind:'mounts',mode:'recover',lot:value('mount-lot')};if(name==='mount-exchange'){const u=s.units[value('mount-crew')],r=s.units[value('mount-rider')];if(!u||!r)return;return{kind:'mounts',mode:'exchange',rider:r.id,lot:value('mount-lot'),crew:u.id,route:path(s,u,r,false,u)??[]};}if(name==='watch-make')return{kind:'watch-gear',mode:'make',facility:value('watch-post')};if(name==='watch-relocate'){const u=s.units[value('watch-worker')],to={x:Number(value('watch-x')),y:Number(value('watch-y'))};if(!u)return;return{kind:'watch-gear',mode:'relocate',facility:value('watch-post'),worker:u.id,route:path(s,u,to,false,u)??[]};}}

export function describe(a:Action):string|undefined{
 if(a.kind==='tool-service')return a.mode==='make'?'15M5K; one staffed week; production queue, no strategic operation. Provisional standard tool recipe.':a.mode==='refit'?'10M5K, 3 readiness, weekly hero commitment; one staffed week, no strategic operation. Original standard tool is consumed; replacement preserves wear and salvage ceilings.':'20M5K and one strategic operation; two local engineer weeks; at most20 existing item durability restored, four finite tool wear. No wounds or unit HP restored. Provisional ordinary recipe.';
 if(a.kind==='mounts')return a.mode==='breed'?'30P10M; three staffed stable weeks; no strategic operation. Provisional twelve-mount batch.':a.mode==='recover'?'5P; one staffed stable week; no strategic operation. Removes two mount-fatigue points only; rider fatigue and wounds unchanged. Provisional recovery tuning.':'5P, 3 readiness, weekly hero commitment and one normal transfer operation. Existing rested mounts travel to the rider; tired mounts physically return. Rider wounds and fatigue are unchanged.';
 if(a.kind==='watch-gear')return a.mode==='make'?'10M5K; one staffed woodland-post week; no strategic operation. Provisional finite watch equipment recipe.':'5M plus2P normal rations,3 readiness, weekly hero commitment and one worker operation. Existing staff and gear physically relocate; old site loses observation and concealment immediately. New light30HP post, old foundation remains; provisional ordinary handling tuning.';
}
