import {observation} from '../simulation/visibility';
import type {Match} from '../simulation/types';
import type {ForestRequest,ForestState} from '../simulation/forest-routes';
export type ForestAction={kind:'consent-veil';unit:string;melian:string;accept:boolean}|({kind:'forest-power'}&ForestRequest)|{kind:'harass-convoy';unit:string;target:string}|{kind:'forest-entrance';facility:string}|{kind:'release-forest';id:string}|{kind:'inspect-forest';unit:string;point:{x:number;y:number}};
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(id:string,label:string)=>`<button data-action="${id}">${label}</button>`;
export function panel(state:Match,seat:string):string{const s=state as ForestState,p=s.players[seat];if(!p)return '';const units=Object.values(s.units).filter(u=>u.owner===seat&&u.alive&&u.active),posts=Object.values(s.facilities).filter(f=>f.owner===seat&&f.hp>0&&f.workers>0),select=(id:string,label:string,choices:{id:string;name:string}[])=>`<label>${label}<select id="${id}">${choices.map(q=>`<option value="${esc(q.id)}">${esc(q.name)}</option>`).join('')}</select></label>`;
 const normal=`<details><summary>Consent to a departing veil</summary><p>After declaring a paid withdrawal, explicitly allow an allied Melian to veil this party. No operation or stock cost; only consent to this existing withdrawal is shared, never its route. Revoke before execution to end permission and any current veil.</p>${select('forest-consent-party','Own withdrawing party',units)}${select('forest-consent-melian','Allied Melian',Object.values(s.players).filter(p=>p.profile==='melian'&&p.seat!==seat).map(p=>({id:p.seat,name:p.seat})))}${button('forest-consent','Review veil consent')}${button('forest-revoke','Review veil consent revocation')}</details><details><summary>Minor convoy harassment</summary><p>One ordinary operation attempts to harass an identified hostile ordinary party. Any cargo and resulting travel delay remain uncertain. No damage, stolen stock or extra attack. Oromë personally nearby on a marked patrol can deter it; concentrated attacks still use normal combat.</p>${select('forest-raider','Company',units.filter(u=>u.kind==='company'))}${select('forest-target','Observed hostile ordinary party',Object.values(s.units).filter(u=>u.owner!==seat&&u.alive&&observation(s,seat,u)==='identified'&&['company','worker','beast','construct'].includes(u.kind)))}${button('forest-harass','Review minor harassment')}<p>Physical inspection spends one operation to examine adjacent observed ground. It may reveal dated anonymous tracks, never hidden identities or future routes.</p><label>Ground X<input id="forest-inspect-x" type="number" value="0" min="0"></label><label>Ground Y<input id="forest-inspect-y" type="number" value="0" min="0"></label>${button('forest-inspect','Review physical track inspection')}</details>`;
 if(!['melian','orome'].includes(p.profile))return normal;
 const survey=select('forest-survey','Actually surveyed route',Object.values(s.routeSurveys).filter(r=>r.owner===seat).map(r=>({id:r.id,name:`Week ${r.turn} · ${r.route.length} points · ${r.id}`}))),owned=Object.values(s.forestRoutes??{}).filter(q=>q.owner===seat);
 const regional=p.profile==='orome'?`<p>Keep the Wild Road: 3 readiness, weekly personal commitment and provisional 1P normal travel supplies. Begin at this physically marked route; actual travel must fit the hero's ordinary allowance. One hunter cannot prevent a real battle or guard distant exits.</p>${survey}${button('forest-wild','Review personal patrol')}`:`<p>Guest Road: 3 readiness, weekly commitment, 10M, 5K and one of three maintained Anchor slots. Existing wooded survey, owned staffed endpoints and Melian beside the sanctuary required. Ordinary carriers retain normal provisions, capacity and travel time. Close inspection, cleared cover, destroyed markers or captured endpoints defeat the ward.</p>${survey}${select('forest-origin','Sanctuary endpoint',posts)}${select('forest-destination','Other staffed endpoint',posts)}${button('forest-guest','Review Guest Road')}<p>Veil the Departing: 2 readiness and tactical hero action; target must already have a paid withdrawal; allied owners must explicitly grant current veil consent. Conceals its trail, not its body. Attacking or open ground ends it; great creatures are excluded.</p>${select('forest-party','Consenting ordinary party',Object.values(s.units).filter(u=>u.alive&&observation(s,seat,u)==='identified'&&['worker','company','beast','construct'].includes(u.kind)))}${button('forest-departing','Review departing trail veil')}${select('forest-entrance','Staffed sanctuary entrance',posts)}${button('forest-threshold','Review one entrance assignment')}`;
 return normal+`<details><summary>${p.profile==='orome'?'Keep the Wild Road':'Woodland roads and thresholds'}</summary>${regional}${select('forest-release','Maintained route',owned.map(q=>({id:q.id,name:`${q.kind} · ${q.released?'released until boundary':'maintained'}`})))}${button('forest-release','Review route release')}<p>Release ends protection now; Anchor capacity returns at the turn boundary without a refund. Hero death suspends dependent magic.</p><p>${Object.values(s.forestReports??{}).filter(r=>r.owner===seat).slice(-4).map(r=>`Week ${r.turn}: ${r.kind} at ${r.point.x},${r.point.y}; identity unestablished.`).join(' ')}</p></details>`;
}
export function actionBuilder(name:string,_s:Match,_seat:string,value:(id:string)=>string):ForestAction|undefined{switch(name){case'forest-consent':case'forest-revoke':return{kind:'consent-veil',unit:value('forest-consent-party'),melian:value('forest-consent-melian'),accept:name==='forest-consent'};case'forest-inspect':return{kind:'inspect-forest',unit:value('forest-raider'),point:{x:Number(value('forest-inspect-x')),y:Number(value('forest-inspect-y'))}};case'forest-wild':return{kind:'forest-power',mode:'wild-road',survey:value('forest-survey')};case'forest-guest':return{kind:'forest-power',mode:'guest-road',survey:value('forest-survey'),origin:value('forest-origin'),destination:value('forest-destination')};case'forest-departing':return{kind:'forest-power',mode:'departing',unit:value('forest-party')};case'forest-harass':return{kind:'harass-convoy',unit:value('forest-raider'),target:value('forest-target')};case'forest-threshold':return{kind:'forest-entrance',facility:value('forest-entrance')};case'forest-release':return{kind:'release-forest',id:value('forest-release')};}}
