import type {Action,Match,Pos} from '../simulation/types';
import {path} from '../simulation/engine';
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(key:string,text:string)=>`<button data-action="${key}">${text}</button>`;
export function panel(s:Match,seat:string,selectedTile?:Pos):string {
 const p=s.players[seat];if(!p)return '';const units=Object.values(s.units).filter(u=>u.owner===seat&&u.alive&&u.kind==='company'),facilities=Object.values(s.facilities).filter(f=>f.owner===seat&&f.hp>0&&f.workers>0),surveys=Object.values(s.routeSurveys).filter(q=>q.owner===seat);
 const choices=(selected?:string)=>units.map(u=>`<option value="${esc(u.id)}" ${u.id===selected?'selected':''}>${esc(u.name)} (${u.x},${u.y})</option>`).join('');
 const posts=facilities.map(f=>`<option value="${esc(f.id)}">${esc(f.name)} (${f.x},${f.y})</option>`).join('');
 const normal=`<details><summary>Physical garrison patrol</summary><p>Assign an existing supplied company beside an existing staffed post to an actually surveyed patrol route. One normal operation; no new company, remote vision or free movement.</p><label>Garrison<select id="formation-post-unit">${choices()}</select></label><label>Existing post<select id="formation-post">${posts}</select></label><label>Surveyed route<select id="formation-survey">${surveys.map(q=>`<option value="${esc(q.id)}">${esc(q.id)} · week ${q.turn} · ${q.route.length} route points</option>`).join('')}</select></label>${button('formation-post','Review garrison assignment')}${button('formation-release','Review release from post')}<p>${Object.values(s.garrisonReports).filter(r=>r.owner===seat).slice(-3).map(r=>`Week ${r.turn}: patrol observed a crossing at ${r.point.x},${r.point.y}; identity unknown.`).join(' ')}</p></details>`;
 if(!['elf_avari','elf_fingolfin','eonwe'].includes(p.profile))return normal;
 const count=p.profile==='eonwe'?3:2,mode=p.profile==='elf_avari'?'rendezvous':p.profile==='elf_fingolfin'?'rotation':'muster';
 const members=Array.from({length:count},(_,i)=>{const u=units[i],at=selectedTile??u??{x:0,y:0};return `<fieldset><legend>Company ${i+1} and declared destination</legend><label>Existing company<select id="formation-unit-${i}">${choices(u?.id)}</select></label><label>X<input id="formation-x-${i}" type="number" min="0" max="${s.map.width-1}" value="${at.x}"></label><label>Y<input id="formation-y-${i}" type="number" min="0" max="${s.map.height-1}" value="${at.y}"></label></fieldset>`;}).join('');
 const specific=mode==='rendezvous'?'<label>Movement<select id="formation-movement"><option value="advance">Coordinated advance</option><option value="retreat">Coordinated retreat</option></select></label><p>2 readiness + one encounter action + 2 normal movement operations. Both light companies need a clear signal within four tiles. Pursuit, blocked routes and damage to the signal remain counters; no speed or damage bonus.</p>':mode==='rotation'?'<p>3 readiness + weekly commitment + 2 normal movement operations. Select two companies already assigned to distinct posts, then destinations beside their opposite posts. Normal upkeep and actual patrol visibility remain required.</p>':`<p>3 readiness + weekly commitment + 15P + 10M + all 3 ordinary movement operations. All three companies must reach distinct positions beside the declared hold-site objective. Arrival grants no fourth operation or free attack.</p><label>Staffed rally relay<select id="formation-relay">${posts}</select></label><label>Declared hold-site objective<select id="formation-objective">${s.sites.map(q=>`<option value="${esc(q.id)}">${esc(q.name)} (${q.x},${q.y})</option>`).join('')}</select></label><label>Written fallback company<select id="formation-commission"><option value="">None</option>${choices()}</select></label><label>Fallback X<input id="formation-fallback-x" type="number" min="0" max="${s.map.width-1}" value="${selectedTile?.x??0}"></label><label>Fallback Y<input id="formation-fallback-y" type="number" min="0" max="${s.map.height-1}" value="${selectedTile?.y??0}"></label><p>Clear Commission preserves only this previously written route if the staffed physical link is cut. It substitutes that company's reserved movement, not an extra move or new remote order.</p>`;
 return normal+`<details><summary>${mode==='rendezvous'?'Rendezvous Signal':mode==='rotation'?'Watch Rotation':'Muster by Terms'}</summary>${specific}${members}${button('formation-power','Review declared formation routes')}<p>One response phase permits route blocking and signal interruption. All numerical geometry is provisional.</p></details>`;
}
export function actionBuilder(name:string,s:Match,seat:string,value:(id:string)=>string):Action|undefined {
 if(name==='formation-post')return {kind:'post-garrison',unit:value('formation-post-unit'),post:value('formation-post'),survey:value('formation-survey')};if(name==='formation-release')return {kind:'release-post',unit:value('formation-post-unit')};if(name!=='formation-power')return;
 const p=s.players[seat];if(!p||!['elf_avari','elf_fingolfin','eonwe'].includes(p.profile))return;const count=p.profile==='eonwe'?3:2;
 const members=Array.from({length:count},(_,i)=>{const u=s.units[value(`formation-unit-${i}`)],to={x:Number(value(`formation-x-${i}`)),y:Number(value(`formation-y-${i}`))};if(!u||!Number.isSafeInteger(to.x)||!Number.isSafeInteger(to.y))return;const route=path(s,u,to,u.flying,u);return route?{unit:u.id,route}:undefined;});if(members.some(m=>!m))return;const selected=members.filter((m):m is NonNullable<typeof m>=>Boolean(m));
 if(p.profile==='elf_avari')return {kind:'formation-power',mode:'rendezvous',movement:value('formation-movement')==='retreat'?'retreat':'advance',members:selected};if(p.profile==='elf_fingolfin')return {kind:'formation-power',mode:'rotation',members:selected};
 const id=value('formation-commission');let commission;if(id){const u=s.units[id],to={x:Number(value('formation-fallback-x')),y:Number(value('formation-fallback-y'))};if(!u||!Number.isSafeInteger(to.x)||!Number.isSafeInteger(to.y))return;const route=path(s,u,to,u.flying,u);if(!route)return;commission={unit:id,route};}
 return {kind:'formation-power',mode:'muster',relay:value('formation-relay'),objective:value('formation-objective'),members:selected,...(commission?{commission}:{})};
}
