import {finalDeviceKind} from "../content/final-production";
import {observation,terrainObserved} from "../simulation/visibility";
import {civilianWeatherLabel} from "../simulation/civilian-rain";
import type {Action,Match} from '../simulation/types';
import {path} from '../simulation/engine';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const select=(id:string,label:string,rows:{id:string;name:string}[])=>`<label>${label}<select id="${id}">${rows.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}</select></label>`;
export function localSupportPanel(s:Match,seat:string){
 const p=s.players[seat],sites=Object.values(s.facilities).filter(f=>f.owner===seat&&f.hp>0&&f.workers>0),units=Object.values(s.units).filter(u=>u.owner===seat&&u.alive),care=Object.values(s.recoveries).filter(q=>q.owner===seat);
 let html=`<p>Travel weather: ${esc(civilianWeatherLabel(s))} Provisional four-week weather cycle.</p>`;
 if(['ulmo','vana','osse','wolf_pack','ent_grove'].includes(p.profile))html+=`<details><summary>Local knowledge</summary><p>Inspect an existing point beside the living hero for one operation. Reports are dated local observations; unmarked water conditions remain unknown. Ossë and Ent inspect one channel or grove per week.</p><label>Inspection X<input id="knowledge-x" type="number" min="0" max="${s.map.width-1}" value="${s.units[p.hero.id]?.x??0}"></label><label>Inspection Y<input id="knowledge-y" type="number" min="0" max="${s.map.height-1}" value="${s.units[p.hero.id]?.y??0}"></label><button data-action="inspect-local">Review local inspection</button></details>`;
 const knowledge=s.localKnowledgeReports[seat];if(knowledge)html+=`<p>Local observation · week ${knowledge.turn} · ${knowledge.point.x},${knowledge.point.y}: ${esc(Object.entries(knowledge.detail).map(([k,v])=>`${k}: ${v??'unknown'}`).join('; '))}. Dated evidence, not live tracking.</p>`;
 if(p.profile==='orc_fortress_clan')html+=`<details><summary>Declared shares</summary><p>Agree a finite reward before participation: one operation. After a real attack, pay the full agreed stocks at a staffed core or depot for one operation by the deadline. The nearby living hero prevents the first distribution dispute each week; old grievances remain.</p>${select('reward-unit','Participating warband',units.filter(u=>u.kind==='company'&&!u.siege))}${select('reward-site','Payout site',sites.filter(f=>['core','depot'].includes(f.kind)))}${['P','M','K','E'].map(k=>`<label>Agreed ${k}<input id="reward-${k}" type="number" min="0" max="100" value="${k==='P'?5:0}"></label>`).join('')}<label>Due week<input id="reward-due" type="number" min="${s.turn}" max="${s.turn+4}" value="${s.turn+1}"></label><button data-action="agree-reward">Review reward agreement</button><button data-action="pay-reward">Review pay agreed reward</button>${Object.values(s.warbandAgreements).filter(q=>q.owner===seat).map(q=>`<p>${esc(s.units[q.unit]?.name??q.unit)} · ${q.status} · due week ${q.due} · ${q.participated?'participated':'awaiting participation'}</p>`).join('')}</details>`;
 if(p.profile==='sauron')html+=`<details><summary>Reserved provisions</summary><p>Pack existing depot Provisions into one ordinary company: at most five, one operation. Each weekly upkeep consumes its own reserve first; no new supply, movement or stocks are created. Carried reserves are lost with the company.</p>${select('reserve-unit','Company',units.filter(u=>u.kind==='company').map(u=>({...u,name:`${u.name} · ${u.reserveProvisions??0} reserved P`})))}${select('reserve-site','Staffed depot',sites.filter(f=>f.kind==='depot'))}<label>Existing Provisions<input id="reserve-amount" type="number" min="1" max="5" value="1"></label><button data-action="pack-rations">Review pack provisions</button></details>`;
 if(p.profile==='aule')html+=`<details><summary>Worksite inspection</summary><p>Inspect one adjacent staffed worksite each week for one operation. Its next ordinary maintenance wear falls from 4 to 2 condition; costs and existing damage remain. Maintenance tuning is provisional.</p>${select('inspect-site','Worksite',sites)}<button data-action="inspect-worksite">Review inspect worksite</button></details>`;
 const beacons=sites.filter(f=>f.kind==='beacon');
 if(beacons.length)html+=`<details><summary>Visual beacon signals</summary><p>Send one existing dated report between staffed beacons within eight tiles: 2K and one operation. Solid cover, storms and heavy fog block delivery. A Star hero's personally walked link passes one light-fog signal each week. Survey costs one operation and needs a recorded actual journey.</p>${select('beacon-origin','Origin beacon',beacons)}${select('beacon-destination','Destination beacon',beacons)}${select('beacon-report','Existing report',Object.values(s.intelligenceReports).filter(q=>q.owner===seat).map(q=>({id:q.id,name:`${q.kind} · week ${q.createdTurn}`})))}${s.beaconSurveyCandidates[seat]?`<p>Personal route: ${esc(s.beaconSurveyCandidates[seat].origin)} → ${esc(s.beaconSurveyCandidates[seat].destination)}.</p><button data-action="survey-beacon-link">Review record surveyed link</button>`:''}<button data-action="signal-beacon">Review visual signal</button>${s.beaconSignals[seat]?`<p>${s.beaconSignals[seat].phase} · original report week ${s.beaconSignals[seat].reportTurn}; light fog exception ${s.beaconSignals[seat].lightFogUsed?'used':'unused'}.</p>`:''}</details>`;
 const trees=Object.values(s.vegetation).filter(v=>v.mature&&!s.loggedVegetation[v.id]&&terrainObserved(s,seat,v));
 html+=`<details><summary>Finite timber harvest</summary><p>One adjacent mature tree, an available worker and nearby staffed receiving worksite: 5P + 2M and one operation, one paid work week. Produces 10M once and consumes that tree. Provisional ordinary harvest; no magical regrowth.</p>${select('logging-worker','Worker',units.filter(u=>u.kind==='worker'))}${select('logging-tree','Existing tree',trees.map(v=>({id:v.id,name:`Tree ${v.x},${v.y}`})))}${select('logging-site','Receiving worksite',sites)}<button data-action="logging">Review timber harvest</button></details>`;
 const captives=Object.values(s.agentCaptivities).filter(q=>q.owner===seat||q.captor===seat);
 html+=`<details><summary>Ordinary agent captivity</summary><p>Capture an adjacent identified enemy courier with a real current assignment at one third health or less: one operation. It remains captive at the capture site. Veil contacts reveal only the current assignment. Rescue requires defeating or displacing the guard; the captor can release.</p>${select('agent-actor','Available actor',units.filter(u=>u.active))}${select('agent-target','Observed enemy ordinary party',Object.values(s.units).filter(u=>u.owner!==seat&&u.alive&&u.active&&['worker','company'].includes(u.kind)&&observation(s,seat,u)==='identified'))}<button data-action="capture-agent">Review capture agent</button>${select('agent-capture','Known captive',captives.map(q=>({id:q.id,name:s.units[q.unit]?.name??q.unit})))}<button data-action="free-agent">Review release or rescue agent</button>${Object.values(s.agentDisclosures).filter(q=>q.owner===seat).map(q=>`<p>Week ${q.turn}: ${esc(q.assignment.kind)} · ${esc(q.scope)} · learned contacts ${q.contacts.map(esc).join(', ')}.</p>`).join('')}</details>`;
 const heavy=Object.values(s.items).filter(i=>i.owner===seat&&i.heavy);
 if(heavy.length)html+=`<details><summary>Carry heavy equipment</summary><p>Carry one existing heavy piece: one operation. A real worker porter is required; the living Troll hero can carry it personally. It occupies 10 transport capacity and limits ordinary movement to one tile. No equipment bonuses while carried. Put down for one operation or equip normally before use.</p>${select('heavy-item','Existing heavy item',heavy.map(i=>({id:i.id,name:`${i.name} · ${i.carried?'carried':'available'}`})))}${select('heavy-carrier','Physical carrier',units.filter(u=>u.kind==='worker'||p.profile==='troll_hold'&&u.id===p.hero.id))}<button data-action="carry-heavy">Review carry heavy item</button><button data-action="drop-heavy">Review put down heavy item</button></details>`;
 html+=`<details><summary>Misleading ground signs</summary><p>An available worker or trained scout can lay one physical false trail at its current dry-ground position: 2M and one operation. Signs last three tactical revisions and disrupt later trail inference; they do not rewrite an observed event or conceal the actor.</p>${select('false-trail-unit','Worker or trained scout',units.filter(u=>u.kind==='worker'||s.scoutCredentials[u.id]?.ready))}<button data-action="lay-false-trail">Review lay false trail</button></details>`;
 const warning=s.airflowWarnings[seat];if(warning)html+=`<p>Airflow observation, week ${warning.turn}: ${esc(warning.site)} is blocked; nearby production will pause from week ${warning.penaltyTurn} if the blockage remains. This is a dated local observation.</p>`;
 if(care.length)html+=`<details><summary>Evacuate paid care</summary><p>Move an existing patient to another staffed refuge or nursery: 2P and one operation, within ordinary movement. Normal evacuation resets care to two steps. Estë or Grove personally treated care can retain one completed step once per injury and week. Travel does not heal.</p>${select('evac-care','Existing care',care.map(q=>({id:q.id,name:`${s.units[q.unit]?.name??q.unit} · ${q.remaining} steps`})))}${select('evac-destination','Receiving facility',sites.filter(f=>['refuge','medicine-nursery'].includes(f.kind)))}<button data-action="evacuate-care">Review evacuate care</button></details>`;
 const devices=Object.values(s.items).filter(i=>i.owner===seat&&i.bearer&&i.finalProduct&&finalDeviceKind(i.finalProduct)&&i.durability>0&&!i.carried);
 if(devices.length)html+=`<details><summary>Prepared field devices</summary><p>Equip an existing paid device before deployment. One operation consumes that same item into a local two-phase obstacle or screen; no hero power or new stocks. Deploy on adjacent dry ground; root snares need existing woodland. Provisional ordinary tuning.</p>${select('device-item','Fitted device',devices.map(i=>({id:i.id,name:`${i.name} · ${s.units[i.bearer!]?.name??i.bearer}`})))}<label>Deployment X<input id="device-x" type="number" min="0" max="${s.map.width-1}" value="${s.units[devices[0].bearer!]?.x??0}"></label><label>Deployment Y<input id="device-y" type="number" min="0" max="${s.map.height-1}" value="${s.units[devices[0].bearer!]?.y??0}"></label><button data-action="deploy-device">Review deploy field device</button></details>`;
 return html;
}
export function localSupportAction(name:string,s:Match,seat:string,value:(id:string)=>string):Action|undefined {
 if(name==='deploy-device'){const item=value('device-item'),i=s.items[item];return i?.owner===seat&&i.bearer?{kind:name,item,unit:i.bearer,at:{x:Number(value('device-x')),y:Number(value('device-y'))}}:undefined;}
 if(name==='carry-heavy')return {kind:name,item:value('heavy-item'),carrier:value('heavy-carrier')};
 if(name==='drop-heavy')return {kind:name,item:value('heavy-item')};
 if(name==='lay-false-trail')return {kind:name,unit:value('false-trail-unit')};
 if(name==='capture-agent')return {kind:name,unit:value('agent-actor'),target:value('agent-target')};
 if(name==='free-agent')return {kind:name,unit:value('agent-actor'),capture:value('agent-capture')};
 if(name==='logging')return {kind:name,worker:value('logging-worker'),vegetation:value('logging-tree'),facility:value('logging-site')};
 if(name==='survey-beacon-link'){const q=s.beaconSurveyCandidates[seat];return q?{kind:name,origin:q.origin,destination:q.destination,trace:q.trace}:undefined;}
 if(name==='signal-beacon')return {kind:name,origin:value('beacon-origin'),destination:value('beacon-destination'),report:value('beacon-report')};
 if(name==='agree-reward')return {kind:name,unit:value('reward-unit'),reward:{P:Number(value('reward-P')),M:Number(value('reward-M')),K:Number(value('reward-K')),E:Number(value('reward-E'))},due:Number(value('reward-due'))};
 if(name==='pay-reward')return {kind:name,unit:value('reward-unit'),facility:value('reward-site')};
 if(name==='inspect-local')return {kind:name,point:{x:Number(value('knowledge-x')),y:Number(value('knowledge-y'))}};
 if(name==='pack-rations')return {kind:name,unit:value('reserve-unit'),facility:value('reserve-site'),amount:Number(value('reserve-amount'))};
 if(name==='inspect-worksite')return {kind:name,facility:value('inspect-site')};
 if(name==='evacuate-care'){const care=value('evac-care'),destination=value('evac-destination'),q=s.recoveries[care],u=q&&q.owner===seat?s.units[q.unit]:undefined,f=s.facilities[destination];const route=u&&f?path(s,u,f,u.flying,u):undefined;return {kind:name,care,destination,route:route??[]};}
 return undefined;
}
