import type {Action,Match,Pos} from '../simulation/types';
import {path} from '../simulation/engine';
import type {NightAction,NightRelayState} from '../simulation/night-relay';
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(name:string,label:string)=>`<button data-action="${name}">${label}</button>`;
const select=(id:string,label:string,values:[string,string][])=>`<label>${label}<select id="${id}">${values.map(([key,text])=>`<option value="${esc(key)}">${esc(text)}</option>`).join('')}</select></label>`;
export function panel(state:Match,seat:string,selectedTile?:Pos):string{
 const s=state as NightRelayState,p=s.players[seat];if(!p||!s.nightRegions)return '';const own=Object.values(s.facilities).filter(f=>f.owner===seat&&f.hp>0),units=Object.values(s.units).filter(u=>u.owner===seat&&u.alive&&['worker','company','beast','hero'].includes(u.kind));const at=selectedTile??s.units[p.hero.id]??s.facilities[`${seat}:core`];
 const coordinates=`<div class="form-row"><label>Route endpoint x<input id="night-x" type="number" value="${at.x}" min="0" max="${s.map.width-1}"></label><label>Route endpoint y<input id="night-y" type="number" value="${at.y}" min="0" max="${s.map.height-1}"></label></div>`;
 const lighting=`<details><summary>Scheduled dark work and dawn watch</summary><p>Authored regional lighting: ${Object.values(s.nightRegions).filter(r=>r.owner===seat).map(r=>esc(r.period)).join(', ')}. Ordinary jobs are unchanged unless explicitly assigned a dark shift. Assignment takes one operation; lamps cost5M and one operation, permitting one normal advance. Mirror/worksite destruction or lost crew stops work.</p>${select('night-job','Existing funded infrastructure stage',Object.values(s.infrastructureWork).filter(j=>j.owner===seat&&j.phase==='work').map(j=>[j.id,`${j.id} · ${j.remaining} stages`]))}${button('night-assign','Review dark-shift assignment')}${select('night-shift','Assigned shift',Object.values(s.darkShifts).filter(q=>q.owner===seat&&q.week===s.turn).map(q=>[q.id,`${q.job} · ${q.light}${q.worked?' · worked':''}`]))}${button('night-lamps','Review maintained lamps')}${p.profile==='arien'?`${select('night-mirror','Maintained mirror',own.filter(f=>f.kind==='mirror-station').map(f=>[f.id,f.name]))}<p>Dawn Worksite:10M5K,3readiness,weekly commitment. Existing staffed funded infrastructure only, no extra cycle.</p>${button('night-dawn','Review Dawn Worksite')}${select('night-post','Occupied dawn watchpost',own.filter(f=>f.kind==='dawn-watch').map(f=>[f.id,f.name]))}${button('night-watch','Review selected lit approach')}<p>Long Shadows records visible crossing direction at one occupied dawn post; no identity or tracking after cover.</p>`:''}</details>`;
 const patrol=`<details><summary>Physical night patrol</summary><p>Train one existing ordinary formation:5P5K,one operation,one week. Ordinary trained patrol:3P and one operation. Provisional night orientation delay:one response phase; all travel uses normal movement and supplies. Reports arrive next planning, containing only actual observed crossings.</p>${select('night-unit','Existing party',units.map(u=>[u.id,`${u.name} (${u.x},${u.y})${s.scoutCredentials[u.id]?.ready?' · trained scout':''}`]))}${button('night-train','Review scout training')}${button('night-patrol','Review ordinary night patrol')}${p.profile==='tilion'?`${select('night-companion','Optional accompanying trained scout',[['','None'],...units.filter(u=>s.scoutCredentials[u.id]?.ready).map(u=>[u.id,u.name] as [string,string])])}<p>Watch of the Moon:Tilion personally moves;10P,3readiness,weekly commitment. Accompanying scout reserves its normal operation. Night Bearings reduces one orientation delay only when retracing a route Tilion actually surveyed, once per encounter.</p>${button('night-moon','Review Watch of the Moon')}`:''}<p>${Object.values(s.nightReports).filter(r=>r.owner===seat).slice(-4).map(r=>`Report ${esc(r.id)} · week${r.createdTurn} · ${r.observations.length} dated crossings`).join('<br>')}</p></details>`;
 const stations=own.filter(f=>['safehouse','relay','beacon'].includes(f.kind)).map(f=>[f.id,f.name] as [string,string]);
 const relay=`<details><summary>Physical report relay</summary><p>Send an existing dated report with an existing supplied courier, one operation and ordinary movement/upkeep. Choose its observed origin, staffed primary station and destination. The route physically visits the primary; a failed primary stops delivery.</p>${select('night-report','Existing report',Object.values(s.intelligenceReports).filter(r=>r.owner===seat&&r.observations.length).map(r=>[r.id,`${r.id} · week${r.createdTurn}`]))}${select('night-origin','Report origin',stations)}${select('night-primary','Primary station',stations)}${select('night-destination','Destination station',stations)}${button('night-message','Review ordinary message')}${p.profile==='ilmare'?`${select('night-message','Existing traveling message',Object.values(s.relayMessages).filter(q=>q.owner===seat&&q.phase==='travel').map(q=>[q.id,`${q.report} · (${q.x},${q.y})`]))}<p>Second Signal:15M5K,3readiness,weekly commitment. Route through the selected map waypoint to bypass the primary. Switch only on real primary failure, once this week, with no teleport. Witness Chain preserves observed station provenance and timestamp for the first message each week; provenance is not guaranteed truth.</p>${button('night-second','Review Second Signal')}`:''}</details>`;
 return `<details><summary>Night work and communications</summary>${coordinates}${lighting}${patrol}${relay}</details>`;
}
export function actionBuilder(name:string,state:Match,seat:string,value:(id:string)=>string):NightAction|undefined{
 if(!name.startsWith('night-'))return;const s=state as NightRelayState,p=s.players[seat];if(!p)return;const target={x:Number(value('night-x')),y:Number(value('night-y'))};
 if(name==='night-assign')return{kind:'night',mode:'assign-shift',job:value('night-job')};
 if(name==='night-lamps'||name==='night-dawn')return{kind:'night',mode:'light-shift',shift:value('night-shift'),method:name==='night-dawn'?'dawn':'lamps',...(name==='night-dawn'?{mirror:value('night-mirror')}:{})};
 const id=value('night-unit'),u=s.units[id];if(name==='night-train')return{kind:'night',mode:'train-scout',unit:id};
 if(name==='night-watch'){const f=s.facilities[value('night-post')];if(!f)return;const route=path(s,f,target);return{kind:'night',mode:'dawn-watch',post:f.id,approach:route?.slice(1)??[]};}
 if(name==='night-patrol'||name==='night-moon'){const unit=name==='night-moon'?s.units[p.hero.id]:u;if(!unit)return;return{kind:'night',mode:'patrol',unit:unit.id,route:path(s,unit,target,unit.flying,unit)??[],method:name==='night-moon'?'moon':'ordinary',...(name==='night-moon'&&value('night-companion')?{companion:value('night-companion')}:{})};}
 if(name==='night-message'){const primary=s.facilities[value('night-primary')],destination=s.facilities[value('night-destination')];if(!u||!primary||!destination)return;const first=path(s,u,primary,u.flying,u),second=path(s,primary,destination,u.flying,u);return{kind:'night',mode:'message',report:value('night-report'),courier:u.id,origin:value('night-origin'),primary:primary.id,destination:destination.id,route:first&&second?[...first,...second.slice(1)]:[]};}
 if(name==='night-second'){const q=s.relayMessages[value('night-message')],unit=q&&s.units[q.courier],f=q&&s.facilities[q.destination];if(!q||!unit||!f)return;const first=path(s,unit,target,unit.flying,unit),second=path(s,target,f,unit.flying,unit);return{kind:'night',mode:'second-signal',message:q.id,route:first&&second?[...first,...second.slice(1)]:[]};}
}

export function describe(a:Action):string|undefined {
 if(a.kind!=='night')return;
 switch(a.mode){
 case 'assign-shift':return '1 operation; no new resource charge. Explicitly schedules this already funded stage in darkness; it cannot advance until lit.';
 case 'light-shift':return a.method==='dawn'?'10M + 5K, 3 readiness, 1 hero commitment, 0 operations. Maintained staffed mirror and connected funded crew required; permits one normal work stage this week, without an extra cycle.':'5M, 1 operation. Maintained ordinary lamps permit one existing funded stage this week; no extra work cycle.';
 case 'dawn-watch':return '1 operation; no stock charge. Select one occupied dawn watchpost approach this week; records only actual visible crossing direction.';
 case 'train-scout':return '5P + 5K, 1 operation, 1 week. Reserves this existing ordinary formation for provisional scout training.';
 case 'patrol':return a.method==='moon'?`10P, 3 readiness, 1 hero commitment, ${a.companion?'1 operation for the accompanying scout':'0 operations'}. Personal physical night route at normal movement; dated observations become available next planning.`:'3P, 1 operation. Existing trained scout follows the real route after one provisional orientation response phase; dated observations arrive next planning.';
 case 'message':return '1 operation; normal courier upkeep and movement. Physically carries the existing dated report through staffed stations; no new intelligence is created.';
 case 'second-signal':return '15M + 5K, 3 readiness, 1 hero commitment, 0 operations. Prepares one real alternate courier route this week, used only after primary relay failure; normal travel and upkeep remain.';
 }
}
